### ISSUE TITLE
bower install - github.com connection timed out

### ISSUE THREAD

**Issue by pmichna** [angular/angular-phonecat#141]
```
pmichna@p:~/angular-phonecat$ npm install

> angular-phonecat@0.0.0 postinstall /home/pmichna/angular-phonecat
> bower install

bower angular-mocks#~1.2.15 not-cached git://github.com/angular/bower-angular-mocks.git#~1.2.15
bower angular-mocks#~1.2.15    resolve git://github.com/angular/bower-angular-mocks.git#~1.2.15
bower bootstrap#~3.1.1      not-cached git://github.com/twbs/bootstrap.git#~3.1.1
bower bootstrap#~3.1.1         resolve git://github.com/twbs/bootstrap.git#~3.1.1
bower angular#1.2.x         not-cached git://github.com/angular/bower-angular.git#1.2.x
bower angular#1.2.x            resolve git://github.com/angular/bower-angular.git#1.2.x
bower jquery#1.10.2         not-cached git://github.com/jquery/jquery.git#1.10.2
bower jquery#1.10.2            resolve git://github.com/jquery/jquery.git#1.10.2
bower angular-resource#~1.2.15       not-cached git://github.com/angular/bower-angular-resource.git#~1.2.15
bower angular-resource#~1.2.15          resolve git://github.com/angular/bower-angular-resource.git#~1.2.15
bower angular-route#~1.2.15          not-cached git://github.com/angular/bower-angular-route.git#~1.2.15
bower angular-route#~1.2.15             resolve git://github.com/angular/bower-angular-route.git#~1.2.15
bower angular-animate#~1.2.15        not-cached git://github.com/angular/bower-angular-animate.git#~1.2.15
bower angular-animate#~1.2.15           resolve git://github.com/angular/bower-angular-animate.git#~1.2.15
bower angular-route#~1.2.15             ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-route.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.130]: errno=Connection timed out

npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.11.0-19-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/pmichna/angular-phonecat
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pmichna/angular-phonecat/npm-debug.log
npm ERR! not ok code 0
```

Sometimes it times out on `angular-animate`, sometimes on `bootstrap`, sometimes on something else. What's wrong?

**Comment by HarishBoke** [comment]
Thanks a lot! @pmichna   git config --global url."https://".insteadOf git:// solved the problem.

**Comment by Geo86** [comment]
Thank you that did the trick for me as well :) !

**Comment by rickyswan** [comment]
git config --global url."https://".insteadOf git:// fixed this for me too! thanks

**Comment by khacnhat** [comment]
Thank!, pmichna's method worked for me.
git config --global url."https://".insteadOf git://

**Comment by Kevded** [comment]
@pmichna Thanks

**Comment by zwhitchcox** [comment]
I had to change it to http. the https protocol still didn't work for me

**Comment by callmehiphop** [comment]
:+1:

**Comment by tangyong** [comment]
Great!

git config --global url."https://".insteadOf git://

**Comment by williamokano** [comment]
Great, solved my problem.

This should be on the AngularJS tutorial for beginners. I know that it's pretty fast and too easy to find this particularly solution on google, but it would be better to don't have to leave the page to find this.

Thanks @pmichna

**Comment by axinging** [comment]
git config --global url."https://".insteadOf git://  fix for me. I am behind a cory proxy.

**Comment by petebacondarwin** [comment]
Would anyone like to make a pull request to the angular.js repository with an update to the tutorial explaining these problems?

**Comment by jasonrogena** [comment]
It turns out this happens if the user running the command has SSH keys that are not registered on GitHub. You should either register the public key or remove the key-pair from the users .ssh directory.

**Comment by soubhik-c** [comment]
I've few public keys registered from my .ssh/ and then some not registered with GitHub. This shouldn't stop me from accessing .. I got multiple package name connection timeout failures on multiple runs "git ls-remote exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.130]: errno=Connection timed out". 

git config --global url."https://".insteadOf git:// did the trick. Thanx a lot.

**Comment by marcellodesales** [comment]
Wow, this trick solved my builds using Docker!!!!

```
git config --global url."https://".insteadOf git://
```

**Comment by Priyanka-Naik** [comment]
thanks :+1:

**Comment by celsonrd** [comment]
Obrigado! otima dica.

**Comment by wholehogsoftware** [comment]
Works for me as well.

**Comment by sopracreau** [comment]
Ca marche pour moi aussi ...
Thanks a lot

**Comment by torcellite** [comment]
Ah, thank you.

**Comment by arcreative** [comment]
:+1: This works for me as well... thanks guys!

**Comment by huangruoyu** [comment]
great! very helpful!!!

**Comment by borislopezaraoz** [comment]
Thanks! great tip

**Comment by AtulKamra** [comment]
I am getting issue while running a job from Jenkins for connecting to Git for building code. any idea what can be done to fix this?

Error - 

Started by user anonymous
Building in workspace /var/jenkins_home/jobs/iOS_Build/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url GIT Repository URL # timeout=10
Fetching upstream changes from GIT Repository URL > git --version # timeout=10
using .gitcredentials to set credentials
 > git config --local credential.username USER_NAME# timeout=10
 > git config --local credential.helper store --file=/tmp/git5514383632996462831.credentials # timeout=10
 > git -c core.askpass=true fetch --tags --progress GIT Repository URL +refs/heads/*:refs/remotes/origin/*

 > git config --local --remove-section credential # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from GIT Repository URL 
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:763)
	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1012)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1043)
	at hudson.scm.SCM.checkout(SCM.java:485)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1275)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:610)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:532)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:408)
Caused by: hudson.plugins.git.GitException: Command "git -c core.askpass=true fetch --tags --progress GIT Repository URL +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout: 
stderr: fatal: unable to access 'GIT Repository URL ': Failed to connect to stash.com port 443: Connection timed out

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1640)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1388)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$300(CliGitAPIImpl.java:62)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:313)
	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:761)
	... 11 more
ERROR: null

**Comment by paulkr** [comment]
`git config --global url."https://".insteadOf git://` worked for me! Thanks!

**Comment by guilherme22** [comment]
git config --global url."https://".insteadOf git:// worked for me too ! Thanks !

**Comment by swapy** [comment]
Yes this works perfect! Thanks.

**Comment by git-msp** [comment]
I did git config --global url."https://".insteadOf git://
but still issue

fatal: unable to access 'https://github.com/git-msp/CubeGeneratorWeb.git/': Failed to connect to 192.135.82.70 port 1080: Timed out

**Comment by neakves** [comment]
Tanks Brow 
git config --global url."https://".insteadOf git:// 
It worked !

**Comment by phppa** [comment]
Excelente, resolveu o problema !

git config --global url."https://".insteadOf git://

**Comment by PStoner3** [comment]
I am still experiencing this issue.
Here is my global .gitconfig
[filter "lfs"]
    required = true
    clean = git-lfs clean %f
    smudge = git-lfs smudge %f
[user]
    name = Paul Stoner
    email = pstoner6765@gmail.com
[core]
    gitProxy = "ssh" for "kernal.org"
    gitProxy=default-proxy
[http]
    proxy = http://<name>:<port>
[https]
    proxy = http://<name>:<port>
[url "https://"]
	insteadOf = git://

As you can see, I've set my proxy, set the url.https. Nothing seems to work.
I am running 
Node V5.0.0
npm v3.8.9
bower v1.7.9
git v2.8.1.windows.1

I simply cannot seem to get bower working

**Comment by ChrisGrigg** [comment]
@PStoner3 I was in the same predicament as you. To solve it I just removed "http.proxy", "https.proxy" and "url..insteadOf" from the global and local .gitconfig files and it worked. Perhaps I had conflicts with other settings on my system and simplifying things helped.

**Comment by vivex** [comment]
I am facing this issue in my ubuntu system as well, node version is 5.0.0 , bower version is 1.7.9
i am able to access github there is no network problem no proxy, and using https:// only. But still it is saying 

```
 ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-route.git", exit code of #128 fatal: unable to access 'https://github.com/angular/bower-angular-route.git/': Could not resolve host: github.com

Additional error details:
fatal: unable to access 'https://github.com/angular/bower-angular-route.git/': Could not resolve host: github.com
```

**Comment by brandonmceachern** [comment]
I'm working behind a firewall and change the config url.. Also, I keep trying bower install. The downloads would time out but each try added more to the cache so eventually I had all the dependencies.

**Comment by savanr** [comment]
For me reverse engineering works :stuck_out_tongue_winking_eye: 

> git config --global url."git://".insteadOf https://

If you have manually run above commands then you should remove those entries first from ~/.gitconfig file. So for that open that file

> nano ~/.gitconfig

Replace these lines
```
[url "https://"]
	insteadOf = git:// 

```

with this

```
[url "git://"]
	insteadOf = https://
```

Save and restart your terminal.

**Comment by cdll** [comment]
``git config --global url."https://".insteadOf git://`` did not solve my problem but ``git config --global url."git://".insteadOf https://`` that @savanr said help me a lot~
hope everyone see it and so much thank to @savanr 😊

**Comment by Dectinc** [comment]
Another possible issue is that you are using incompatible versions of nss and curl, try updating nss and curl.

For example, on CentOS, run `yum upgrade -y nss curl`

**Comment by skyrw** [comment]
bower d3#3.5.6                                              ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/mbostock-bower/d3-bower.git", exit code of #128 error:  while accessing https://github.com/mbostock-bower/d3-bower.git/info/refs  fatal: HTTP request failed
Additional error details:
error:  while accessing https://github.com/mbostock-bower/d3-bower.git/info/refs
fatal: HTTP request failed

I met the above error message,and it use 'https',What should I do,thanks
