### ISSUE TITLE
bower_components path is wrong

### ISSUE THREAD

**Issue by palcu** [angular/angular-phonecat#143]
Started the tutorial `v1.3.0-build.2603`. The path to `bower_components` in every `index.html` is `../bower_components/angular/angular.js`. However, `bower_components` is now installed in the `app` directory.

```
hobbit:~/Projects/angular-phonecat% npm -v                                                                                                                   
1.4.3
hobbit:~/Projects/angular-phonecat% bower -v
1.3.1
```

I think the paths in the tutorial should be changed. Can I proceed, or did I do something wrong?

EDIT:
- also the tests should be updated

**Comment by ravimalik20** [comment]
@lmorchard morchard it did save me!! Kudos!!
