### ISSUE TITLE
Issue with bower

### ISSUE THREAD

**Issue by bparrish** [angular/angular-phonecat#163]
Having an issue with Bower at the beginning of the tutorial.. here is the log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart angular-phonecat@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info angular-phonecat@0.0.0 Failed to exec prestart script
9 error angular-phonecat@0.0.0 prestart: `npm install`
9 error Exit status 1
10 error Failed at the angular-phonecat@0.0.0 prestart script.
10 error This is most likely a problem with the angular-phonecat package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     npm install
10 error You can get their info via:
10 error     npm owner ls angular-phonecat
10 error There is likely additional logging output above.
11 error System Windows_NT 6.2.9200
12 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
13 error cwd D:\Dev\AngularDevelopment\angular-phonecat
14 error node -v v0.10.28
15 error npm -v 1.4.9
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

**Comment by rsford31** [comment]
I'm having an issue installing bower as well. When I run npm install I get:
$ npm install
npm WARN package.json karma-chrome-launcher@0.1.7 No README data

> angular-phonecat@0.0.0 postinstall c:\Users\cl07023\angular-phonecat
> bower install

bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 1.8s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 1.2s
bower retry         Request to https://bower.herokuapp.com/packages/angular-rout
e failed with ETIMEDOUT, retrying in 1.2s
bower retry         Request to https://bower.herokuapp.com/packages/bootstrap fa
iled with ETIMEDOUT, retrying in 1.2s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 1.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-reso
urce failed with ETIMEDOUT, retrying in 1.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular-anim
ate failed with ETIMEDOUT, retrying in 1.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-reso
urce failed with ETIMEDOUT, retrying in 2.2s
bower retry         Request to https://bower.herokuapp.com/packages/angular-anim
ate failed with ETIMEDOUT, retrying in 3.9s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 3.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-rout
e failed with ETIMEDOUT, retrying in 3.4s
bower retry         Request to https://bower.herokuapp.com/packages/bootstrap fa
iled with ETIMEDOUT, retrying in 2.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 3.3s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 3.5s
bower retry         Request to https://bower.herokuapp.com/packages/angular-reso
urce failed with ETIMEDOUT, retrying in 5.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular-anim
ate failed with ETIMEDOUT, retrying in 7.7s
bower retry         Request to https://bower.herokuapp.com/packages/bootstrap fa
iled with ETIMEDOUT, retrying in 5.6s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 7.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular-rout
e failed with ETIMEDOUT, retrying in 4.7s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 5.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 7.4s
bower retry         Request to https://bower.herokuapp.com/packages/angular-reso
urce failed with ETIMEDOUT, retrying in 8.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular-anim
ate failed with ETIMEDOUT, retrying in 11.3s
bower retry         Request to https://bower.herokuapp.com/packages/bootstrap fa
iled with ETIMEDOUT, retrying in 10.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-rout
e failed with ETIMEDOUT, retrying in 14.7s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 12.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 10.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 10.2s
bower retry         Request to https://bower.herokuapp.com/packages/angular-reso
urce failed with ETIMEDOUT, retrying in 23.9s
bower retry         Request to https://bower.herokuapp.com/packages/angular-anim
ate failed with ETIMEDOUT, retrying in 18.3s
bower retry         Request to https://bower.herokuapp.com/packages/bootstrap fa
iled with ETIMEDOUT, retrying in 28.5s
bower retry         Request to https://bower.herokuapp.com/packages/jquery faile
d with ETIMEDOUT, retrying in 30.6s
bower retry         Request to https://bower.herokuapp.com/packages/angular-rout
e failed with ETIMEDOUT, retrying in 23.0s
bower retry         Request to https://bower.herokuapp.com/packages/angular-mock
s failed with ETIMEDOUT, retrying in 23.1s
bower retry         Request to https://bower.herokuapp.com/packages/angular fail
ed with ETIMEDOUT, retrying in 22.4s
bower ETIMEDOUT     Request to https://bower.herokuapp.com/packages/angular-reso
urce failed: connect ETIMEDOUT

npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodej
s\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\cl07023\angular-phonecat
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\cl07023\angular-phonecat\npm-debug.log
npm ERR! not ok code 0

I have tried running npm install -g bower and get this:
C:\Users\cl07023\AppData\Roaming\npm\bower -> C:\Users\cl07023\AppData\Roaming\n
pm\node_modules\bower\bin\bower
bower@1.3.12 C:\Users\cl07023\AppData\Roaming\npm\node_modules\bower
├── is-root@1.0.0
├── junk@1.0.0
├── stringify-object@1.0.0
├── abbrev@1.0.5
├── chmodr@0.1.0
├── which@1.0.8
├── osenv@0.1.0
├── archy@0.0.2
├── rimraf@2.2.8
├── opn@1.0.1
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.5
├── lockfile@1.0.0
├── retry@0.6.0
├── nopt@3.0.1
├── tmp@0.0.23
├── q@1.0.1
├── request-progress@0.3.0 (throttleit@0.0.2)
├── shell-quote@1.4.2 (array-filter@0.0.1, array-map@0.0.0, array-reduce@0.0.0,
jsonify@0.0.0)
├── semver@2.3.2
├── chalk@0.5.0 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0
.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── fstream@1.0.3 (inherits@2.0.1)
├── p-throttler@0.1.0 (q@0.9.7)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── promptly@0.2.0 (read@1.0.5)
├── bower-config@0.5.2 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.1)
├── tar-fs@0.5.2 (pump@0.3.5, tar-stream@0.4.7)
├── decompress-zip@0.0.8 (mkpath@0.1.0, nopt@2.2.1, touch@0.0.2, readable-stream
@1.1.13, binary@0.3.0)
├── request@2.42.0 (caseless@0.6.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0,
forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.4.0, tunnel-agent@0.4.0, q
s@1.2.2, node-uuid@1.4.2, mime-types@1.0.2, form-data@0.1.4, http-signature@0.10
.1, bl@0.9.3, tough-cookie@0.12.1, hawk@1.1.1)
├── glob@4.0.6 (inherits@2.0.1, once@1.3.1, minimatch@1.0.0)
├── bower-registry-client@0.2.2 (request-replay@0.2.0, graceful-fs@2.0.3, lru-ca
che@2.3.1, mkdirp@0.3.5, async@0.2.10, request@2.27.0)
├── cardinal@0.4.0 (redeyed@0.4.4)
├── update-notifier@0.2.0 (semver-diff@0.1.0, string-length@0.1.2, latest-versio
n@0.2.0, configstore@0.3.2)
├── mout@0.9.1
├── inquirer@0.7.1 (figures@1.3.5, mute-stream@0.0.4, through@2.3.6, readline2@0
.1.0, lodash@2.4.1, cli-color@0.3.2, rx@2.3.22)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── insight@0.4.3 (object-assign@1.0.0, async@0.9.0, chalk@0.5.1, os-name@1.0.1,
 lodash.debounce@2.4.1, tough-cookie@0.12.1, configstore@0.3.2, inquirer@0.6.0)
When I try running npm install again I get the same message.

I've deleted the files from ~\AppData\Roaming\bower\cache and re-ran npm install. Same issue.
I've used bower cache clean and then re-ran npm install. Same issue.
I've tried git config --global url."https://".insteadOf git:// and re-ran npm install. Same issue. 
I've never had bower_components appear in angular-phonecat\app.

Just a note I am behind a fire wall.

Any ideas?

**Comment by thetallweeks** [comment]
I tried installing bower globally and cleaning cache but I wasn't even getting a bower_components folder.

I found that the **html5-boilerplate dependency was causing an error**:

```
bower EINVRES       Request to https://bower.herokuapp.com/packages/html5-boilerplate failed with 500
```

So I removed the dependency, ran `bower install`, then added it back with
```
bower install html5-boilerplate --save
```

**Comment by natstar93** [comment]
@peantunes Thanks, deleting node_modules worked for me :)

**Comment by shoaibuddin** [comment]
This is due to permission issue. Try: 
sudo bower install --allow-root

**Comment by chandu87** [comment]
finally this solution solved my problem... Thanks
git config --local url."https://".insteadOf git://

**Comment by Justin-Case** [comment]
I would guess that you're on a Windows computer and filepath maximum lengths were overrun.  You might try mapping an N: drive to:

net use n: \\computername\D$\Dev\AngularDevelopment\ang2 /persistent:yes

...and change to the N: drive.  Then CD into your project and continue the npm install from there.  Now, the tree depth and filepaths are all short enough (hopefully) for bower to install correctly.

**Comment by zishanj** [comment]
I was facing this same issue on my Ubuntu and I have installed `git`:

`sudo apt-get install git`

For windows users, they should visit this link to install `git`: https://msysgit.github.io/

**Comment by ankur711** [comment]
when i do npm install, this will show following error
what should I do.?
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.13.0-32-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /home/ankur/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/home/ankur/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ankur/npm-debug.log

**Comment by Justin-Case** [comment]
@ankur711 "package.json npm can't find a package.json file in your current directory."

Doesn't that say it all?  You need to run "npm install" from your project directory.

**Comment by xiaofire** [comment]
>On Windows 8.1, I was getting the same as the op. Fixed by using Git Bash:

Opened up Git Bash
In Git Bash, cd to angular-phonecat directory
In Git Bash, npm install
Then I:

Opened up a command window (i.e. cmd), not in Git Bash
In the command window, cd to angular-phonecat directory
In the command window, npm start
Web server starts and I can see the on http://localhost:8000/app

I guess Git Bash works because it knows about Git, alternative would be to have the appropriate environment variable. But this worked for me. If I remember correctly, Git Bash installed when I installed Git for use with Visual Studio.

Update:

Added 
%PROGRAMFILES(x86)%\Git\bin;%PROGRAMFILES(x86)%\Git\cmd to my path environment variable and git is now recognised in command window (which it wasn't before).

This was helpful (thanks rodriwasabi):

http://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path

Update 2:

To check this works, I removed angular-phonecat and started again. Everything worked perfectly this time. In other words, following the tutorial install instructions. Changing my path environment variable did the trick.

Persevere folks, it's worth it:-)


worked!

**Comment by Abhilash-Chandran** [comment]
Possible Solution for "Git not in Path" error (Windows 10):

1. I simply switched the Default shell in GitHub Desktop app(Windows 10) to cmd.
2. Opened the the angular-phonecat in a GitShell(which inturn is a cmd). 
3. From here again I ran "npm install" and it proceeds fine without errors.

I think switching this option simply adds git to your env path. Simply eases out the way you add the path in env. :)

Hope it helps some one.

**Comment by Justin-Case** [comment]
@xiaofire If you install git from Visual Studio it probably adds the path information only to the (many) VS-related command prompts but not necessarily to the system environment.  I just transport important path variables over to the system environment so I don't have to think too much about it.

**Comment by undergrinder** [comment]
@DuncanJack , thank you it works fine! (with gitbash+cmd)

**Comment by pejman-saberin** [comment]
I was having this issue when I was trying to download angular-seed project on windows 10. I installed GIT command line. Then Instead of downloading the ZIP, I used GIT command line to download the project. For the network issue I typed in git config --global url."https://".insteadOf git:// as others have mentioned.

**Comment by RajeswarReddy** [comment]
Hi, i am getting this error, while starting npm start . Can anyone rectify please.


npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
npm ERR! Exit status 1 
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a 0.0.0.0 -p 8000
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Rajesh\angular-phonecat\npm-debug.log

**Comment by OutsourcedGuru** [comment]
@RajeswarReddy Sounds like it's trying to start up a webserver on IP address 0.0.0.0 (which is like saying "on all internal and external addresses" using TCP port 8000.  If it were me I think I'd jump to a DOS prompt and run something like...

    netstat -a | find "LISTENING"

...and see if you already have something that's using port 8000.  If so, then you might have to either stop that other server or use a different port like 3000, 3001, 5000 or something like that.

**Comment by stowjam** [comment]
Help I am getting following errors: window 8.1

C:\Users\Jam\Desktop\B2B>npm install
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ECONNREFUSED
npm ERR! errno ECONNREFUSED
npm ERR! syscall connect

npm ERR! Error: connect ECONNREFUSED 127.0.0.1:8080
npm ERR!     at Object.exports._errnoException (util.js:870:11)
npm ERR!     at exports._exceptionWithHostPort (util.js:893:20)
npm ERR!     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
npm ERR!  { [Error: connect ECONNREFUSED 127.0.0.1:8080]
npm ERR!   code: 'ECONNREFUSED',
npm ERR!   errno: 'ECONNREFUSED',
npm ERR!   syscall: 'connect',
npm ERR!   address: '127.0.0.1',
npm ERR!   port: 8080,
npm ERR!   parent: 'b2b' }
npm ERR!
npm ERR! If you are behind a proxy, please make sure that the
npm ERR! 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Jam\Desktop\B2B\npm-debug.log

**Comment by petebacondarwin** [comment]
@stowjam - the error log you have provided indicates that the package.json that you are using does not match the one in the phonecat project. Are you sure you are using this project?

In any case, I believe the problem you have is that `bower install && ./node_modules/.bin/gulp build` is a BASH command and you are trying to run this command from the Windows command prompt, which does not understand that syntax.

**Comment by stowjam** [comment]
HI 
Sorry I am not sure but I am running the npm install from Node.js prompt
So am not sure why it is picking up a BASH command
I had to fork the project from GITHUB then copy it locally 
Then load node.js and run npm install 
Now I am getting all the below issues 
It was alot more but it is down to the belwo issues now....

Basically I have been told I need to get this running on my windows machine before I can start the contract... spent two days trying to fumble through as i do not know node.js or npm so am on a major learning curve to work out what i am doing
here is the screenshot

              

Date: Wed, 16 Mar 2016 04:38:00 -0700

**Comment by stowjam** [comment]
What I need to do then to get the project running can you suggest?

**Comment by petebacondarwin** [comment]
Which project on github did you fork?

**Comment by stowjam** [comment]
cameliaTech/B2B private
It is private unfortunately -  i got an invite
they have a number of dependancies also 
darn i think i am up the creak on this one...
## Dependencies

 - Mongodb 
 - Elasticsearch (with two indexes named 'b2b-companies' and 'words' => `curl -XPUT 'http://localhost:9200/b2b-companies/'`)
 - 
 
## Run the app

    npm install
    npm run dev
    
### To run locally but connect to QA db
    NODE_ENV=qa MONGO_USER=admin MONGO_PASSWORD=??????? npm run dev
    

### open in browser
http://localhost:3000/

### Test
   
#### All
 
    npm run all-test

#### Functional
    npm run e2e-test

**Comment by petebacondarwin** [comment]
I'm afraid that this project has been developed on a unix based system,
which is why the tools are not working for you on Windows.
While it is completely possible to fix this, it is outside of the scope of
this issue, since it is neither related to phonecat nor a issue with the
project.

I suggest that you ask around on StackOverflow or node related mailing
lists to see if there is someone that can give you support.

**Comment by stowjam** [comment]
perhaps i should just uninstall all and start fresh
but the main question is I am not running this in gitbash so not sure if my instructions are incorrect to run npm from the node.js command prompt ; becuase of your comment that it is a BASH COMMAND.....or did i misinterpret what you were saying.... whoops....

**Comment by divye1995** [comment]
The issue us with bower and its is solved if you run this

sudo chown -R $USER:$GROUP ~/.npm
sudo chown -R $USER:$GROUP ~/.config
