### ISSUE TITLE
npm run protractor step fails on windows

### ISSUE THREAD

**Issue by gdadams123** [angular/angular-phonecat#176]
Running via cygwyn on windows:
$ npm run protractor

> angular-phonecat@0.0.0 preprotractor C:\git\angular-phonecat
> npm run update-webdriver
> 
> angular-phonecat@0.0.0 preupdate-webdriver C:\git\angular-phonecat
> npm install
> 
> angular-phonecat@0.0.0 postinstall C:\git\angular-phonecat
> bower install
> 
> angular-phonecat@0.0.0 update-webdriver C:\git\angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor C:\git\angular-phonecat
> protractor test/protractor-conf.js

Using ChromeDriver directly...

C:\git\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\net\index.js:48
    interfaces[key].forEach(function(ipAddress) {
                    ^

npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\nodejs\node.exe" "C:\nodejs\node_modules\npm\bin\npm-cli.js" "run" "protractor"
npm ERR! cwd C:\git\angular-phonecat
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm

**Comment by Benjamin-Dada** [comment]
Changing `chromeOnly: true` to false; worked for me!

**Comment by ctp-placebo** [comment]
It's 2019 and I'm having the same problem. 

`> angular-phonecat@0.0.0 protractor C:\Users\xxxxx\yyyyyy\Ang1Refresher\phonecat\angular-phonecat
> protractor e2e-tests/protractor.conf.js

[08:54:20] I/launcher - Running 1 instances of WebDriver
[08:54:20] I/local - Starting selenium standalone server...      
[08:54:20] E/launcher - Error: Error: Server terminated early with status 1
    at earlyTermination.catch.e (C:\Users\xxxxx\yyyyy\Ang1Refresher\phonecat\angular-phonecat\node_modules\selenium-webdriver\remote\index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:68:7)[08:54:20] E/launcher - Process exited with error code 100       
npm ERR! code ELIFECYCLE
npm ERR! errno 100
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script. 
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxx\AppData\Roaming\npm-cache\_logs\2019-09-16T06_54_20_981Z-debug.log`  

Have tried setting 'chromeOnly: fasle' and manually updating webdriver-managar(een though `npm run protractor` does npm install and webdriver-manager update on start.   

On Win10 latest.
