### ISSUE TITLE
Angularjs tutorial - 'npm start' not working

### ISSUE THREAD

**Issue by lavalampan** [angular/angular-phonecat#180]
I'm having problems with the "npm command" found at the end of the first step of the tutorial. I've overviewed the other threads on this question but haven't found the answers I'm looking for.

The project is cloned from github, Node is installed. I've confirmed this with

$ node --version
v. 0.10.29
orienting myself to ../GitHub/angular-phonecat in Gitbash, I write

$ npm install
npm WARN optional dep failed, continuing fsevents@0.2.0
|

> ws@0.4.31 install c:\..\Documents\github\angular-phonecat\node_modules\karma\node_modules\socket.io\node_modules\socket.ioclient\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
\

Next step is

$ npm start
> angular-phonecat@0.0.0 prestart c:\..\Documents\github\angular-phonecat
> npm install

Now, browsing to "localhost:8000/app/index.html" explained in the tutorial, i'm getting a 404-error message.

I guess that's not a correct output.. so just wondering if any of you guys have any suggestions where to go next?

**Comment by eabdelmoneim** [comment]
Ran into a 'npm start' failure on MacOSX as well.  Unlike the people commenting on Windows, my issue was making sure I ran the 'npm install' as specified in the tutorial as root.  

Issue was fixed by doing a 'sudo npm install'.

**Comment by ukizhake** [comment]
i had to remove the public folder 

just stayed with 0.0.0.0 and 8000

**Comment by JuanCarlosC** [comment]
@eabdelmoneim I'm on OSX 10.10 and that worked! Thanks!

**Comment by mrosata** [comment]
I had this problem as well. Running the `http-server` command directly rather then using `npm start` in terminal helped diagnose the issue. I'm on Ubuntu 14.04 LTS, nvm using node v0.12.2
```sh
$ http-server -a 0.0.0.0 -p 8000
   events.js:85
         throw er; // Unhandled 'error' event
               ^
Error: listen EADDRINUSE
```
The error name is fairly straight forward, E(rror) ADDR(ess) IN USE, so I tried the suggestion above and used `http-server -a 127.0.0.1 -p 8080`, and got the same error. So if that happens to you don't get discouraged. I then tried `http-server -a 127.0.0.1 -p 5000` to no success and finally `-p 3000`, which turned out to be available and working.
I'm guessing 8080 is tied up because of apache but I don't remember node not being able to listen to 8080 on my last install before using nvm. Either way. Solution works, and If you are having same error code, keep trying until you find an open port. Then, to implement working solution, use @erknrio instruction, change the `"start"` property under `"scripts"` in the package.json file from `"http-server -a 0.0.0.0 -p 8000"` to `"http-server -a 127.0.0.1 -p <the open port>"`.
```json
...
  },
  "scripts": {
    "postinstall": "bower install",

    "prestart": "npm install",
    "start": "http-server -a 127.0.0.1 -p 3000",

    "pretest": "npm install",
```

Thanks @erknrio

**Comment by petebacondarwin** [comment]
Sometimes the port is tied up if you happen to leave a previous `http-server` or similar running in the background. You can find out on OS/X what the port is being used by if you run

```
lsof -iTCP:8080
```

**Comment by erknrio** [comment]
Your welcome @mrosata :).

**Comment by farskid** [comment]
guys "npm test" does not work for me although "npm start " is working fine!
it outputs the error describing that it can not find "socket.io-client".
i'm using windows 7 by the way.

**Comment by kaustubh12345** [comment]
Those who have problem with live-server not opening a browser window just do 
"start": "live-server --open=src --port=3000 --host=127.0.0.1"
in the script part of package.json.

**Comment by RajeswarReddy** [comment]
How to use these? I am at step 0. how to change the code to step 1 and edit, do the practice. Kindly share if any vedios are there?

**Comment by sajedshaikh777** [comment]
@erknrio Thank you very much for this solution :+1:

**Comment by erknrio** [comment]
Thanks @sajedshaikh777, which version of Ubuntu are you using?

**Comment by beacham** [comment]
For windows 7, change to the Samples/Chapter01/live-server-test folder, and run these commands:

# npm install

# npm start

On my system the chrome browser (default) launches per the book.

**Comment by vishalmule17** [comment]
@beacham npm start work for me

**Comment by ridkadri** [comment]
npm start, npm install, live-server all not working! have done all the above solutions. i run a windows 10

**Comment by Jibinj21** [comment]
npm start is not working for me too some time it will work and then I can't stop the server then it will become not responding (git bash) and then I will close the git bash and opens again and some times npm start will not work and it will give errors  can anyone help me

**Comment by akgupta002** [comment]
I was facing the same issue that I was unable to run 'npm start' command. Going through above comments, I changed the port from 8000 to 8080 in 'package.json' file and it finally run. 
Earlier, it was `"start": "http-server ./app -a localhost -p 8000 -c-1",` 
Now, it is `"start": "http-server ./app -a localhost -p 8080 -c-1",`.

Server started on 'npm start' and hence problem resolved.

**Comment by uinstinct** [comment]
I figured out that if **ignore-scripts** is set to *true* in **npm config**, none of the scripts in *package.json* would work.

Just run `npm config set ignore-scripts false` in the command line
