### ISSUE TITLE
e2e protractor failing

### ISSUE THREAD

**Issue by amp3rsand** [angular/angular-phonecat#189]
I have looked through other similar failures in the issues list - but nothing seems to work.

'npm run protractor' - 
Opens chrome browser window, but stays blank with 'data:,' in the address bar. 
c:\Users\david\angularJS\tutorials\angular-phonecat>npm run protractor

> angular-phonecat@0.0.0 preprotractor c:\Users\david\angularJS\tutorials\angula
r-phonecat
> npm run update-webdriver

-

> angular-phonecat@0.0.0 preupdate-webdriver c:\Users\david\angularJS\tutorials\
angular-phonecat
> npm install

npm WARN prefer global karma-cli@0.0.4 should be installed with -g

> angular-phonecat@0.0.0 postinstall c:\Users\david\angularJS\tutorials\angular-
phonecat
> bower install

/-

> angular-phonecat@0.0.0 update-webdriver c:\Users\david\angularJS\tutorials\ang
ular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.
-

> angular-phonecat@0.0.0 protractor c:\Users\david\angularJS\tutorials\angular-p
honecat
> protractor test/protractor-conf.js

Using ChromeDriver directly...
\

Then timesout and returns in CMD:
c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules\protractor\node
_modules\selenium-webdriver\lib\atoms\error.js:109
  var template = new Error(this.message);
                 ^
UnknownError: chrome not reachable
  (Driver info: chromedriver=2.10.267521,platform=Windows NT 6.3 x86_64)
    at new bot.Error (c:\Users\david\angularJS\tutorials\angular-phonecat\node_m
odules\protractor\node_modules\selenium-webdriver\lib\atoms\error.js:109:18)
    at Object.bot.response.checkResponse (c:\Users\david\angularJS\tutorials\ang
ular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\lib\atoms\
response.js:106:9)
    at c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules\protract
or\node_modules\selenium-webdriver\lib\webdriver\webdriver.js:134:24
    at c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules\protract
or\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
    at webdriver.promise.ControlFlow.runInNewFrame_ (c:\Users\david\angularJS\tu
torials\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver
\lib\webdriver\promise.js:1539:20)
    at notify (c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules\
protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:362:12)
    at notifyAll (c:\Users\david\angularJS\tutorials\angular-phonecat\node_modul
es\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:331:7)
    at resolve (c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules
\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:309:7)
    at fulfill (c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules
\protractor\node_modules\selenium-webdriver\lib\webdriver\promise.js:429:5)
    at c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules\protract
or\node_modules\selenium-webdriver\lib\goog\base.js:1243:15
==== async task ====
WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (c:\Users\david\angularJS\tu
torials\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver
\lib\webdriver\webdriver.js:131:49)
    at Function.webdriver.WebDriver.createSession (c:\Users\david\angularJS\tuto
rials\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\l
ib\webdriver\webdriver.js:111:30)
    at Object.createDriver (c:\Users\david\angularJS\tutorials\angular-phonecat\
node_modules\protractor\node_modules\selenium-webdriver\chrome.js:460:30)
    at ChromeDriverProvider.getDriver (c:\Users\david\angularJS\tutorials\angula
r-phonecat\node_modules\protractor\lib\driverProviders\chrome.js:67:27)
    at c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules\protract
or\lib\runner.js:217:35
    at _fulfilled (c:\Users\david\angularJS\tutorials\angular-phonecat\node_modu
les\protractor\node_modules\q\q.js:797:54)
    at self.promiseDispatch.done (c:\Users\david\angularJS\tutorials\angular-pho
necat\node_modules\protractor\node_modules\q\q.js:826:30)
    at Promise.promise.promiseDispatch (c:\Users\david\angularJS\tutorials\angul
ar-phonecat\node_modules\protractor\node_modules\q\q.js:759:13)
    at c:\Users\david\angularJS\tutorials\angular-phonecat\node_modules\protract
or\node_modules\q\q.js:525:49
|
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`

npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! cwd c:\Users\david\angularJS\tutorials\angular-phonecat
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\david\angularJS\tutorials\angular-phonecat\npm-debug.log
npm ERR! not ok code 0

c:\Users\david\angularJS\tutorials\angular-phonecat>

I have tried installing globally and running directly - but get the same issue?

**Comment by cloidjgreen** [comment]
So the server is already downloaded and running as the server for the phoneCat App.  Can you be more explicit here.  What did you do differently.
What does the phrase 
"I used https://www.npmjs.org/package/http-server in the root of the project directory "
translate to that I can follow?

**Comment by petebacondarwin** [comment]
@cloidjgreen, try this:

```bash
npm install -g http-server
cd your/phonecat/project
http-server -p 8000
```
