### ISSUE TITLE
Cannot install angular-route via bower for Lesson 7

### ISSUE THREAD

**Issue by zasipin** [angular/angular-phonecat#195]
Lesson 7 
When I run "bower install", it finishes with error "ECONFLICT Unable to find suitable version for angular"
It is looking for version of angular-route for angular 1.2.21 and 1.2.20.

When I commented in bower.json line "angular-route": "~1.2.x"
and downloaded bower-angular-route from github and added it into folder "bower_componetns", lesson 7 started to work fine.

**Comment by nandavanan** [comment]
I would suggest trying 'bower update'. This updates all the packages and installs the new ones in ones step.

To get this to work, you need bower to be installed globally, to do so, try 'npm install -g bower'
