### ISSUE TITLE
Angular framework is not downloaded when running `npm install` - this conflicts with instructions in tutorial

### ISSUE THREAD

**Issue by ng-gupta** [angular/angular-phonecat#210]
npm install is not automatically using bower to download the Angular framework into the app/bower_components directory as mentioned in the tutorial at https://docs.angularjs.org/tutorial/

**Comment by setlord** [comment]
I've found an **angular-route** folder inside app/bower_components so there's no need to modify bower.json to get it. I guess the addition of angular-route line into bower.json raises the error since there are two directives in conflict.

**Comment by andrewzen** [comment]
I got the same "npm WARN cannot run in wd..." error in Terminal when running "npm install".

I got Angular into app/bower_components, by [fixing my npm permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) (using Option 1), and then running "npm install" again in the /angular-phonecat directory.

**Comment by dkoleary88** [comment]
I fixed this by changing the ownership of `/usr/local` and `~/Users/user-name` like so:

`sudo chown -R my_name /usr/local`

This allowed me to do everything without `sudo`

**Comment by caizhongxian** [comment]
`cd angular-phonecat/`
`sudo bower install angular --allow-root`

Thanks for you help^v^
