### ISSUE TITLE
npm start script should be 'http-server app -a 0.0.0.0 -p 8000'

### ISSUE THREAD

**Issue by ryanking8215** [angular/angular-phonecat#211]
use `npm start` to start the http server. Browser shows the files list instead of the correct web content.

Without path, http-server will use the current directory. But there is no index.html in it.  `app` directory should be the working path.

So we should modified the script in `package.json` 
from
```shell
http-server -a 0.0.0.0 -p 8000
```
to
```shell
http-server app -a 0.0.0.0 -p 8000
```

**Comment by petebacondarwin** [comment]
@ryanking8215 - it is the URL you navigate to that you must change not the server. See https://docs.angularjs.org/tutorial/#running-development-web-server
