### ISSUE TITLE
Component-based version of Angular PhoneCat App

### ISSUE THREAD

**Issue by demisx** [angular/angular-phonecat#218]
Hi. I've rewritten this tutorial app leveraging component-based organization based on the Google publicly recommended guidelines, Jonn Papa's LIFT principle and our experience developing enterprise software. Most of the directory structure is shown here: https://github.com/demisx/angular-phonecat-components. 

I think it would be very beneficial to show new AngularJS developers that there is an alternative way to organize your application then the traditional type-based approach shown in the original tutorial app. Especially, taking into consideration the Angular 2.0 philosophy. The current problem we see that people learning Angular start with the type-based approach in the tutorials and then they apply the same approach to writing production apps, then the code becomes very hard to maintain.

Please let me know if the component-based version can be mentioned in the main README file and I'll put together a PR. Thank you.

**Comment by gkalpak** [comment]
Finally, the latest version of the tutorial uses components and a better architecture/code organization closer to modern practices and @johnpapa's styleguide. :tada:
