### ISSUE TITLE
Ubuntu 14.10, can not load "chromium-browser", it is not registered! 

### ISSUE THREAD

**Issue by kenpeter** [angular/angular-phonecat#222]
I am in step-03 of the tutorial. I try to run "npm test" with chromium-browser on Ubuntu, but I get "can not load "chromium-browser", it is not registered!". Based on this https://github.com/karma-runner/karma-firefox-launcher, if I set the browser name as "Firefox" (notice the capitialized F) in karma.conf.js and it is working. I tried different names like "Chromium-browser" and "Chromium_browser". Unfortunately, it is still not working for me.

**Comment by gkalpak** [comment]
Closing as this is not directly related to the tutorial. If anyone is still facing problems, [this SO answer][1] seems promising.

[1]: http://stackoverflow.com/questions/19671999/how-to-get-karma-to-work-with-chrome
