### ISSUE TITLE
E2E warning in step-6 and step-7

### ISSUE THREAD

**Issue by sszigeti** [angular/angular-phonecat#223]
After checking out step-6 `npm run protractor` completes without failures, but it also gives a warning: _more than one element found for locator By.cssSelector(".phones li a") - you may need to be more specific_

Interestingly, the [tutorial](https://docs.angularjs.org/tutorial/step_06#test) claims that in **test/e2e/scenarios.js** we should have this:

    element.all(by.css('.phones li a')).first().click();

However, in scenarios.js the `.first()` method call is not present, hence the warning. Actually, that method isn't even defined there, according to Protractor, which chokes on the tutorial's version (which  simply calls the `element` method instead of `element.all`).

A simple way to fix the warning would be something like the following:

    element(by.css('.phones li a:first-of-type')).click();

or

    element.all(by.css('.phones li a')).first().click();

This is my first time to submit an issue on GitHub, and I'm unsure how to proceed. Please let me know if I'm expected to do anything else besides reporting it.

**Comment by sszigeti** [comment]
Impacts step-6 and step-7. Step-8 seems to be okay in this regard.

**Comment by rafi** [comment]
Using protractor 1.4.0, I also had to change the url expected from `browser.getLocationAbsUrl()` for the test to pass:
```javascript
    it('should render phone specific links', function() {
      var query = element(by.model('query'));
      query.sendKeys('nexus');
      element.all(by.css('.phones li a')).first().click();
      browser.getLocationAbsUrl().then(function(url) {
        expect(url).toBe('/phones/nexus-s');
      });
    });
```

**Comment by petebacondarwin** [comment]
This seems to be fixed.
