### ISSUE TITLE
step-6 uses an href rather than a ng-href

### ISSUE THREAD

**Issue by EthanLozano** [angular/angular-phonecat#226]
[step-6](https://github.com/angular/angular-phonecat/blob/step-6/app/index.html) uses a dynamically generated link with the href attribute rather than the [ng-href](https://docs.angularjs.org/api/ng/directive/ngHref) attribute.

**Comment by EthanLozano** [comment]
The [docs tutorial](https://github.com/angular/angular.js/blob/master/docs/content/tutorial/step_06.ngdoc) needs to be fixed after this is fixed. So, I created an [issue](https://github.com/angular/angular.js/issues/10828) for that repo.

**Comment by petebacondarwin** [comment]
This is not really necessary as it is unlikely that the user will click on a link before Angular has had time to fill it correctly.
