### ISSUE TITLE
error with npm install    win 7 

### ISSUE THREAD

**Issue by abhirupM** [angular/angular-phonecat#227]
I created npm folder [ D:\Users\avm\AppData\Roaming\npm ]  which was missing initially.
Now I am having following error:
----npm-debug log ------
0 info it worked if it ends with ok
1 verbose cli [ 'd:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'd:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose readDependencies using package.json deps
5 verbose install where, deps [ 'f:\\angular\\angular-phonecat',
5 verbose install   [ 'karma',
5 verbose install     'karma-chrome-launcher',
5 verbose install     'karma-jasmine',
5 verbose install     'protractor',
5 verbose install     'http-server',
5 verbose install     'tmp',
5 verbose install     'bower',
5 verbose install     'shelljs' ] ]
6 info preinstall angular-phonecat@0.0.0
7 warn package.json karma-chrome-launcher@0.1.7 No README data
8 verbose readDependencies using package.json deps
9 verbose already installed skipping karma@^0.12.16 f:\angular\angular-phonecat
10 verbose already installed skipping karma-chrome-launcher@^0.1.4 f:\angular\angular-phonecat
11 verbose already installed skipping karma-jasmine@^0.1.5 f:\angular\angular-phonecat
12 verbose already installed skipping protractor@~1.0.0 f:\angular\angular-phonecat
13 verbose already installed skipping http-server@^0.6.1 f:\angular\angular-phonecat
14 verbose already installed skipping tmp@0.0.23 f:\angular\angular-phonecat
15 verbose already installed skipping bower@^1.3.1 f:\angular\angular-phonecat
16 verbose already installed skipping shelljs@^0.2.6 f:\angular\angular-phonecat
17 silly resolved []
18 info build f:\angular\angular-phonecat
19 verbose linkStuff [ false, false, false, 'f:\\angular' ]
20 info linkStuff angular-phonecat@0.0.0
21 verbose linkBins angular-phonecat@0.0.0
22 verbose linkMans angular-phonecat@0.0.0
23 verbose rebuildBundles angular-phonecat@0.0.0
24 verbose rebuildBundles [ '.bin',
24 verbose rebuildBundles   'bower',
24 verbose rebuildBundles   'http-server',
24 verbose rebuildBundles   'karma',
24 verbose rebuildBundles   'karma-chrome-launcher',
24 verbose rebuildBundles   'karma-jasmine',
24 verbose rebuildBundles   'protractor',
24 verbose rebuildBundles   'shelljs',
24 verbose rebuildBundles   'tmp' ]
25 info install angular-phonecat@0.0.0
26 info postinstall angular-phonecat@0.0.0
27 verbose unsafe-perm in lifecycle true
28 info angular-phonecat@0.0.0 Failed to exec postinstall script
29 error angular-phonecat@0.0.0 postinstall: `bower install`
29 error Exit status 1
30 error Failed at the angular-phonecat@0.0.0 postinstall script.
30 error This is most likely a problem with the angular-phonecat package,
30 error not with npm itself.
30 error Tell the author that this fails on your system:
30 error     bower install
30 error You can get their info via:
30 error     npm owner ls angular-phonecat
30 error There is likely additional logging output above.
31 error System Windows_NT 6.1.7601
32 error command "d:\\Program Files\\nodejs\\node.exe" "d:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
33 error cwd f:\angular\angular-phonecat
34 error node -v v0.10.36
35 error npm -v 1.4.28
36 error code ELIFECYCLE
37 verbose exit [ 1, true ]

**Comment by Dapsang** [comment]
This seems to be the same error I have. It boils down to bower install not working. Although I am in MACOSX

**Comment by adoliver** [comment]
I am also having a problem with bower not installing. The npm install command hangs for 20min.
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\WINDOWS\system32>cd c:\Users\allenoliver\AngularTutorial\angular-phonecat

c:\Users\allenoliver\AngularTutorial\angular-phonecat>npm install
npm WARN optional dep failed, continuing fsevents@0.3.5
|


> ws@0.4.32 install c:\Users\allenoliver\AngularTutorial\angular-phonecat\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


c:\Users\allenoliver\AngularTutorial\angular-phonecat\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
/

After I kill npm and try again I get this error:
c:\Users\allenoliver\AngularTutorial\angular-phonecat>npm install

> angular-phonecat@0.0.0 postinstall c:\Users\allenoliver\AngularTutorial\angular-phonecat
> bower install

'bower' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\allenoliver\AngularTutorial\angular-phonecat
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     c:\Users\allenoliver\AngularTutorial\angular-phonecat\npm-debug.log
npm ERR! not ok code 0

c:\Users\allenoliver\AngularTutorial\angular-phonecat>

**Comment by adoliver** [comment]
This seems to be related to #163
I was able to solve my problem by installing bower and karma globally
npm install -g bower
npm install -g karma
Then I could run npm install within the angular-phonecat directory successfully.

I also needed to make sure that I ran the npm install within a command prompt which had the git executable in the PATH. I had installed git to only run in git bash and then I was attempting to use the normal windows command prompt to run npm install which did not work because git was not in the path.

**Comment by kenshinji** [comment]
yeah, it works! thanks @adoliver

**Comment by harjolgoo** [comment]
still not working for me...

**Comment by gkalpak** [comment]
All dependencies and tools have been updated recently and this is hopefully not an issue any more.
If anyone is still having problems, please open a new issue.

Also, take a look [here][1] for a list of common issues and ways to solve them.

[1]: https://docs.angularjs.org/tutorial#common-issues
