### ISSUE TITLE
step-6: Error: Expected undefined to be '/phones/nexus-s'

### ISSUE THREAD

**Issue by yaojingguo** [angular/angular-phonecat#229]
In step-6, when running `npm run protractor`, there is the following error:

```
Failures:

  1) PhoneCat App Phone list view should render phone specific links
   Message:
     Expected undefined to be '/phones/nexus-s'.
   Stacktrace:
     Error: Expected undefined to be '/phones/nexus-s'.
    at /home/jing/code/tutoral/angular-phonecat/test/e2e/scenarios.js:63:35
```

The fix is to change `expect(url.split('#')[1]).toBe('/phones/nexus-s');` to ` expect(url).toBe('/phones/nexus-s');`.

Angular version is 1.3.10. I am using a Ubuntu 14.04 box.

**Comment by yaojingguo** [comment]
Step-7 has similar problems.

**Comment by yaojingguo** [comment]
Upgrading AngularJS to 1.3.11 solves this problem.

**Comment by m31uk3** [comment]
still a problem with 1.3.15

{code}
bower list
bower check-new     Checking for new versions of the project dependencies..
angular-phonecat#0.0.0 /git.repo/angular-phonecat
├── angular#1.3.15 (1.3.16-build.108+sha.fee437f available, latest is 1.4.0-rc.1)
├─┬ angular-animate#1.3.15 extraneous (1.3.16-build.108+sha.fee437f available, latest is 1.4.0-rc.1)
│ └── angular#1.3.15 (latest is 1.4.0-rc.1)
├─┬ angular-mocks#1.3.15 (1.3.16-build.108+sha.fee437f available, latest is 1.4.0-rc.1)
│ └── angular#1.3.15
├─┬ angular-resource#1.3.15 extraneous (1.3.16-build.108+sha.fee437f available, latest is 1.4.0-rc.1)
│ └── angular#1.3.15
├─┬ angular-route#1.3.15 extraneous (1.3.16-build.108+sha.fee437f available, latest is 1.4.0-rc.1)
│ └── angular#1.3.15
├─┬ bootstrap#3.1.1 (latest is 3.3.4)
│ └── jquery#2.1.4
└── jquery#2.1.4
{code}

{code}
/git.repo/angular-phonecat> ./node_modules/.bin/protractor test/protractor-conf.js
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://192.168.0.3:57817/wd/hub
..WARNING - more than one element found for locator By.cssSelector(".phones li a") - the first result will be used
F

Failures:

  1) PhoneCat App Phone list view should render phone specific links
   Message:
     Expected undefined to be '/phones/nexus-s'.
   Stacktrace:
     Error: Expected undefined to be '/phones/nexus-s'.
    at /git.repo/angular-phonecat/test/e2e/scenarios.js:62:35
    at Array.forEach (native)

Finished in 2.673 seconds
3 tests, 6 assertions, 1 failure

Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1
{code}

**Comment by m31uk3** [comment]
removed working directory and rechecked out with:

git clone --depth=14 https://github.com/angular/angular-phonecat.git

somehow everything works now for step 6 and 7

I notice that if you leave karma running during: i.e. git checkout -f step-7 it will fail

However if you kill it an rerun everything tests successful.

**Comment by brian-villanueva** [comment]
Still having this problem with 1.3.16

**Comment by rockallite** [comment]
Me too. I'm using AngularJS 1.3.16, need ```expect(url).toBe('/phones/nexus-s');``` fix to pass step-6 e2e test.

**Comment by Flynsarmy** [comment]
I also needed to change it to `expect(url)` to make it work.

**Comment by ygamretuta** [comment]
confirming aforementioned: change it to `expect(url)` works for me too
