### ISSUE TITLE
Problem With Bower.

### ISSUE THREAD

**Issue by metwally** [angular/angular-phonecat#234]
It seems that there is a problem with Bower and git!
this is my first encounter with Bower and it seems it will be the last!
I just want to learn **AngularJs**, but I found myself spend sometimes troubleshooting Bower to just download some libraries!
**IT will be better if you have a complete version of this app,** like old days, when every web app was have everything included in its folders :)

I will stop troubleshooting this problem, but here is the error message. 

> bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://github.com/angular/bower-angular-route.git", exit code of #128
> Additional error details:
> fatal: write error: Invalid argument

p.s. I've tried to reconfigure git to use git insteadOf https and it start to give me another errors.

**Comment by gkalpak** [comment]
Closing as the issue/error is not directly related to the tutorial and we are unlikely to move away from bower ta this point. Hopefully, the eminent update to newer versions of our tools will help in solve any problems.
