### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by dlaub123** [angular/angular-phonecat#235]
I have no problem cloning the repo, but when I run npm install, I get this error:

C:\Users\laubd\angular-phonecat>npm install
npm WARN package.json karma-chrome-launcher@0.1.7 No README data

> angular-phonecat@0.0.0 postinstall C:\Users\laubd\angular-phonecat
> bower install

bower not-cached    git://github.com/twbs/bootstrap.git#~3.1.1
bower resolve       git://github.com/twbs/bootstrap.git#~3.1.1
bower not-cached    git://github.com/angular/bower-angular-resource.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-resource.git#1.3.x
bower not-cached    git://github.com/angular/bower-angular-animate.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-animate.git#1.3.x
bower not-cached    git://github.com/jquery/jquery.git#~2.1.1
bower resolve       git://github.com/jquery/jquery.git#~2.1.1
bower not-cached    git://github.com/angular/bower-angular.git#1.3.x
bower resolve       git://github.com/angular/bower-angular.git#1.3.x
bower not-cached    git://github.com/angular/bower-angular-route.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-route.git#1.3.x
bower not-cached    git://github.com/angular/bower-angular-mocks.git#1.3.x
bower resolve       git://github.com/angular/bower-angular-mocks.git#1.3.x
bower ECMDERR       Failed to execute "git ls-remote --tags --heads git://githu
.com/angular/bower-angular-mocks.git", exit code of #128

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.128]: errno=No error

npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat

**Comment by dlaub123** [comment]
I'm 99% convinced this is a firewall issue where I work - because the install works fine for me at home...I think it boils down to git:// vs. http://

**Comment by pkozlowski-opensource** [comment]
@dlaub123 this is what I was [trying to tell you yesterday....](https://github.com/angular/angular.js/issues/11151#issuecomment-75605925)

**Comment by xie-qianyue** [comment]
I have this problem too. As like decribed in #163, running the command `git config --global url."https://".insteadOf git://` works for me.

**Comment by dlaub123** [comment]
Thanks - this is Really very helpful!  The root cause still being work
environments firewall out too much useful stuff

**Comment by samiralajmovic** [comment]
@xie-qianyue worked beautifully.

**Comment by ainsofsoo** [comment]
thanx @xie-qianyue . your solutions worked for me on windows 7 64 bit running npm

**Comment by rubinchyk** [comment]
It's working for me also. I checked on 4 hosts.

**Comment by Qurbonov** [comment]
@xie-qianyue  THANK YOU :+1:

**Comment by xie-qianyue** [comment]
@dlaub123 It's the firewall blocking `git` protocol, and the configuration `git config --global url."https://".insteadOf git://` works for manay people. Maybe this issue should be closed now?

**Comment by dudedev** [comment]
Thanks ! It worked for me too.

**Comment by buddalasunil999** [comment]
Thanks git config --global url."https://".insteadOf git:// worked for me

**Comment by fidelisfelipe** [comment]
Thanks ! it worked for me too.

**Comment by gkalpak** [comment]
Thx @xie-qianyue :+1:

**Comment by sheridanandrew13** [comment]
This problem has plagued me for a week, thanks @xie-qianyue for the fix.

**Comment by sid226** [comment]
worked for me thanks :)

**Comment by iruasev** [comment]
+1 Many thanks! ;)

**Comment by RidhoIdris** [comment]
thanks work for me
