### ISSUE TITLE
Failed to instantiate module ngPDFViewer due to: [$injector:nomod] Module 'ngPDFViewer' is not available! 

### ISSUE THREAD

**Issue by Dhanayan123** [angular/angular-phonecat#236]
Dear all, 
I am trying to use ngpdfviwer in my application. but i hvae the following, please help me thanks in advance. 
[$injector:modulerr] Failed to instantiate module ngPDFViewer due to:
[$injector:nomod] Module 'ngPDFViewer' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.22/$injector/nomod?p0=ngPDFViewer

**Comment by pkozlowski-opensource** [comment]
@Dhanayan123 support questions like this one should be asked using one of the dedicated [support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
