### ISSUE TITLE
Problme test tutorial step 2 

### ISSUE THREAD

**Issue by alanMediacy** [angular/angular-phonecat#237]
Hello i'm following the tutorial of Angular
In step 2: https://docs.angularjs.org/tutorial/step_02

When i try to run karma with:
<code>start karma.conf.js</code>
give me:
<code>
Phonecat controllers PhoneListCytl encountered a declaratgion exception FAILED
ReferenceError: module is not defined at Suite.<anonymous> (c:/Users/alan/Develep/Programs/nodejs/node_module/js/tests/controllerSpec.js:8:16)
at Suite.<anonymous>(c:/Users/alan/Develep/Programs/nodejs/node_module/js/tests/controllerSpec.js:6:3)
at c:/Users/alan/Develep/Programs/nodejs/node_module/js/tests/controllerSpec.js:4:1
 </code>

I understand is a stupid error but i'm newbie of angular and js
Thank you so much.
The code is exactly like this:
https://github.com/angular/angular-phonecat/compare/step-1...step-2

Alan

**Comment by petebacondarwin** [comment]
It sounds like you have not included `angular-mocks.js` in your karma configuration.

**Comment by alanMediacy** [comment]
Thanks i already resolve it  restart from the begin
