### ISSUE TITLE
npm run protractor fail on step-6

### ISSUE THREAD

**Issue by 274793580** [angular/angular-phonecat#241]
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\ng\\nodejs\\\\node.exe',
1 verbose cli   'D:\\ng\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink D:\ng\nodejs\\node.exe
5 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
6 info preprotractor angular-phonecat@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info protractor angular-phonecat@0.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-phonecat@0.0.0 Failed to exec protractor script
11 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
11 error Exit status 1
12 error Failed at the angular-phonecat@0.0.0 protractor script.
12 error This is most likely a problem with the angular-phonecat package,
12 error not with npm itself.
12 error Tell the author that this fails on your system:
12 error     protractor test/protractor-conf.js
12 error You can get their info via:
12 error     npm owner ls angular-phonecat
12 error There is likely additional logging output above.
13 error System Windows_NT 6.1.7601
14 error command "D:\\ng\\nodejs\\\\node.exe" "D:\\ng\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
15 error cwd C:\Users\xxb03\angular-phonecat
16 error node -v v0.10.28
17 error npm -v 1.4.9
18 error code ELIFECYCLE
19 verbose exit [ 1, true ]

**Comment by dmitriz** [comment]
The e2e Test in Step 6 fails for two reasons:

- `element(by.css('.phones li a')).click()` clicks the 1st of the two matched element, which is the wrong one;
- `getLocationAbsUrl()` returns the relative path, not the absolute one (see https://github.com/angular/protractor/issues/1436).

Here is the amendment that makes the test pass:

    it('should render phone specific links', function() {
      var query = element(by.model('query'));
      query.sendKeys('nexus');

      //element(by.css('.phones li a')).click();
      var nameLink = element(by.binding('phone.name'));
      expect(nameLink.getText()).toEqual("Nexus S");

      element(by.binding('phone.name')).click();

      var getUrl = browser.getLocationAbsUrl();

	    expect(browser.getLocationAbsUrl()).toBe('/phones/nexus-s');

      // browser.getLocationAbsUrl().then(function(url) {
      //   expect(url.split('#')[1]).toBe('/phones/nexus-s');
      // });
    });

**Comment by mcmoe** [comment]
If you want to get the previous behavior of actually retrieving the full URL, [browser.getCurrentUrl()](http://angular.github.io/protractor/#/api?view=webdriver.WebDriver.prototype.getCurrentUrl) worked for me.

```javascript
browser.getCurrentUrl().then(function(url) {
   expect(url.split('#')[1]).toBe('/phones');
});
```
and

```javascript
browser.getCurrentUrl().then(function(url) {
   expect(url.split('#')[1]).toBe('/phones/nexus-s');
});
```

**Comment by petebacondarwin** [comment]
These have now been fixed
