### ISSUE TITLE
Level 5 CORS issue in Chrome

### ISSUE THREAD

**Issue by DaveLindberg** [angular/angular-phonecat#242]
Flummoxed. 

The Level 5 code works in Safari and other browsers, but I've run into a CORS issue with Chrome that I can't get around. End to end and unit tests pass, but the JSON data will not display. 

````XMLHttpRequest cannot load file://localhost/Applications/MAMP/htdocs/angular-phonecat/app/phones/phones.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.````

I understand this is not an Angular issue per se, but hope I might find a workable solution here to complete the tutorial.

**Comment by pkozlowski-opensource** [comment]
@DaveLindberg you should be running an app from a web server as [described](https://github.com/angular/angular-phonecat#running-the-app-during-development) instead off the file system.

**Comment by DaveLindberg** [comment]
Oh. Right. Thank you, that's exactly what I was missing. 
:-)
