### ISSUE TITLE
setup issues - npm install  errors  - help!

### ISSUE THREAD

**Issue by marklovett** [angular/angular-phonecat#245]
I believe I may have fixed the issue by running:
sudo chown -R marklovett .npm/

Please help me get setup for the tutorial.  I tried installing the software according to the tutorial instructions but cant get it working. I also read several other solutions but no luck yet.

MOST RECENT ATTEMPT:

Last login: Sat Apr  4 19:11:37 on ttys000
You have new mail.
marks-mbp:~ marklovett$ cd angular-tuts
-bash: cd: angular-tuts: No such file or directory
marks-mbp:~ marklovett$ git clone --depth=14 https://github.com/angular/angular-phonecat.git
Cloning into 'angular-phonecat'...
remote: Counting objects: 294, done.
remote: Compressing objects: 100% (221/221), done.
remote: Total 294 (delta 66), reused 279 (delta 64), pack-reused 0
Receiving objects: 100% (294/294), 1.47 MiB | 0 bytes/s, done.
Resolving deltas: 100% (66/66), done.
Checking connectivity... done.
marks-mbp:~ marklovett$ cd angular-phonecat/
marks-mbp:angular-phonecat marklovett$ node --version
v0.12.2
marks-mbp:angular-phonecat marklovett$ npm install
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/bower-b7b873f4ac91562d.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/bower-b7b873f4ac91562d.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/bower-b7b873f4ac91562d.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/bower-b7b873f4ac91562d.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/bower, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/tmp-e43d240891eed1e9.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/tmp-e43d240891eed1e9.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/tmp-e43d240891eed1e9.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/tmp-e43d240891eed1e9.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/tmp, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/karma-chrome-launcher-40cba6f338207cb5.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/karma-chrome-launcher-40cba6f338207cb5.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/karma-chrome-launcher-40cba6f338207cb5.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/karma-chrome-launcher-40cba6f338207cb5.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/karma-chrome-launcher, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/karma-jasmine-c28aa84bd84b44a0.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/karma-jasmine-c28aa84bd84b44a0.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/karma-jasmine-c28aa84bd84b44a0.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/karma-jasmine-c28aa84bd84b44a0.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/karma-jasmine, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/shelljs-1c73fcfbe5ff642d.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/shelljs-1c73fcfbe5ff642d.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/shelljs-1c73fcfbe5ff642d.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/shelljs-1c73fcfbe5ff642d.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/shelljs, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/protractor-46de233e8de6f71e.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/protractor-46de233e8de6f71e.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/protractor-46de233e8de6f71e.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/protractor-46de233e8de6f71e.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/protractor, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/karma-51be8c80ed42f5f2.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/karma-51be8c80ed42f5f2.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/karma-51be8c80ed42f5f2.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/karma-51be8c80ed42f5f2.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/karma, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/http-server-b3c60f7f9cdd7cd6.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/http-server-b3c60f7f9cdd7cd6.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/http-server-b3c60f7f9cdd7cd6.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/http-server-b3c60f7f9cdd7cd6.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /Users/marklovett/angular-phonecat/node_modules/http-server, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marklovett/angular-phonecat/npm-debug.log
marks-mbp:angular-phonecat marklovett$ sudo npm install
Password:
npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.7.5"})
 
> fsevents@0.3.5 install /Users/marklovett/angular-phonecat/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  SOLINK_MODULE(target) Release/fse.node: Finished

> ws@0.4.32 install /Users/marklovett/angular-phonecat/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN cannot run in wd angular-phonecat@0.0.0 bower install (wd=/Users/marklovett/angular-phonecat)
karma-chrome-launcher@0.1.7 node_modules/karma-chrome-launcher

tmp@0.0.23 node_modules/tmp

karma-jasmine@0.1.5 node_modules/karma-jasmine

shelljs@0.2.6 node_modules/shelljs

http-server@0.6.1 node_modules/http-server
├── opener@1.3.0
├── colors@0.6.2
├── portfinder@0.2.1 (mkdirp@0.0.7)
├── optimist@0.5.2 (wordwrap@0.0.2)
├── ecstatic@0.4.13 (ent@0.0.7, mime@1.2.11, optimist@0.3.7)
└── union@0.3.8 (pkginfo@0.2.3, qs@0.5.6)

bower@1.4.1 node_modules/bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── user-home@1.1.1
├── which@1.0.9
├── abbrev@1.0.5
├── chmodr@0.1.0
├── rimraf@2.3.2
├── archy@1.0.0
├── opn@1.0.1
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.6
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.1
├── tmp@0.0.24
├── q@1.2.0
├── request-progress@0.3.1 (throttleit@0.0.2)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── semver@2.3.2
├── p-throttler@0.1.1 (q@0.9.7)
├── fstream@1.0.4 (inherits@2.0.1)
├── promptly@0.2.0 (read@1.0.5)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── tar-fs@1.5.0 (pump@1.0.0, tar-stream@1.1.2)
├── glob@4.5.3 (inherits@2.0.1, inflight@1.0.4, once@1.3.1, minimatch@2.0.4)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.4)
├── insight@0.5.3 (object-assign@2.0.0, lodash.debounce@3.0.3, async@0.9.0, os-name@1.0.3, tough-cookie@0.12.1)
├── update-notifier@0.3.1 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.0)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── github@0.2.3
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@2.3.1)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, osenv@0.1.0, uuid@2.0.1, js-yaml@3.2.7)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, cli-color@0.3.3, rx@2.4.10)

protractor@1.0.0 node_modules/protractor
├── jasminewd@1.0.4
├── saucelabs@0.1.1
├── q@1.0.0
├── minijasminenode@1.1.1
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── adm-zip@0.4.4
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map-support@0.2.10 (source-map@0.1.32)
├── request@2.36.0 (json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, qs@0.6.6, oauth-sign@0.3.0, tunnel-agent@0.4.0, mime@1.2.11, node-uuid@1.4.3, form-data@0.1.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@1.0.0)
├── lodash@2.4.1
└── selenium-webdriver@2.42.1

karma@0.12.31 node_modules/karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── rimraf@2.2.8
├── colors@0.6.2
├── mime@1.2.11
├── q@0.9.7
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map@0.1.43 (amdefine@0.1.0)
├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── lodash@2.4.1
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── connect@2.26.6 (fresh@0.2.4, cookie@0.1.2, pause@0.0.1, cookie-signature@1.0.5, response-time@2.0.1, vhost@3.0.0, basic-auth-connect@1.0.0, on-headers@1.0.0, media-typer@0.3.0, bytes@1.0.0, parseurl@1.3.0, depd@0.4.5, qs@2.2.4, cookie-parser@1.3.4, connect-timeout@1.3.0, debug@2.0.0, finalhandler@0.2.0, method-override@2.2.0, morgan@1.3.2, serve-favicon@2.1.7, type-is@1.5.7, csurf@1.6.6, multiparty@3.3.2, serve-static@1.6.5, express-session@1.8.2, errorhandler@1.2.4, compression@1.1.2, body-parser@1.8.4, serve-index@1.2.1)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── chokidar@0.12.6 (async-each@0.1.6, readdirp@1.3.0, fsevents@0.3.5)
└── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
marks-mbp:angular-phonecat marklovett$ 

OLD ATTEMPT BELOW:

When running npm install I get the following errors:

Error log below:

Last login: Sat Apr  4 16:46:34 on ttys000
You have new mail.
marks-mbp:~ marklovett$ cd angularjs-tuts/
marks-mbp:angularjs-tuts marklovett$ cd angular-phonecat/
marks-mbp:angular-phonecat marklovett$ npm install
npm WARN package.json karma-chrome-launcher@0.1.7 No README data

> angular-phonecat@0.0.0 postinstall /Users/marklovett/angularjs-tuts/angular-phonecat
> bower install

npm WARN unmet dependency /Users/marklovett/angularjs-tuts/angular-phonecat/node_modules/karma/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/regex-cache/node_modules/benchmarked/node_modules/file-reader/node_modules/map-files/node_modules/globby requires glob@'^4.0.2' but will load
npm WARN unmet dependency /Users/marklovett/angularjs-tuts/angular-phonecat/node_modules/karma/node_modules/glob,
npm WARN unmet dependency which is version 3.2.11
marks-mbp:angular-phonecat marklovett$ npm install -g npm@latest
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "npm@latest"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /Users/marklovett/.npm/npm/2.7.5
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/Users/marklovett/.npm/npm/2.7.5'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/Users/marklovett/.npm/npm/2.7.5']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/marklovett/.npm/npm/2.7.5' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marklovett/angularjs-tuts/angular-phonecat/npm-debug.log
marks-mbp:angular-phonecat marklovett$ npm install -g npm@latest
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "npm@latest"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! path /Users/marklovett/.npm/npm/2.7.5
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/Users/marklovett/.npm/npm/2.7.5'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/Users/marklovett/.npm/npm/2.7.5']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/marklovett/.npm/npm/2.7.5' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marklovett/angularjs-tuts/angular-phonecat/npm-debug.log
marks-mbp:angular-phonecat marklovett$ sudo npm install -g npm@latest
Password:
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm@2.7.5 /usr/local/lib/node_modules/npm
marks-mbp:angular-phonecat marklovett$ cd ~
marks-mbp:~ marklovett$ npm install -g bower
npm WARN locking Error: EACCES, open '/Users/marklovett/.npm/_locks/bower-e8debc5417026b57.lock'
npm WARN locking     at Error (native)
npm WARN locking  /Users/marklovett/.npm/_locks/bower-e8debc5417026b57.lock failed { [Error: EACCES, open '/Users/marklovett/.npm/_locks/bower-e8debc5417026b57.lock']
npm WARN locking   errno: -13,
npm WARN locking   code: 'EACCES',
npm WARN locking   path: '/Users/marklovett/.npm/_locks/bower-e8debc5417026b57.lock' }
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "bower"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5

npm ERR! Attempt to unlock /usr/local/lib/node_modules/bower, which hasn't been locked
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marklovett/npm-debug.log
marks-mbp:~ marklovett$ sudo npm install -g bower
Password:
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
bower@1.4.1 /usr/local/lib/node_modules/bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── user-home@1.1.1
├── abbrev@1.0.5
├── which@1.0.9
├── chmodr@0.1.0
├── rimraf@2.3.2
├── archy@1.0.0
├── opn@1.0.1
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.6
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.1
├── tmp@0.0.24
├── q@1.2.0
├── request-progress@0.3.1 (throttleit@0.0.2)
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── semver@2.3.2
├── fstream@1.0.4 (inherits@2.0.1)
├── p-throttler@0.1.1 (q@0.9.7)
├── promptly@0.2.0 (read@1.0.5)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── tar-fs@1.5.0 (pump@1.0.0, tar-stream@1.1.2)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.4)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.4)
├── insight@0.5.3 (object-assign@2.0.0, lodash.debounce@3.0.3, async@0.9.0, os-name@1.0.3, tough-cookie@0.12.1)
├── update-notifier@0.3.1 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.0)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── github@0.2.3
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, aws-sign2@0.5.0, forever-agent@0.5.2, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.3.3, combined-stream@0.0.7, form-data@0.2.0, mime-types@2.0.10, bl@0.9.4, http-signature@0.10.1, tough-cookie@0.12.1, hawk@2.3.1)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, osenv@0.1.0, uuid@2.0.1, js-yaml@3.2.7)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, cli-color@0.3.3, rx@2.4.10)
marks-mbp:~ marklovett$ ~/.cache/bower
-bash: /Users/marklovett/.cache/bower: is a directory
marks-mbp:~ marklovett$ npm cache clean
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "cache" "clean"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! path /Users/marklovett/.npm/Base64/0.2.1
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/Users/marklovett/.npm/Base64/0.2.1'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/Users/marklovett/.npm/Base64/0.2.1']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/marklovett/.npm/Base64/0.2.1' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marklovett/npm-debug.log
marks-mbp:~ marklovett$ sudo npm cache clean
marks-mbp:~ marklovett$ cd angularjs-tuts/
marks-mbp:angularjs-tuts marklovett$ cd angular-phonecat/
marks-mbp:angular-phonecat marklovett$ sudo npm install -g bower
/usr/local/bin/bower -> /usr/local/lib/node_modules/bower/bin/bower
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
bower@1.4.1 /usr/local/lib/node_modules/bower
├── is-root@1.0.0
├── junk@1.0.1
├── stringify-object@1.0.1
├── user-home@1.1.1
├── abbrev@1.0.5
├── which@1.0.9
├── chmodr@0.1.0
├── rimraf@2.3.2
├── archy@1.0.0
├── opn@1.0.1
├── bower-logger@0.2.2
├── lru-cache@2.5.0
├── bower-endpoint-parser@0.2.2
├── graceful-fs@3.0.6
├── lockfile@1.0.0
├── nopt@3.0.1
├── retry@0.6.1
├── tmp@0.0.24
├── q@1.2.0
├── request-progress@0.3.1 (throttleit@0.0.2)
├── semver@2.3.2
├── shell-quote@1.4.3 (array-filter@0.0.1, array-reduce@0.0.0, array-map@0.0.0, jsonify@0.0.0)
├── fstream@1.0.4 (inherits@2.0.1)
├── bower-json@0.4.0 (intersect@0.0.3, deep-extend@0.2.11, graceful-fs@2.0.3)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
├── p-throttler@0.1.1 (q@0.9.7)
├── promptly@0.2.0 (read@1.0.5)
├── mkdirp@0.5.0 (minimist@0.0.8)
├── tar-fs@1.5.0 (pump@1.0.0, tar-stream@1.1.2)
├── glob@4.5.3 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.4)
├── fstream-ignore@1.0.2 (inherits@2.0.1, minimatch@2.0.4)
├── insight@0.5.3 (object-assign@2.0.0, async@0.9.0, lodash.debounce@3.0.3, tough-cookie@0.12.1, os-name@1.0.3)
├── update-notifier@0.3.1 (is-npm@1.0.0, string-length@1.0.0, semver-diff@2.0.0, latest-version@1.0.0)
├── decompress-zip@0.1.0 (mkpath@0.1.0, touch@0.0.3, readable-stream@1.1.13, binary@0.3.0)
├── github@0.2.3
├── cardinal@0.4.4 (ansicolors@0.2.1, redeyed@0.4.4)
├── bower-registry-client@0.3.0 (graceful-fs@2.0.3, request-replay@0.2.0, rimraf@2.2.8, lru-cache@2.3.1, async@0.2.10, mkdirp@0.3.5, request@2.51.0)
├── request@2.53.0 (caseless@0.9.0, json-stringify-safe@5.0.0, forever-agent@0.5.2, aws-sign2@0.5.0, stringstream@0.0.4, oauth-sign@0.6.0, tunnel-agent@0.4.0, isstream@0.1.2, node-uuid@1.4.3, qs@2.3.3, form-data@0.2.0, combined-stream@0.0.7, bl@0.9.4, mime-types@2.0.10, http-signature@0.10.1, tough-cookie@0.12.1, hawk@2.3.1)
├── mout@0.11.0
├── bower-config@0.6.1 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.9.1)
├── configstore@0.3.2 (object-assign@2.0.0, xdg-basedir@1.0.1, osenv@0.1.0, uuid@2.0.1, js-yaml@3.2.7)
├── handlebars@2.0.0 (optimist@0.3.7, uglify-js@2.3.6)
└── inquirer@0.8.0 (figures@1.3.5, ansi-regex@1.1.1, mute-stream@0.0.4, through@2.3.6, readline2@0.1.1, chalk@0.5.1, lodash@2.4.1, cli-color@0.3.3, rx@2.4.10)
marks-mbp:angular-phonecat marklovett$ nano  /Users/marklovett/npm-debug.log

  GNU nano 2.0.6                                       File: /Users/marklovett/npm-debug.log

**Comment by gkalpak** [comment]
Closing as this issue is not directly related to the tutorial and it's pretty old anyway (so hopefully solved or solvable by installing latest versions of the tools).
