### ISSUE TITLE
npm run protractor` doesn't work on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by marklovett** [angular/angular-phonecat#246]
Seems to work intermittently.  At the very bottom of this page shows a recent successful run of protractor.

I tried this solution-  downloading  https://sites.google.com/a/chromium.org/chromedriver/downloads manualy and copy in  ... /node_modules/protractor/selenium/ directory

It worked one time,  then failed.  Help!
 

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marklovett/angular-phonecat/npm-debug.log
marks-mbp:angular-phonecat marklovett$ nano /Users/marklovett/angular-phonecat/npm-debug.log

Debug log below:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'protractor' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/pro$
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/n$
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/n$
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1$
11 verbose pkgid angular-phonecat@0.0.0

It seems to work intermittently. The last time I ran protractor it worked!
At end of lesson 4, this is what I got:

marks-mbp:angular-phonecat marklovett$ npm run protractor

> angular-phonecat@0.0.0 preprotractor /Users/marklovett/angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver /Users/marklovett/angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall /Users/marklovett/angular-phonecat
> bower install

> angular-phonecat@0.0.0 update-webdriver /Users/marklovett/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/marklovett/angular-phonecat
> protractor test/protractor-conf.js

util.puts: Use console.log instead
Using ChromeDriver directly...
..

Finished in 3.871 seconds
2 tests, 5 assertions, 0 failures

**Comment by gnzlbg** [comment]
I have the same problem

**Comment by vnctaing** [comment]
Same hereUpdating selenium standalone
downloading http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.2.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.10/chromedriver_mac32.zip...
chromedriver_2.10.zip downloaded to /Users/vnctaing/projects/angular-phonecat/node_modules/protractor/selenium/chromedriver_2.10.zip

/Users/vnctaing/projects/angular-phonecat/node_modules/protractor/node_modules/adm-zip/zipFile.js:66
            throw Utils.Errors.INVALID_FORMAT;
                              ^
Invalid or unsupported zip format. No END header found

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "update-webdriver"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 update-webdriver: `webdriver-manager update`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 update-webdriver script 'webdriver-manager update'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webdriver-manager update
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vnctaing/projects/angular-phonecat/npm-debug.log

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 preprotractor: `npm run update-webdriver`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 preprotractor script 'npm run update-webdriver'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run update-webdriver
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vnctaing/projects/angular-phonecat/npm-debug.log

**Comment by leocaseiro** [comment]
Same problem =/

**Comment by leocaseiro** [comment]
I've fixed installing Protactor globally:
    npm install -g protractor

**Comment by vnctaing** [comment]
I created [pyenv-virtualenv](https://github.com/yyuu/pyenv-virtualenv) set with a 2.7.8 python version and it did the trick. It seems that protractor doesn't work with python 3.x.x.

**Comment by billytd** [comment]
Installing protractor globally worked for me. Thanks @leocaseiro!

**Comment by heeeee10** [comment]
Anyone knows how to execute the command line: npm run protractor when I already typed: npm start.  Because when I typed npm start, I cannot type any command line anymore in the terminal

**Comment by leocaseiro** [comment]
Ctrl+C to stop any process in your terminal

**Comment by davidt22** [comment]
I have the same problem. Anyone has a tested solution that works ? Please, solve it.

**Comment by davidt22** [comment]
The solution is here for me: Mac OS Yosemite 10.10.5
https://github.com/angular/angular-phonecat/issues/230
Solution fixed running npm update-webdriver for me.
After I still had to remove chromeOnly: true and add directConnect: true in test/protractor-conf.js to succesfully run npm run protractor.

**Comment by craig-o-curtis** [comment]
@davidt22 

Wow! I've been working on getting the protractor working ALL weekend! That fixed it!
1. install protractor globally
`npm install -g protractor`

2. Got to the test/protractor-conf.js file, change to:
`  // chromeOnly: true,
  directConnect: true,`

3. Do the rest of the steps: 
`npm run update-webdriver`
`npm run protractor`

This fixed the following error: 
`angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.`
