### ISSUE TITLE
protractor fails invalid chromedriver

### ISSUE THREAD

**Issue by cloidjgreen** [angular/angular-phonecat#252]
c:\Users\cloidjgreen\WebstormProjects\angular-phonecat\node_modules\protractor\lib\driverProviders\local.js:42
        throw new Error('Could not find chromedriver at ' +
              ^
Error: Could not find chromedriver at c:\Users\cloidjgreen\WebstormProjects\angular-phonecat\node_modules\protractor\selenium
\chromedriver.exe

There is a chromedriver_2.10.zip downloaded but it will not open.  Seems to be corrupted

**Comment by DrBrown123** [comment]
I had this same issue on Macbook Air Yosemite 10.10.3 - I fixed it by first downloading and unzipping the chromedriver for mac32 from [the Chromedriver storage](http://chromedriver.storage.googleapis.com/index.html?path=2.15/) as `chromedriver` into `angular-phonecat/node_modules/protractor/selenium/`

I then removed the lines in package.json which were updating the chromedriver:
```
"preupdate-webdriver": "npm install",
"update-webdriver": "webdriver-manager update",
"preprotractor": "npm run update-webdriver",
```

 and ran `npm run protractor` and it worked.

**Comment by DanJFletcher** [comment]
Had same issue on my Windows 8 PC. I followed what marcerbil said only downloaded and unzipped the win_32 chromedriver. It worked, thanks so much!

**Comment by henry2man** [comment]
It doesn't work for me.. Windows 10 x64 final. I have tried 2.16 version (I have Chrome 44) but it doesn't work.

Any ideas?

**Comment by shindoujay** [comment]
@henry2man 
Thanks.
It works!.
