### ISSUE TITLE
npm run protractor ubuntu 15.04 64bit

### ISSUE THREAD

**Issue by MrOutput** [angular/angular-phonecat#254]
rafael@rcepeda:~/Playground/angular-phonecat$ npm run protractor

> angular-phonecat@0.0.0 preprotractor /home/rafael/Playground/angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver /home/rafael/Playground/angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall /home/rafael/Playground/angular-phonecat
> bower install

> angular-phonecat@0.0.0 update-webdriver /home/rafael/Playground/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /home/rafael/Playground/angular-phonecat
> protractor test/protractor-conf.js

util.puts: Use console.log instead
Using ChromeDriver directly...
[launcher] Error: Could not find chromedriver at /home/rafael/Playground/angular-phonecat/node_modules/protractor/selenium/chromedriver.exe

npm ERR! Linux 4.1.0-rc2
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rafael/Playground/angular-phonecat/npm-debug.log

## NPM DEBUG

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd /home/rafael/Playground/angular-phonecat
13 error Linux 4.1.0-rc2
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
15 error node v0.12.3
16 error npm  v2.9.1
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor test/protractor-conf.js
19 error You can get their info via:
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by Niceplace** [comment]
I have the same error, Ubunutu 14.04

npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "protractor"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

#180  NPM DEBUG 

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'protractor' ]
2 info using npm@2.10.1
3 info using node@v0.12.4
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
6 info preprotractor angular-phonecat@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info protractor angular-phonecat@0.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-phonecat@0.0.0 Failed to exec protractor script
11 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:110:17)
11 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
11 verbose stack     at ChildProcess.emit (events.js:110:17)
11 verbose stack     at maybeClose (child_process.js:1015:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
12 verbose pkgid angular-phonecat@0.0.0
13 verbose cwd /home/simon/Workspace/angular-tutorials/angular-phonecat
14 error Linux 3.13.0-44-generic
15 error argv "/usr/bin/node" "/usr/bin/npm" "run" "protractor"
16 error node v0.12.4
17 error npm  v2.10.1
18 error code ELIFECYCLE
19 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
19 error Exit status 1
20 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
20 error This is most likely a problem with the angular-phonecat package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     protractor test/protractor-conf.js
20 error You can get their info via:
20 error     npm owner ls angular-phonecat
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]

**Comment by prashantnag93** [comment]
Selenium is a Java application. I had the error above, which disappeared once I installed the latest JDK:

sudo apt-get install default-jdk
This is on 14.04 Trusty Tahr, YMMV. It is also not very obvious that you must be running the server in the background while protractor is running. I assumed it would start the server itself.

**Comment by ivyhaswell** [comment]
@ghost  it works for me, thank you for your help

**Comment by MrOutput** [comment]
install JDK as @ghost mentions
