### ISSUE TITLE
win7 npm install error

### ISSUE THREAD

**Issue by Garryzhang** [angular/angular-phonecat#255]
![image](https://cloud.githubusercontent.com/assets/9335536/7650169/6b1f398e-fb26-11e4-8e0e-a6b4605fc79c.png)

**Comment by boydwang** [comment]
+1

**Comment by ylzhang** [comment]
+1

**Comment by gkalpak** [comment]
This seems like a temporary issue with either the internet connection, github or the `bower-angular-mocks` repository. Feel free to reopen if the issue persists.
