### ISSUE TITLE
Approach you used with gi

### ISSUE THREAD

**Issue by justsayno** [angular/angular-phonecat#257]
Hi there

I love the way you guys have created the git branches to make changing each step easy and hassle free. I am trying to do this in a tutorial I am writing. I can get it going locally (in that I have 10 branches with all my different steps) but then how did you guys get this to work in cloning from the master in github and actually have all those branches?

I am quite new to git and don't understand how this has been done. I've done a lot of googling but cannot figure it out.

Any help or just a pointer in a direction would be great! I want to do all my tutorials like this from now on.

Regards,
Seth

**Comment by petebacondarwin** [comment]
They are actually tags and not branches. They should get pulled down when you clone.
