### ISSUE TITLE
Should we make a collection to list some 'npm install' issues and relevant solutions for users?

### ISSUE THREAD

**Issue by kenshinji** [angular/angular-phonecat#260]
Saying, the issue [#227](https://github.com/angular/angular-phonecat/issues/227) which I encountered and had been solved, I think we should update this kind of stuff into README.md.

**Comment by petebacondarwin** [comment]
+1!

**Comment by saadanerdetbare** [comment]
+1
An issue, wich may be temporary until more packages get updated, is that i have to hack the dependency tree to get a succesfull build. First i have to update package.json in angular-phonecat to the newest versions of packages from npm and install.
Then i have to find the ws package, update that, do `npm cache clear` and then `npm install` again

**Comment by gkalpak** [comment]
There is now a list of common issues [here][1]. Feel free to add more if you feel they are closely related to the tutorial or common enough to warrant a mention.

[1]: https://docs.angularjs.org/tutorial#common-issues
