### ISSUE TITLE
run protractor fails, Error: Timed out waiting for the WebDriver server

### ISSUE THREAD

**Issue by jackwhit3** [angular/angular-phonecat#276]
I'm running on a Mac OS X Yosemite v10.10.2.
Resembles #168 , tried with their solution running
 `./node_modules/.bin/protractor test/protractor-conf.js` still does not work.
Also relates to [this](https://github.com/angular/protractor/issues/656) issue, but the commit doesn't seem to solve.

> angular-phonecat@0.0.0 preprotractor /Users/lihsing/Workspace/angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver /Users/lihsing/Workspace/angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall /Users/lihsing/Workspace/angular-phonecat
> bower install

> angular-phonecat@0.0.0 update-webdriver /Users/lihsing/Workspace/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/lihsing/Workspace/angular-phonecat
> protractor test/protractor-conf.js

Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
/Users/lihsing/Workspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:39
  goog.global.setTimeout(function() { throw exception; }, 0);
                                            ^
Error: Timed out waiting for the WebDriver server at http://192.168.0.102:54508/wd/hub
    at Error (native)
    at onResponse (/Users/lihsing/Workspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:87:66)
    at /Users/lihsing/Workspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/http/util.js:42:21
    at /Users/lihsing/Workspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/http/http.js:123:5
    at ClientRequest.<anonymous> (/Users/lihsing/Workspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/http/index.js:145:7)
    at ClientRequest.emit (events.js:107:17)
    at Socket.socketErrorListener (_http_client.js:271:9)
    at Socket.emit (events.js:107:17)
    at net.js:459:14
    at process._tickCallback (node.js:355:11)

npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/lihsing/.nvm/versions/node/v0.12.7/bin/node" "/Users/lihsing/.nvm/versions/node/v0.12.7/bin/npm" "run" "protractor"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lihsing/Workspace/angular-phonecat/npm-debug.log

===================================================
npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/lihsing/.nvm/versions/node/v0.12.7/bin/node',
1 verbose cli   '/Users/lihsing/.nvm/versions/node/v0.12.7/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.11.3
3 info using node@v0.12.7
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/Users/lihsing/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/Users/lihsing/.nvm/versions/node/v0.12.7/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd /Users/lihsing/Workspace/angular-phonecat
13 error Darwin 14.1.0
14 error argv "/Users/lihsing/.nvm/versions/node/v0.12.7/bin/node" "/Users/lihsing/.nvm/versions/node/v0.12.7/bin/npm" "run" "protractor"
15 error node v0.12.7
16 error npm  v2.11.3
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor test/protractor-conf.js
19 error You can get their info via:
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by hellrider42** [comment]
Hi jackwhit3,
I had the same issue when using protractor. This seems to be caused by selenium-server-standalone-2.47.1.jar
I solved it for now by downloading selenium-server-standalone-2.46.0.jar to replace the problematic one. I then modified the requiered version number in config.json to prevent it from upgrading and then I ran protractor using ./node_modules/.bin/protractor test/protractor-conf.js

**Comment by jackwhit3** [comment]
Hi @hellrider42 , 
After updating Java, I followed @alecsandre 's solution at #230 and it worked for me.
I removed `chromeOnly: true` and added `directConnect: true` in `test/protractor-conf.js`.
By the way, I had selenium-webdriver@2.45.1 all the time.

**Comment by hellrider42** [comment]
I made it work with your solution indeed, thanks.

**Comment by santiagos11** [comment]
I can confirm that @jackwhit3 's solutions. However, I still want to make it work without using the direct connect option. What is causing this error?

**Comment by wojciechpe** [comment]
@alecsandre 's solution at #230 worked for me in Windows 10 64b

**Comment by srokatonie** [comment]
@jackwhit3 
> After updating Java, I followed @alecsandre 's solution at #230 and it worked for me.
I removed chromeOnly: true and added directConnect: true in test/protractor-conf.js.
The version of .jar file doesn't matter I think, I had older version and still worked after I changed.

Helped!

**Comment by Alberto-** [comment]
@jackwhit3 
---
I removed chromeOnly: true and added directConnect: true in test/protractor-conf.js.
---
It works! thanks

**Comment by jeongl** [comment]
OMG - after losing my night trying to get this stupid test to run, @jackwhit3 's solution worked. Thanks so much!

**Comment by Sheeryada** [comment]
@jackwhit3 Thanks a lot. your solution solved my issue.

**Comment by kambojankit** [comment]
Thanks @Alberto- Its now working for me too.

**Comment by marciandmnd** [comment]
@jackwhit3 
This solution works on Ubuntu 15.04

**Comment by KassPerf** [comment]
Thanks @jackwhit3 it works for me on my Mac 10.11.2

**Comment by SeanGo** [comment]
@jackwhit3 Thank You Very Much! it works on Centos7 x64

**Comment by wjazz3911** [comment]
Thanks @jackwhit3 it works for me on my Mac 10.10.1 and  Chrome version must be >= 43.0.2357.0

**Comment by victorhazbun87** [comment]
Thank you @jackwhit3, is there an alternative for "directConnect" ? Please let me know.

**Comment by sergeycooper** [comment]
"directConnect: true" solved my problem. Thanks man!

**Comment by Bretto** [comment]
"directConnect: true" solved my problem. Thanks man!

**Comment by canercak** [comment]
add  directConnect: true  to protractor.conf.js

**Comment by EoinGriffin-AI** [comment]
Didn't work for me. I'm already using `directConnect: true`
Currently blocked by this issue.

**Comment by robinj** [comment]
This seems to be caused by trying to connect to your Selenium server using DHCP IP address rather than 127.0.0.1 or localhost which would be more sensible. 

When I am offline or connected to a DMZ this works perfectly fine, but when I connect to my VPN the error occurs.

**Comment by EoinGriffin-AI** [comment]
Installing the latest Java 8 JRE using `apt-get` (Ubuntu) fixed this for me, although I don't know why. I already had the JDK installed.

**Comment by KeidyGibson01** [comment]
I use selenium webdriverjs and i have this same problem but I can not find the rotractor-conf.js

**Comment by gkalpak** [comment]
It is in `/e2e-tests/protractor.conf.js`.

**Comment by sankargorthi** [comment]
Was trying out the tutorial and ran into this today. Had to add this to `e2e-tests.js/protractor.conf.js`
```js
directConnect: true
```

The tags in the tutorial don't have this change.

**Comment by mjohenneken** [comment]
If you search google for "Timed out waiting for Webdriver" this is the first result. I find it worth to mention, that this Error happens when you use Firefox  > 47.0 with an Selenium version < 3.0.
That's because Firefox made some changes and the native FirefoxDriver doesn't work anymore. If you want to use the newest Firefox you have to use the Marionette driver.

**Comment by aniruddhadas9** [comment]
adding `directConnect: true` in protractor config file worked for me.

**Comment by anurbol** [comment]
In my case, chrome was not installed, installing helped: https://askubuntu.com/a/510186

**Comment by edgarechm** [comment]
Quick and easy question:
This URL: http://192.168.0.102:54508/wd/hub
Is a Local domain, the same as using 127.0.0.1? Where does it come from?
