### ISSUE TITLE
testing error - addMatchers is not a function 

### ISSUE THREAD

**Issue by ajlee** [angular/angular-phonecat#277]
I'm following the tutorial to learn how to use Angular. But I am getting this error when I try run the npm test command:

<code>
PhoneCat controllers PhoneListCtrl should create "phones" model with 2 phones fetched from xhr FAILED 
TypeError: this.addMatchers is not a function at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:7:10)
Expected [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ] to equal [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ].
Error: Expected [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ] to equal [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ].
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:34:28)
Chrome 45.0.2454 (Mac OS X 10.11.0) PhoneCat controllers PhoneListCtrl should set the default value of orderProp model FAILED
TypeError: this.addMatchers is not a function
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:7:10)
Chrome 45.0.2454 (Mac OS X 10.11.0) PhoneCat controllers PhoneDetailCtrl should fetch phone detail FAILED
TypeError: this.addMatchers is not a function
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:7:10)
TypeError: expect(...).toEqualData is not a function
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:66:27)
</code>

**Comment by Stargator** [comment]
I got to step 11 and I am getting the same issue. Though when I run "git checkout -f step-11" and "npm test" it runs fine.

The only difference is the version of the dependencies. I using the latest available.. Seems karma-jasmine ~0.1.0 works, but anything at or above 0.2.0 causes this error to appear.
