### ISSUE TITLE
Unable to install Protractor on Windows 7 machine

### ISSUE THREAD

**Issue by SMMatti** [angular/angular-phonecat#281]
Hi All,

I have installed Nodejs successfully and facing an issue with installing Protractor on Windows 7 machine. 

Please find the below command prompt error.

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\310197644>npm --version
2.14.7

C:\Users\310197644>node --version
v4.2.1

C:\Users\310197644>npm install -g protractor
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "protractor"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ETIMEDOUT
npm ERR! errno ETIMEDOUT
npm ERR! syscall connect

npm ERR! network connect ETIMEDOUT 23.235.43.162:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settin
gs.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\310197644\npm-debug.log

C:\Users\310197644>

Also find the attached npm-debug log file.

Any suggestions/inputs would be appreciated.

Thanks & Regards,
Matti

![logfile](https://cloud.githubusercontent.com/assets/15606534/10876260/2a93b842-8161-11e5-9e6d-6b6e2dfe2e62.png)

**Comment by gkalpak** [comment]
Closing as this is an issue with npm and not with the tutorial itself.
Besides you don't need to install protractor (or any other node dependency) globally for the tutorial to work.
