### ISSUE TITLE
Failure to create database using mysql

### ISSUE THREAD

**Issue by michaldrori** [angular/angular-phonecat#282]
Hi,

For some reason my scripts are failing on:
mysql.connector.errors.DatabaseError: 1006 (HY000): Can't create database

Can you please check if there's any memory issue (or any other problem with mysql)

Thanks
Michal

**Comment by michaldrori** [comment]
Hi,

I also receive the following errors, which might suggest there's a memory issue:

DBD::mysql::st execute failed: Error writing file './o_Althaea/SimilarSequencesAlthaea.frm' (Errcode: 28) at /share/apps/orthomclSoftware-v2.0.3/bin/orthomclInstallSchema line 146, <F> line 12.
Error writing file './o_Althaea/SimilarSequencesAlthaea.frm' (Errcode: 28) at /share/apps/orthomclSoftware-v2.0.3/bin/orthomclInstallSchema line 146, <F> line 12.


Please check it out and let me know what you find

Thanks
Michal

**Comment by gkalpak** [comment]
Wrong repository ?
