### ISSUE TITLE
CD-HIT command not found on some nodes on Jekyl

### ISSUE THREAD

**Issue by michaldrori** [angular/angular-phonecat#288]
Hi,

Please check why some of the nodes on Jekyl don't recognize CD-Hit command path:

[michaldrori@compute-8-10 ~]$ /bioseq/cd_hit/cd-hit
/bioseq/cd_hit/cd-hit: Command not found.

For example compute-8-0

Best Regards,
Michal

**Comment by gkalpak** [comment]
Wrong repository ?
