### ISSUE TITLE
_http_outgoing.js:351       throw new TypeError('The header content contains invalid characters');       ^

### ISSUE THREAD

**Issue by kimbeast** [angular/angular-phonecat#303]
## Environment : 
Windows 10 64bit, nodejs 4.3.x and nodejs 5.6.x

## Issue : 
**Trying to connect after starting with "npm start",  http-server die with follwing error.**

```
_http_outgoing.js:351
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ResponseStream.(anonymous function) [as setHeader] (C:\SourceIgloo\0.Studying\AngularJS\angular-phonecat\node_modules\http-server\node_modules\union\lib\response-stream.js:86:34)
    at serve (C:\SourceIgloo\0.Studying\AngularJS\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:146:11)
    at C:\SourceIgloo\0.Studying\AngularJS\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:139:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```

## Solution :
**need to upgrade http-server to 0.8.5**

In package.json
```
"http-server": "^0.8.5"
```

**Comment by inithink** [comment]
It doesn't solve the problem in my environment...
(Windows 10 64bit, nodejs 4.3)

**Comment by inithink** [comment]
Solution : upgrade karma

**Comment by DanGld** [comment]
> Solution: upgrade karma

How to do this?

**Comment by inithink** [comment]
maybe...  
npm install karma --save    
(you should see package.json file and update karma related packages)

**Comment by DanGld** [comment]
Solved: OS language wasn't english, so chars in header were not identified -> TypeError('The header content contains invalid characters')

**Comment by igoradamenko** [comment]
@DanGld Change OS lang because framework's example does not work? No.

Try `npm install http-server -D`. More info in PR: #311

**Comment by HBXSZ** [comment]
why "http-server": "^0.8.5" isn't work on my issue? Throw the same err:TypeError: The header content contains invalid characters
node v4 
npm v2

**Comment by igoradamenko** [comment]
@HBXSZ try the 0.9.0 version. check the PR: #311

**Comment by namecgg** [comment]
not work

**Comment by HBXSZ** [comment]
@igoradamenko yep! It works fine,thanks a lot!

**Comment by namecgg** [comment]
@igoradamenko Thanks,It works fine!!!

**Comment by seeallsea** [comment]
Yes, 0.9.0 version works fine on my environment!

**Comment by Aslan1992** [comment]
Changing version to 0.9.0 works well!

**Comment by Themercee** [comment]
Yeah! I got the same problem and you solve my issue :+1:

**Comment by martinlong77** [comment]
@igoradamenko Thanks,that's the anwser.

**Comment by ottercoder** [comment]
works fine
