### ISSUE TITLE
Problem with starting a server

### ISSUE THREAD

**Issue by SvDen** [angular/angular-phonecat#304]
I tried to learn the 1-st step from angular tutorial but I couldn't even start a server.
It starts normally, but when I am going to visit http://127.0.0.1:8000/ it throws me an error. I attached debug.txt here.
Help me please.

[npm-debug.txt](https://github.com/angular/angular-phonecat/files/131377/npm-debug.txt)

**Comment by SvDen** [comment]
Still important.
I updated all of modules include http-server but it changes nothing.
https://gyazo.com/01914e2f84db1fab4aca9eb2edfc0bff

**Comment by portfolio-examples** [comment]
I've got the same problem.

npm-start -> starting up http-server, available.

but when trying to connect via chrome or ff:

_http_outgoing.js:351
      throw new TypeError('The header content contains invalid characters');

 I've updated http-server and karma. That didn't help.

**Comment by SvDen** [comment]
That didn't help me too.

But I got another solution, step by step:
1. cd /path/to/your/app
2. install 'npm i -g lite-server'
3. run 'lite-server' being in the /app directory.

I hope it helps you. Not what I expected, but still working.

**Comment by portfolio-examples** [comment]
Thank you very much SvDen. 

lite-server is the solution I was lookin for!

**Comment by incaib** [comment]
Can view a sample Of header, html sended to server?

**Comment by portfolio-examples** [comment]
Im not sure if thats what you asking for (lines with '>'):

http://imgur.com/pg8TutE

**Comment by Toisen** [comment]
Same problem here. Thanks for lite-server solution, but I still don't know how to make protractor to find what it needs. I changed a port of baseUrl parameter in default config to 3000 (lite-server runs at it) but protractor still can't get index.html

**Comment by igoradamenko** [comment]
Right now `npm install http-server -D` fixes it for me.

More info in PR: #311

**Comment by braveliuchina** [comment]
@igoradamenko i tried ‘npm install http-server -D ’,but it doesn't work. had the latest http-server version  
solved the problem ?

**Comment by igoradamenko** [comment]
@braveliuchina It's interesting. Are you sure about the version of `http-server`? Try to check out [this issue](https://github.com/indexzero/http-server/issues/244).

**Comment by braveliuchina** [comment]
@igoradamenko  thanks .i solved this problem by changing the version of http-server in package.json.

**Comment by MocYang** [comment]
I update http-server to 0.9.0.Then change the package.json file .Now everything goes well.

**Comment by Doubl3** [comment]
Upgrading the http-server dependency to 0.9.0 seems to fix the pb. Thank you @igoradamenko  & @MocYang !

This issue could now be closed, if somebody still contributes to this tutorial.

**Comment by gkalpak** [comment]
Thx for getting back.
I will leave this open, as in its current state the tutorial fails (i.e. the user needs to update the dependency themselves).

I am about to submit a PR that will take care of that (among other stuff), as well as bring the tutorial up to speed with angular v1.5.
I'll close this when it lands.

**Comment by kuznets** [comment]
I have problem with start node.js (http-server 0.9.0)
First start pass is good, node start and browser display angular-phonecat page.
Then I resets workspace to step 0, start node end get errors.
console log:
______________________________________________________________
 $ npm start
 angular-phonecat@0.0.0 prestart D:\NodeJs\angular-phonecat
 npm install

 angular-phonecat@0.0.0 postinstall D:\NodeJs\angular-phonecat
 bower install

 angular-phonecat@0.0.0 start D:\NodeJs\angular-phonecat
 http-server -a 0.0.0.0 -p 8000

 events.js:141
       throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE 0.0.0.0:8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at nextTickCallbackWith3Args (node.js:453:9)
    at process._tickCallback (node.js:359:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a 0.0.0.0 -p 8000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\NodeJs\angular-phonecat\npm-debug.log
_____________________________________________________________________
and npm-debug.log

How to repair it?

[npm-debug.txt](https://github.com/angular/angular-phonecat/files/278700/npm-debug.txt)

**Comment by gkalpak** [comment]
@kuznets, this mrans that the first instance is still running and bound to pirt 8000, so the port is not available for the second instance to bind to.
You can't have more than one instances running at the same time - make sure the first one has been stopped properly.
