### ISSUE TITLE
Step 7 Excute Snapshots.

### ISSUE THREAD

**Issue by RajeswarReddy** [angular/angular-phonecat#307]
Anyone kindly provide me the files and code for step7 with snapshots(images) kindly. This task is much needed for me kindly respond anyone who have done that step

**Comment by petebacondarwin** [comment]
@RajeswarReddy - I am sorry but the GitHub issue tracker is not a support forum. It is for bugs and feature requests for the tutorial app. You can look for further help on [StackOverflow](http://stackoverflow.com/search?q=phonecat), [Gitter](https://gitter.im/angular/angular.js) and the [angular mailing list](https://groups.google.com/forum/#!forum/angular).

**Comment by petebacondarwin** [comment]
But regarding your question...

If you have cloned this repository using git then you should be able to set your working copy to step-8 by running....

```bash
git checkout step-8
```

If not then you can download that tagged version of the code at https://github.com/angular/angular-phonecat/archive/step-8.zip

**Comment by RajeswarReddy** [comment]
@petebacondarwin  sir could you please send me the link which have all the zip files from 1 to 12?

**Comment by petebacondarwin** [comment]
I think you can guess them if you look carefully at the URL I gave you :-)

**Comment by petebacondarwin** [comment]
Please direct further questions at the support websites I linked to above.
