### ISSUE TITLE
http server is not displaying the structure

### ISSUE THREAD

**Issue by shan31** [angular/angular-phonecat#312]
Starting up http-server, serving ./ on port: 8000
Hit CTRL-C to stop the server

After this my project doees not structuring the display

**Comment by gkalpak** [comment]
What do you mean by _"not structuring the display"_ ?
What do you see in the browser ? What is the address in the address bar ?

**Comment by vargavince91** [comment]
```
~/angular-phonecat$ npm start app
```

If you go to [0.0.0.0:8000](http://0.0.0.0:8000/), you'll see the app.

Maybe you typed `npm start` (without `app`)?

**Comment by gkalpak** [comment]
Since there was no response, I assume this is not an issue any more.
(BTW, you don't need the `app` part; `npm start` is enough.)
