### ISSUE TITLE
issues when  npm run protractor

### ISSUE THREAD

**Issue by xu-snow** [angular/angular-phonecat#316]
The npm-debug.log:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.14.12
3 info using node@v4.3.2
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:821:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd /Users/zhengxu/Desktop/angular/angular-phonecat
13 error Darwin 15.2.0
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
15 error node v4.3.2
16 error npm  v2.14.12
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor test/protractor-conf.js
19 error You can get their info via:
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by DanielaGSB** [comment]
Can you check that you have the latest version of the Chrome Browser installed and that selenium is up to date?
Have you tried installing protractor globally and running it directly:

npm install -g protractor
protractor test/protractor-conf.js

**Comment by xu-snow** [comment]
Thank you very much!

**Comment by xu-snow** [comment]
thank you very much,i found  clone the lastest vesion of phonecat and the problom is gone.
