### ISSUE TITLE
Continious integration tests broken

### ISSUE THREAD

**Issue by programmador** [angular/angular-phonecat#317]
If you now go to the pull requests list you'll see that lots of them are rejected because of continious integration tests fail. The eror message is:
`error: pathspec 'step-{0..12}' did not match any file(s) known to git.`

If I change in this line:
https://github.com/angular/angular-phonecat/blob/master/scripts/private/test-all.sh#L28
`for i in {0..12}`
to
``for i in `seq 1 12```
the test will run successfully.

I'm not very skilled in bash scripting so I don't know whether using `seq` command is the best solution here. Also I don't know why `{0..12}` doesn't work. Anyway please pay attention to this bug and be sure to re-run the continious integration checks on all pending pull requests after fixing it.

**Comment by gkalpak** [comment]
There's a pull request for that : #280
It'll get merged soon.

Let's track this problem there.
