### ISSUE TITLE
angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000` Exit status 1

### ISSUE THREAD

**Issue by HBXSZ** [angular/angular-phonecat#318]
I update http-server to 0.8.5,then run npm start,
Starting up http-server, serving ./
Available `on:`
  http:192.168.28.151:8000
  http:127.0.0.1:8000
When I open all of above at chrome,throw err,
_0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v5.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info start angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec start script
10 verbose stack Error: angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\lifecycle.js:217:16)
10 verbose stack     at emitTwo (events.js:100:13)
10 verbose stack     at EventEmitter.emit (events.js:185:7)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_global\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:100:13)
10 verbose stack     at ChildProcess.emit (events.js:185:7)
10 verbose stack     at maybeClose (internal/child_process.js:850:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd C:\Users\Administrator\WebstormProjects\untitled13\angular-phonecat-master
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v5.8.0
16 error npm  v2.15.0
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     http-server -a 0.0.0.0 -p 8000
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs angular-phonecat
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]
I‘m_ confused where the matter is.

**Comment by gkalpak** [comment]
Could it be due to node v5 ? Could you try with node v4 ?

<sub>(BTW, node v5 wuth npm v2 ? How come not npm v3 ?)</sub>

**Comment by HBXSZ** [comment]
@gkalpak I have used node v5.8 ，then npm warn:you'd better install npm v2 -g,so I try npm v2,it seems doesn't work,I'll try node v4

**Comment by HBXSZ** [comment]
@gkalpak  it works fine refer to [https://github.com/igoradamenko/angular-phonecat/commit/8d5da7c61c02d3c1b17fa7abfaf2767c8174ba81](config as it says)

**Comment by gkalpak** [comment]
Thx for the follow-up, @HBXSZ.
I will close this issue, since you got it working. (We will update our dependencies soon, so this shouldn't be an issue in the future).
