### ISSUE TITLE
protractor-conf.js: Permission denied

### ISSUE THREAD

**Issue by marchowardbegins** [angular/angular-phonecat#320]
when trying to run npm run protractor (with or without sudo on my Mac) per Step 3 of the Phonecat tutorial i get a permission denied error.  attached is the log.  moving to another directory does not appear to help nor recreating the protractor-conf.js file.  below is the npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/marchoward/angular-phonecat/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /Users/marchoward/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/marchoward/angular-phonecat/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /Users/marchoward/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'test/protractor-conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 126  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `test/protractor-conf.js`
18 verbose stack Exit status 126
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at EventEmitter.emit (events.js:185:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
18 verbose stack     at emitTwo (events.js:100:13)
18 verbose stack     at ChildProcess.emit (events.js:185:7)
18 verbose stack     at maybeClose (internal/child_process.js:850:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /Users/marchoward/angular-phonecat
21 error Darwin 15.3.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
23 error node v5.8.0
24 error npm  v3.7.3
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `test/protractor-conf.js`
26 error Exit status 126
27 error Failed at the angular-phonecat@0.0.0 protractor script 'test/protractor-conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     test/protractor-conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by gkalpak** [comment]
Could you try with node v4/npm v2 ?
(I'm not sure that's the issue, but would be useful to find out.)

**Comment by marchowardbegins** [comment]
Hi looks like the problem is fixed.  I just saw your message so I think you solution may have resolved it as well since it appears it has to do with versions.  What I did was delete app/bower_components then run npm install and that appeared to refresh bower and then I was able to successfully execute npm run protractor.  Thanks for the fast response!
