### ISSUE TITLE
I've got a proplem with protractor

### ISSUE THREAD

**Issue by Gennady77** [angular/angular-phonecat#323]
I try to run End to End test npm run protractor. As a result I get error. This is a log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
6 info preprotractor angular-phonecat@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info protractor angular-phonecat@0.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-phonecat@0.0.0 Failed to exec protractor script
11 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
11 error Exit status 8
12 error Failed at the angular-phonecat@0.0.0 protractor script.
12 error This is most likely a problem with the angular-phonecat package,
12 error not with npm itself.
12 error Tell the author that this fails on your system:
12 error     protractor test/protractor-conf.js
12 error You can get their info via:
12 error     npm owner ls angular-phonecat
12 error There is likely additional logging output above.
13 error System Windows_NT 6.2.9200
14 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
15 error cwd E:\Users\User\Documents\NetBeansProjects\angular-phonecat
16 error node -v v0.10.26
17 error npm -v 1.4.3
18 error code ELIFECYCLE
19 verbose exit [ 1, true ]

What's the problem?

**Comment by zhoubihn** [comment]
I faced a similiar problem below:
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
[launcher] Process exited with error code 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)

**Comment by Gennady77** [comment]
Unfortunatly problem wasn't be solved. In addition to those error I had an exception:

Error: Server terminated early with status 1
    at Error (<anonymous>)
    at E:\Users\User\Documents\NetBeansProjects\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver
\remote\index.js:204:18
    at promise.ControlFlow.runInFrame_ (eval at <anonymous> (E:\Users\User\Documents\NetBeansProjects\angular-phonecat\n
ode_modules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1124:19), <anonymous>:1857:20)
    at goog.defineClass.notify (eval at <anonymous> (E:\Users\User\Documents\NetBeansProjects\angular-phonecat\node_modu
les\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1124:19), <anonymous>:2448:25)
    at promise.Promise.notify_ (eval at <anonymous> (E:\Users\User\Documents\NetBeansProjects\angular-phonecat\node_modu
les\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1124:19), <anonymous>:564:12)
    at Array.forEach (native)
    at promise.Promise.notifyAll_ (eval at <anonymous> (E:\Users\User\Documents\NetBeansProjects\angular-phonecat\node_m
odules\protractor\node_modules\selenium-webdriver\lib\goog\base.js:1124:19), <anonymous>:553:15)
    at goog.async.run.processWorkQueue [as _onTimeout] (E:\Users\User\Documents\NetBeansProjects\angular-phonecat\node_m
odules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:130:15)
    at Timer.listOnTimeout [as ontimeout] (timers.js:110:15)

**Comment by sylnp0201** [comment]
Same here. I found the solution from this [issue](https://github.com/angular/angular-phonecat/issues/252). In test/protractor-conf.js replace `chromeOnly: true,` by `directConnect: true,`.

**Comment by rarspace01** [comment]
I had the same problem with ubuntu 16.04, i found that i have to install java (i did install the openjdk: `sudo apt-get install openjdk-8-jre` and then it worked)

**Comment by zhoubhin** [comment]
@rarspace01  maybe compiling java manually is a more good choice rather han using `sudo apt-get install`

**Comment by danwulff** [comment]
Had the same problem on Ubuntu 16.04, per @rarspace01 's recommendation, installing java fixed it for me:
$ sudo apt-get update
$ java -version                 (to make sure java wasn't already installed)
$ sudo apt-get install default-jre

**Comment by Cynthi23** [comment]
sudo apt-get install default-jre does not seem to be working
