### ISSUE TITLE
Problems with start angular-phonecat Wndows 7

### ISSUE THREAD

**Issue by shepetovdm** [angular/angular-phonecat#324]
Starting up http-server, serving ./ on port: 8000
Hit CTRL-C to stop the server
[Sun, 10 Apr 2016 15:29:51 GMT] "GET /app/index.html" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Geck
o) Chrome/49.0.2623.110 Safari/537.36"
_http_outgoing.js:351
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ResponseStream.(anonymous function) [as setHeader] (D:\!Projects\Angular\angular-phonecat\node_modules\http-serve
r\node_modules\union\lib\response-stream.js:86:34)
    at serve (D:\!Projects\Angular\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:146:1
1)
    at D:\!Projects\Angular\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:139:9
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a 0.0.0.0 -p 8000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\!Projects\Angular\angular-phonecat\npm-debug.log
PS D:\!Projects\Angular\angular-phonecat>
FILE npm-debug:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info start angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec start script
10 verbose stack Error: angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:827:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd D:\!Projects\Angular\angular-phonecat
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v4.4.2
16 error npm  v2.15.0
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     http-server -a 0.0.0.0 -p 8000
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs angular-phonecat
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by gkalpak** [comment]
This is due to outdated dependecies (more specifically `http-server`). We are about to update all our dependencies (including `http-server`).

In the meantime, you can solve this by manually updating your local version of `http-server` to `0.9.0` or newer. E.g.:

```
npm uninstall http-server
npm install http-server@0.9.0
```
