### ISSUE TITLE
Could not copy files

### ISSUE THREAD

**Issue by waywayan** [angular/angular-phonecat#325]
Hello 

while trying to copy files to local directory I got following error:
$ git clone --depth=14 https://github.com/angular/angular-phonecat.git
Cloning into 'angular-phonecat'...
fatal: unable to access 'https://github.com/angular/angular-phonecat.git/': Coul
dn't resolve host 'github.com'
1. I'm using SSH
2. I'm working behind a corporate proxy, but access via proxy is configured globally in npmrc and bowerrc.

$ ssh -v
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]

Why it is not working? 

Thanks!

Regards

**Comment by gkalpak** [comment]
As per the message, you aren't able to access `github.com` (where the repository is hosted).
This was either a temporary, connectivity/availability issues, or a restricted network access/proxy issue.

In any case, this is not related to the tutorial. Closing.
