### ISSUE TITLE
e2e error at step NR. -1 

### ISSUE THREAD

**Issue by korulis** [angular/angular-phonecat#328]
Hi,
at step Nr1. (https://docs.angularjs.org/tutorial) on last sub step "Running End to End Tests"

I get an error on command "npm run protractor"

Finished in 12.909 seconds
7 tests, 11 assertions, 1 failure

Shutting down selenium standalone server.
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] overall: 1 failed spec(s)
[launcher] Process exited with error code 1

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\nodejs\\node.exe" "C:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ProjectsGit\angular-phonecat\angular-phonecat\npm-debug.log

And the file " C:\ProjectsGit\angular-phonecat\angular-phonecat\npm-debug.log" does not get generated.

The first run of e2e tests was successful btw, but the 4 subsequent attempts yelded the same error.
PS. I do have the the latest java version and the cmd is being run in admin mode.

Help?

**Comment by korulis** [comment]
The exact error message : 
...
...
Selenium standalone server started at http://10.1.1.50:62553/wd/hub
...F...

Failures:

  1) PhoneCat App Phone list view should render phone specific links
   Message:
     Expected '/phones/motorola-xoom-with-wi-fi' to equal '/phones/nexus-s'.
   Stacktrace:
     Error: Expected '/phones/motorola-xoom-with-wi-fi' to equal '/phones/nexus-s'.
    at new jasmine.ExpectationResult (C:\ProjectsGit\angular-phonecat\angular-phonecat\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:137:32)
    at [object Object].<anonymous> (C:\ProjectsGit\angular-phonecat\angular-phonecat\node_modules\protractor\node_modules\minijasminenode\lib\jasmine-1.3.1.js:1349:29)
    at [object Object].toEqual (C:\ProjectsGit\angular-phonecat\angular-phonecat\node_modules\protractor\node_modules\jasminewd\index.js:248:11)
    at C:\ProjectsGit\angular-phonecat\angular-phonecat\test\e2e\scenarios.js:70:21
    at Array.forEach (native)
    at goog.async.run.processWorkQueue (C:\ProjectsGit\angular-phonecat\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\lib\goog\async\run.js:130:15)

Finished in 12.909 seconds
7 tests, 11 assertions, 1 failure
...
...

**Comment by dusuney** [comment]
I had  same issue. Try to update depending

**Comment by gkalpak** [comment]
All dependencies and tools have been updated recently (along with the tutorial itself) and this is hopefully not an issue any more.
If anyone is still having problems, please open a new issue.
