### ISSUE TITLE
erorr, on my mac

### ISSUE THREAD

**Issue by ysfox** [angular/angular-phonecat#330]
9 verbose pkgid angular-phonecat@0.0.0
10 verbose cwd /Users/Ysfox/Desktop/angular-phonecat
11 error Darwin 14.5.0
12 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
13 error node v4.4.4
14 error npm  v2.15.1
15 error code ELIFECYCLE
16 error angular-phonecat@0.0.0 preprotractor: `npm run update-webdriver`
16 error Exit status 1
17 error Failed at the angular-phonecat@0.0.0 preprotractor script 'npm run update-webdriver'.

**Comment by gkalpak** [comment]
There is not enough info to diagnose the problem here.

In any case, all dependencies and tools have been updated recently and this is hopefully not an issue any more. If anyone is still having problems, please open a new issue.
