### ISSUE TITLE
Issues with running "npm test" on Windows 10

### ISSUE THREAD

**Issue by jshin49** [angular/angular-phonecat#331]
Hi there I've been having issues with npm test, Karma unit tests, on the step-2.

Anyone knows why?

The following is the error-log:
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 50.0.2661 (Windows 10 0.0.0)]: Connected on socket wGn9Y8QeTAPEkhAocJiU with id 80523642
ERROR [karma]: [TypeError: The header content contains invalid characters]
TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at ServerResponse.res.setHeader (C:\Users\jshin\Dropbox\Dev\workspace\Angular\angular-phonecat\node_modules\connect\lib\patch.js:134:22)
    at Object.setNoCacheHeaders (C:\Users\jshin\Dropbox\Dev\workspace\Angular\angular-phonecat\node_modules\karma\lib\middleware\common.js:76:12)
    at C:\Users\jshin\Dropbox\Dev\workspace\Angular\angular-phonecat\node_modules\karma\lib\middleware\karma.js:109:18
    at C:\Users\jshin\Dropbox\Dev\workspace\Angular\angular-phonecat\node_modules\karma\lib\middleware\common.js:63:35
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
npm ERR! Test failed.  See above for more details.

**Comment by gkalpak** [comment]
This must be related to outdated dependencies. Try updating `http-server` (see https://github.com/angular/angular-phonecat/issues/322#issuecomment-211279406).
There is already a PR for updating all dependencies (and the tutorial itself).

**Comment by jshin49** [comment]
I have already done updating http-server to the newest version.

Maybe I should try to update all of the outdated dependencies?

**Comment by gkalpak** [comment]
You might also try updating `karma`. I think that one was causing that error (possibly because of using `http-server` under the hood). BTW, you can take a look at the pending PR: #326

**Comment by jshin49** [comment]
Following the PR: #326 resolved my issue. All I did is updating the package.json and run npm install
