### ISSUE TITLE
Filtering only by name not also by description

### ISSUE THREAD

**Issue by DAT14WRomulusDanielNegut** [angular/angular-phonecat#337]
The filter should display based by the name, but instead it filters also by description.
If that was intended, how can it filter only by phone name?

**Comment by gkalpak** [comment]
Yes, it is intended. If you want to filter by name only, replace `| filter:$ctrl.query` with `| filter:{name: $ctrl.query}` on the repeater (or replace `ng-model="$ctrl.query"` with `ng-model="$ctrl.query.name"` on the text input).
For more info see [the docs][1].

[1]: https://docs.angularjs.org/api/ng/filter/filter

**Comment by DAT14WRomulusDanielNegut** [comment]
Thank you!
