### ISSUE TITLE
unable to execute conf.js 

### ISSUE THREAD

**Issue by checkshailendra** [angular/angular-phonecat#344]
have setup the Protractor and could able to run the Example.js conf and able to see the results.

but when tried with my project conf.js unable to execute the same and getting the below error message.

throw new exitCodes_1.ConfigError(logger, 'failed loading configurat
ion file ' + filename);
            ^

any response would be much appreciated.

**Comment by gkalpak** [comment]
This doesn't seem related to this repository. It's also impossible to help more without any info about the code. In any case, I suggest you seek help on a general support channel, e.g. StackOverflow.
