### ISSUE TITLE
Update minimatch

### ISSUE THREAD

**Issue by alanyee** [angular/angular-phonecat#347]
It works, but
```
$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
```
I think updating is in order.

**Comment by gkalpak** [comment]
We are not using `minimatch`. It is a transient dependency. Nothing we can do about it (unless it is updated in the packages that depend on it.

Closing as non-actionable. Feel free to suggest a different update (in one of our dependencies) if it improves the situation.
