### ISSUE TITLE
Want to use Jasmine HTML reporter along with the Protractor HTML reporter

### ISSUE THREAD

**Issue by checkshailendra** [angular/angular-phonecat#348]
Hi,

i have tried to use Jasmine HTML reporter along with the Protractor HTML reporter.

My Config.js code look like this

var HtmlReporter = require('protractor-html-screenshot-reporter');
		
		jasmine.getEnv().addReporter(new HtmlReporter({
			baseDirectory: '/protractor-result', // a location to store screen shots.
			docTitle: 'Protractor Demo Reporter',
			docName:    'protractor-demo-tests-report.html'
		}));
		
		
		var Jasmine2HtmlReporter = require('protractor-jasmine2-html-reporter');
		
		jasmine.getEnv().addReporter(new Jasmine2HtmlReporter({
			savePath: '../Report/HTML/',
			showSummary: true,
			showQuickLinks: true,
			showConfiguration: true,
			screenshotsFolder: 'images',
			takeScreenshots: true,
			takeScreenshotsOnlyOnFailures: true,
			fixedScreenshotName: true,
			ignoreSkippedSpecs: true,
			consolidate: true,
			consolidateAll: true,
			preserveDirectory: true,
			reportTitle: 'Protractor-Execution-Report-' + timeStamp
		}));
		
**i could able to see HTML reports generated by Jasmine but still unable to see the HTML reports generated by Protractor.**

Any help would be appreciated.

**Comment by gkalpak** [comment]
Closing since this is not related to the tutorial. Please, use one of the [general support channels][1] for these types of questions.

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
