### ISSUE TITLE
Unable to execute "npm run protractor" on Windows 10

### ISSUE THREAD

**Issue by vishipayyallore** [angular/angular-phonecat#350]
> angular-phonecat@0.0.0 protractor A:\LordKrishna\vishipayyallore\angular-phonecat
> protractor e2e-tests/protractor.conf.js

[15:07:08] I/local - Starting selenium standalone server...
[15:07:08] I/launcher - Running 1 instances of WebDriver
[15:07:08] E/launcher - Process exited with error code 1
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn java ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     A:\LordKrishna\vishipayyallore\angular-phonecat\npm-debug.log

**Comment by gkalpak** [comment]
It seems that you either don't have JDK installed or the Java executable can't be found on the PATH.
You can check your setup by running `java -version` (as mentioned in the tutorial).

<sub>(Another option would be adding `directConnect: true` to your `protractor.conf.js`, but it will only work for Chrome and Firefox - not that it matters much for the tutorial.</sub>

**Comment by vishipayyallore** [comment]
gkalpak,
I figured out after posting. I have installed java jdk and other node dependencies. Also I was not running the "npm start". I figured out little later. Thank you!
