### ISSUE TITLE
problem with npm start

### ISSUE THREAD

**Issue by Bournegit** [angular/angular-phonecat#351]
> angular-phonecat@0.0.0 prestart C:\Users\Bhuwan\angular-phonecat
> npm install

npm WARN install Couldn't install optional dependency: Unsupported

> angular-phonecat@0.0.0 postinstall C:\Users\Bhuwan\angular-phonecat
> bower install

> angular-phonecat@0.0.0 start C:\Users\Bhuwan\angular-phonecat
> http-server -a localhost -p 8000 -c-1 ./app

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8000
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1221:19)
    at listen (net.js:1270:10)
    at net.js:1379:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:64:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:83:10)

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bhuwan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.4.5
npm ERR! npm  v3.3.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server -a localhost -p 8000 -c-1 ./app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server -a localhost -p 8000 -c-1 ./app'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a localhost -p 8000 -c-1 ./app
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Bhuwan\angular-phonecat\npm-debug.log

**Comment by gkalpak** [comment]
This is probably because some other process is listening on port `8000`. Either stop that process first (if it is not necessary), or change the port used by the tutorial (you need to change it in `package.json` and in `e2e-tests/protractor.conf.js`).

Closing, but feel free to continue the discussion below if this doesn't solve the problem.
