### ISSUE TITLE
npm run protractor error

### ISSUE THREAD

**Issue by jwheel1969** [angular/angular-phonecat#353]
running on Windows 10 OS
attached log file as requested.
attempting to run through the tutorial
unable to run - npm run protractor 

Thanks for any help 

[npm-debug.zip](https://github.com/angular/angular-phonecat/files/355802/npm-debug.zip)

**Comment by gkalpak** [comment]
Can you run `npm run update-webdriver` manually and verify that the chromedriver executable is indeed in `node_modules\protractor\selenium`?

If that doesn't work, try removing the `node_modules/` directory and run `npm install` again.
Also, make sure you have a server running when executing `npm run protractor` (as described in the tutorial).

**Comment by mconnor** [comment]
i'm having the same problem with the tutorial. I tried `npm run update-webdriver` but got:

module.js:442
    throw err;
    ^

Error: Cannot find module '../lib/bin/bower'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mikeconnor/Dropbox/mikesFiles/codeTest2016/angular-phonecat001/angular-phonecat/node_modules/.bin/bower:3:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by gkalpak** [comment]
> If that doesn't work, try removing the node_modules/ directory and run npm install again.
Also, make sure you have a server running when executing npm run protractor (as described in the tutorial).

Have you tried that?

**Comment by mconnor** [comment]
Yes. That worked. Thanks.
I can run `npm start` and launch a page. And run a unit test with Karma -  [npm test](url).  Success.
So now the protractor end-to-end test... I have the server running... and the unit test because the tutorial says its go to kee that running. (Btw, i guess the way to do this is to open up separate terminal windows to start the server, start the unit test).... 
i ran `npm run update-webdriver` as instructed... and then `npm run protractor`. That gives didn't work. I get the following:
npm run protractor

> angular-phonecat@0.0.0 preprotractor /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
> npm run update-webdriver


> angular-phonecat@0.0.0 preupdate-webdriver /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
> npm install


> angular-phonecat@0.0.0 postinstall /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
> bower install


> angular-phonecat@0.0.0 update-webdriver /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
> protractor e2e-tests/protractor.conf.js

[16:15:48] I/local - Starting selenium standalone server...
[16:15:48] I/launcher - Running 1 instances of WebDriver
[16:15:49] E/launcher - Process exited with error code 1
/Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^

Error: Server terminated early with status 1
    at Error (native)
    at /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/selenium-webdriver/remote/index.js:210:20
    at Promise.invokeCallback_ (/Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at asyncRun (/Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2652:27)
    at /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/npm-debug.log
Mikes-MacBook:angular-phonecat me$

**Comment by gkalpak** [comment]
You shouldn't be running the unit tests alongside the e2e tests. The unit tests should be running while you develop (or hack around the tutorial), so that every time yoy save a changed file Karma will run your unit tests and let you know if you broke anything.

Once you are ready to run the e2e tests (in a real-world workflow, typically before you commit or push your code), stop the unit tests, start the webserver in a separate terminal (with `npm start`) and start protractor (with `npm run protractor`).

(You should also make sure you have your environment set up correctly, as explained in the respective section of the tutorial.)

**Comment by mconnor** [comment]
thanks. i did all that
is ran `npm run update-webdriver`
no problem
started a server. Not running unit test.
and then `npm run protractor`

that gave me these errors.



Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/npm-debug.log

**Comment by gkalpak** [comment]
That is strange. What step are you at?

**Comment by mconnor** [comment]
step 5

getting these errors:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/6.3.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.5
3 info using node@v6.3.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/.bin:/usr/local/Cellar/node/6.3.0/bin:/Users/mikeconnor/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat/node_modules/.bin:/usr/local/Cellar/node/6.3.0/bin:/Users/mikeconnor/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:852:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /Users/me/Dropbox/myFiles/codeTest2016/angular-phonecat
21 error Darwin 15.5.0
22 error argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "run" "protractor"
23 error node v6.3.0
24 error npm  v3.10.5
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by gkalpak** [comment]
I tried this on a fresh clone of angular-phonecat with Node.js v6.3.0 (on Windows 10) and it works fine for me.

If, instead of `npm run protractor` you run one of the following commands, what is the output:

1. `node_modules/.bin/protractor e2e-tests/protractor.conf.js`
2. `node_modules/.bin/protractor e2e-tests/protractor.conf.js --directConnect`

--
<sub>
If you haven't already, make sure you have an up-to-date clone of the angular-phonecat repo.
Also, some people have suggested in other similar issues, that installing protractor globally helped, although I can't imagine why.
</sub>

**Comment by 4liaise** [comment]
The same issue. See below **promise.js:654:String) [], RemoteException**:

PS C:\work\js\angular-phonecat> npm run protractor
> angular-phonecat@0.0.0 preprotractor C:\work\js\angular-phonecat
> npm run update-webdriver
> angular-phonecat@0.0.0 preupdate-webdriver C:\work\js\angular-phonecat
> npm install
> angular-phonecat@0.0.0 postinstall C:\work\js\angular-phonecat
> bower install
> angular-phonecat@0.0.0 update-webdriver C:\work\js\angular-phonecat
> webdriver-manager update
selenium standalone is up to date.
chromedriver is up to date.
> angular-phonecat@0.0.0 protractor C:\work\js\angular-phonecat
> protractor e2e-tests/protractor.conf.js
[22:10:30] I/local - Starting selenium standalone server...
[22:10:30] I/launcher - Running 1 instances of WebDriver
[22:10:31] E/launcher - Process exited with error code 1
npm : C:\WORK\JS\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:654
строка:1 знак:1
+ npm run protractor
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (C:\WORK\JS\angu...\promise.js:654:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
    throw error;
    ^
Error: Server terminated early with status 1
    at Error (native)
    at C:\WORK\JS\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\remote\index.js:210:20
    at Promise.invokeCallback_ (C:\WORK\JS\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\l
ib\promise.js:1329:14)
    at TaskQueue.execute_ (C:\WORK\JS\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\lib\pr
omise.js:2790:14)
    at TaskQueue.executeNext_ (C:\WORK\JS\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\li
b\promise.js:2773:21)
    at C:\WORK\JS\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2652:27
    at C:\WORK\JS\angular-phonecat\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:639:7
    at process._tickCallback (node.js:369:9)
npm
 
ERR!
 Windows_NT 10.0.10586
npm
 
ERR!
 
argv
 "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protrac
tor"
npm
 
ERR!
 
node
 v4.4.7
npm
 
ERR!
 
npm  v2.15.8
npm
 
ERR!
 
code
 ELIFECYCLE
npm
 
ERR!
 angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm
 
ERR!
 Exit status 1
npm
 
ERR!
 
npm
 
ERR!
 Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm
 
ERR!
 This is most likely a problem with the angular-phonecat package,
npm
 
ERR!
 not with npm itself.
npm
 
ERR!
 Tell the author that this fails on your system:
npm
 
ERR!
     protractor e2e-tests/protractor.conf.js
npm
 
ERR!
 You can get information on how to open an issue for this project with:
npm
 
ERR!
     npm bugs angular-phonecat
npm
 
ERR!
 Or if that isn't available, you can get their info via:
npm
 
ERR!
 
npm
 
ERR!
     npm owner ls angular-phonecat
npm
 
ERR!
 There is likely additional logging output above.
npm
 
ERR!
 Please include the following file with any support request:
npm
 
ERR!
     C:\work\js\angular-phonecat\npm-debug.log

**Comment by gkalpak** [comment]
@4liaise , this is a different error. [This thread][1] might help.

[1]: https://github.com/angular/protractor/issues/2638

**Comment by jwheel1969** [comment]
I was able to get this to work as expected now, windows 10. 

Thanks!

**Comment by gkalpak** [comment]
Great! I am going to close this then.
@jwheel1969, consider posting what the problem was or how you solved it below, to help others that might run into the same problem.

**Comment by Franmoti** [comment]
> gkalpak commented on 15 Jul 2016
> I tried this on a fresh clone of angular-phonecat with Node.js v6.3.0 (on Windows 10) and it works fine for me.
> 
> If, instead of npm run protractor you run one of the following commands, what is the output:
> 
> node_modules/.bin/protractor e2e-tests/protractor.conf.js
> node_modules/.bin/protractor e2e-tests/protractor.conf.js --directConnect

Hello! I have had a similar problem with exit status 199 (you can see in the npm-debug.log file attached) and this solution works for me (the second, with "--directConnect").

Thanks!

15 silly lifecycle angular-phonecat@0.0.0-protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0-protractor: Returned: code: 199  signal: null
17 info lifecycle angular-phonecat@0.0.0-protractor: Failed to exec protractor script

[npm-debug.log.txt](https://github.com/angular/angular-phonecat/files/881741/npm-debug.log.txt)

**Comment by pricolhasan** [comment]
when running protractor using -> gulp protractor:src, getting the  Error: protractor exited with code 1
