### ISSUE TITLE
1.3.x conflict ? what is the issue any clues ?

### ISSUE THREAD

**Issue by jpraval** [angular/angular-phonecat#355]
praval@praval-laptop:~/Desktop/AngularJS/production/ng-1.3/code.collpoll.com/img-grid/angular-phonecat$ npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130

> angular-phonecat@0.0.0 postinstall /home/praval/Desktop/AngularJS/production/ng-1.3/code.collpoll.com/img-grid/angular-phonecat
> bower install

bower angular-mocks#1.3.x   not-cached https://github.com/angular/bower-angular-mocks.git#1.3.x
bower angular-mocks#1.3.x      resolve https://github.com/angular/bower-angular-mocks.git#1.3.x
bower angular-resource#1.3.x       not-cached https://github.com/angular/bower-angular-resource.git#1.3.x
bower angular-resource#1.3.x          resolve https://github.com/angular/bower-angular-resource.git#1.3.x
bower angular#1.3.0                not-cached https://github.com/angular/bower-angular.git#1.3.0
bower angular#1.3.0                   resolve https://github.com/angular/bower-angular.git#1.3.0
bower jquery#2.2.x                     cached https://github.com/jquery/jquery-dist.git#2.2.4
bower jquery#2.2.x                   validate 2.2.4 against https://github.com/jquery/jquery-dist.git#2.2.x
bower angular-route#1.3.x          not-cached https://github.com/angular/bower-angular-route.git#1.3.x
bower angular-route#1.3.x             resolve https://github.com/angular/bower-angular-route.git#1.3.x
bower bootstrap#3.3.x                  cached https://github.com/twbs/bootstrap.git#3.3.7
bower bootstrap#3.3.x                validate 3.3.7 against https://github.com/twbs/bootstrap.git#3.3.x
bower angular-animate#1.3.x        not-cached https://github.com/angular/bower-angular-animate.git#1.3.x
bower angular-animate#1.3.x           resolve https://github.com/angular/bower-angular-animate.git#1.3.x
bower angular-mocks#1.3.x            checkout v1.3.20
bower angular-resource#1.3.x         checkout v1.3.20
bower angular#1.3.0                  checkout v1.3.0
bower angular-route#1.3.x            checkout v1.3.20
bower angular-animate#1.3.x          checkout v1.3.20
bower angular-mocks#1.3.x            resolved https://github.com/angular/bower-angular-mocks.git#1.3.20
bower angular#1.3.20               not-cached https://github.com/angular/bower-angular.git#1.3.20
bower angular#1.3.20                  resolve https://github.com/angular/bower-angular.git#1.3.20
bower angular#1.3.20                 checkout v1.3.20
bower angular-resource#1.3.x         resolved https://github.com/angular/bower-angular-resource.git#1.3.20
bower angular#1.3.0                  progress remote: Compressing objects:  80% (8/10)   
bower angular#1.3.0                  progress remote: Compressing objects:  90% (9/10)   
bower angular#1.3.0                  progress remote: Compressing objects: 100% (10/10)   
bower angular#1.3.0                  progress remote: Compressing objects: 100% (10/10), done.
bower angular-route#1.3.x            progress remote: Compressing objects:  11% (1/9)   
bower angular-route#1.3.x            progress remote: Compressing objects:  22% (2/9)   
bower angular-route#1.3.x            progress remote: Compressing objects:  33% (3/9)   
bower angular-route#1.3.x            progress remote: Compressing objects:  44% (4/9)   
bower angular-route#1.3.x            progress remote: Compressing objects:  55% (5/9)   
bower angular-route#1.3.x            progress remote: Compressing objects:  66% (6/9)   
bower angular#1.3.0                  resolved https://github.com/angular/bower-angular.git#1.3.0
bower angular-route#1.3.x            progress remote: Compressing objects:  88% (8/9)   
bower angular-route#1.3.x            progress remote: Compressing objects: 100% (9/9)   
bower angular-route#1.3.x            progress remote: Compressing objects: 100% (9/9), done.
bower angular-animate#1.3.x          progress remote: Compressing objects:  77% (7/9)   
bower angular-animate#1.3.x          progress remote: Compressing objects:  88% (8/9)   
bower angular-animate#1.3.x          progress remote: Compressing objects: 100% (9/9)   
bower angular-animate#1.3.x          progress remote: Compressing objects: 100% (9/9), done.
bower angular-animate#1.3.x          resolved https://github.com/angular/bower-angular-animate.git#1.3.20
bower angular#1.3.20                 progress remote: Compressing objects:  80% (8/10)   
bower angular#1.3.20                 progress remote: Compressing objects:  90% (9/10)   
bower angular#1.3.20                 progress remote: Compressing objects: 100% (10/10)   
bower angular#1.3.20                 progress remote: Compressing objects: 100% (10/10), done.
bower angular-route#1.3.x            resolved https://github.com/angular/bower-angular-route.git#1.3.20
bower angular#1.3.20                 resolved https://github.com/angular/bower-angular.git#1.3.20
bower                               ECONFLICT Unable to find suitable version for angular

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/praval/Desktop/AngularJS/production/ng-1.3/code.collpoll.com/img-grid/angular-phonecat/npm-debug.log

**Comment by gkalpak** [comment]
It seems that you are depending on both angular v1.3.0 and angular v1.3.20.
In any case, this is a general support question and should be asked in one of the [appropriate support channels][1].
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
