### ISSUE TITLE
How to explain the meaning of  'git checkout -f step-n' ? Thanks

### ISSUE THREAD

**Issue by eyeA** [angular/angular-phonecat#356]
I want to know urgely this answer.
I can change to the step-n easily ,but can't finf the branch named "step-n".

**Comment by dingchuanWen** [comment]
i don't konw this

**Comment by a434828920** [comment]
Would be glad to receive your letter, I am a beginner, I mean: the understanding of this test presents - in 'https://github.com/angular/angular-phonecat' phonecat each step, the set - n is represents one of the steps, git checkout - f step - n this is in the git used to retrieve the content in the git running in the statement.Not the right place hope to get your correction.

**Comment by dingchuanWen** [comment]
no ,   i  is a novice to , nothing  can help you  ， sorry

**Comment by gkalpak** [comment]
`step-n` (where `n` should be substituted with the number of the step, e.g. `step-0`, `step-1`, etc) is not a branch; it is a tag.

--
That said, please, use one of the [appropriate support channels][1] for general support questions such as this one.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx !

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question

**Comment by eyeA** [comment]
@gkalpak OK Thanks.
