### ISSUE TITLE
New steps missing tags

### ISSUE THREAD

**Issue by ZvikaZ** [angular/angular-phonecat#358]
Hi.

The new 'steps' commits are missing tags.
Threrefore, one a user checkouts 'step-3' for example, instead of getting commit '401ee34', he's getting commit '1071c2c'

**Comment by gkalpak** [comment]
Not sure what you mean. The `step-3` tag is set correctly afaict and points to commit 95ab340 (neither 401ee34, nor 1071c2c). It sounds like yur local copy is outdated. Make sure you have pulled the latest content from the repote repo (including tags).

**Comment by ZvikaZ** [comment]
My mistake...
I wasn't aware of 'git fetch --tags'.

Please close this.
Thanks.
