### ISSUE TITLE
Issue setting up on Mac OS X 10.11.4 

### ISSUE THREAD

**Issue by UniyalAshish** [angular/angular-phonecat#362]
Referring tutorial at https://docs.angularjs.org/tutorial (in initial setup step facing below issues)

Environment: Mac OS X 10.11.4 (Chrome 52.0.2743) 

1. when I run command sudo npm start from iTerm:

`"GET /bower_components/jquery/dist/jquery.js" Error (404): "Not found"
"GET /bower_components/angular/angular.js" Error (404): "Not found"
["GET /bower_components/angular-animate/angular-animate.js" Error (404): "Not found"]`

2. when I run "sudo npm run protractor", got below error:

   ` Failed: Angular could not be found on the page http://localhost:8000/index.html : retries looking for angular exceeded`

**Comment by gkalpak** [comment]
For some reason it seems that you haven't got the dependencies downloaded.
Try running `npm install` or `node_modules/.bin/bower install` manually. What happens?

**Comment by gkalpak** [comment]
Since we haven't heard back from the OP, I am going to assume this is not an issue any more :)
