### ISSUE TITLE
Issue running protractor test

### ISSUE THREAD

**Issue by akanksha-singh** [angular/angular-phonecat#368]
I get the following error while running npm run protractor command.

> angular-phonecat@0.0.0 protractor /Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat
> protractor e2e-tests/protractor.conf.js

[18:51:45] I/local - Starting selenium standalone server...
[18:51:45] I/launcher - Running 1 instances of WebDriver
[18:51:45] E/launcher - Process exited with error code 1
/Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^

Error: Server terminated early with status 1
    at Error (native)
    at /Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:210:20
    at Promise.invokeCallback_ (/Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
    at TaskQueue.execute_ (/Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
    at TaskQueue.executeNext_ (/Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
    at /Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
    at /Users/akanksha.singh/Documents/AngularWorkspace/angular-phonecat/node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:369:9)

npm ERR! Darwin 13.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.

**Comment by gkalpak** [comment]
This error is not informative. It seems more related to selenium or protractor though. Also make sure you have all the dependencies installed (including Java) and the port used by selenium is available.

You could also try setting `directConnect: true` in your `protractor.conf.JS` and see if the problem goes away.

**Comment by balaka** [comment]
`directConnect: true` helps, thanks!

**Comment by lsqy** [comment]
l try`directConnect: true`,works!thanks @gkalpak !

**Comment by gkalpak** [comment]
OK, since we haven't heard from the OP and people seem to be able to work around any issues with `directConnect: true`, I am going to close this.
(We should consider including `directConnect: true` by default.)

**Comment by Namita1210** [comment]
I am having same issue while using browser internet explorer. 
directConnect: true - Doesn't work with internet explorer. Any other leads for IE?
