### ISSUE TITLE
Github tags do not line up with tutorial stages

### ISSUE THREAD

**Issue by TepidSwitch** [angular/angular-phonecat#373]
The structure of the different tags in this repository do not follow the steps in the tutorial. The most confusing and glaring example is that at tutorial-7 at https://code.angularjs.org/1.3.20/docs/tutorial/step_07 the user is introduced to extracting templates from index.html, but the github repo has this convention starting at its tag equivalent of tutorial-3. This disconnect between repo and tutorial assumption makes it harder to follow the tutorial along.

**Comment by gkalpak** [comment]
The version of the tutorial you are using (1.3.20) is outdated. (In fact, the 1.3.x version is not supported anymore; in the sense that it won't receive any kind of fixes or updates.)

It is recommended to follow the latest (and greatest) version of the tutorial [here][1], which aligns with the version on the master branch of this repo.

--
In case you absolutely need it, the old tutorial is still available on the 1.4.x docs (e.g. [there][2]) and the corresponding code is on the `1.4-snapshot` branch of this repo. Note that there are no live demos for the old version of the tutorial, but other than that, everything works (including code-diffs).

<sub>(But, really, there shouldn't be any reason not to follow the latest tutorial, especially if you are starting out :smile:</sub>

[1]: https://docs.angularjs.org/tutorial
[2]: https://code.angularjs.org/1.4.12/docs/tutorial

**Comment by TepidSwitch** [comment]
Well then, dunno how I got to the outdated version but that's horribly embarassing.
Thank you so much for the heads up
