### ISSUE TITLE
issue while running npm run protractor

### ISSUE THREAD

**Issue by mlanandnair** [angular/angular-phonecat#379]
While running npm run protractor , it shows error when " npm run update-webdriver". version of nodejs and npm are in correct versions.
![error](https://cloud.githubusercontent.com/assets/22978595/19594085/2e80b642-97a1-11e6-8f45-2521de99f64c.jpg)
![error2](https://cloud.githubusercontent.com/assets/22978595/19594086/2e841238-97a1-11e6-920b-a2539912ac0c.jpg)

**Comment by gkalpak** [comment]
What version of protractor has been installed with `npm install`? E.g. what does `npm list protractor` return?

**Comment by mlanandnair** [comment]
Sorry for the late reply, npm version is latest 3.10.8 and protractor version is 
![untitled](https://cloud.githubusercontent.com/assets/22978595/19673568/af11c832-9a9e-11e6-8bd4-8c24ecd86087.jpg)
protractor@4.0.9

**Comment by gkalpak** [comment]
Hm...the lines on your logs to do match with the webdriver version I have locally. Can you try to remove `node_modules/` and run `npm install` again?

**Comment by gkalpak** [comment]
Since we haven't heard from the OP in a while, I assume this is not an issue any more.
