### ISSUE TITLE
Protractor fails with error 199

### ISSUE THREAD

**Issue by AdamSLevy** [angular/angular-phonecat#381]
I checked out step-6.
I installed the app: `npm install`
I ran the server: `npm start`
I ran protractor and received the following output resulting in error 199:

```
$ npm run protractor

> angular-phonecat@0.0.0 preprotractor /home/aslevy/repos/angular-phonecat
> npm run update-webdriver


> angular-phonecat@0.0.0 preupdate-webdriver /home/aslevy/repos/angular-phonecat
> npm install


> angular-phonecat@0.0.0 postinstall /home/aslevy/repos/angular-phonecat
> bower install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

> angular-phonecat@0.0.0 update-webdriver /home/aslevy/repos/angular-phonecat
> webdriver-manager update

[12:38:51] I/file_manager - creating folder /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium
[12:38:51] I/downloader - selenium standalone: downloading version 2.53.1
[12:38:51] I/downloader - curl -o /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium/selenium-server-standalone-2.53.1.jar https://selenium-release.storage.googleapis.com/2.53/selenium-server-standalone-2.53.1.jar
[12:38:51] I/downloader - chromedriver: downloading version 2.25
[12:38:51] I/downloader - curl -o /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25linux64.zip https://chromedriver.storage.googleapis.com/2.25/chromedriver_linux64.zip
[12:38:51] I/downloader - geckodriver: downloading version v0.9.0
[12:38:51] I/downloader - curl -o /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0-linux64.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-linux64.tar.gz
[12:38:58] I/update - chromedriver: unzipping /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25linux64.zip
[12:38:58] I/update - chromedriver: setting permissions to 0755 for /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25
[12:39:18] I/update - geckodriver: unzipping /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0-linux64.tar.gz
[12:39:18] I/update - geckodriver: setting permissions to 0755 for /home/aslevy/repos/angular-phonecat/node_modules/protractor/node_modules/webdriver-manager/selenium/geckodriver-v0.9.0

> angular-phonecat@0.0.0 protractor /home/aslevy/repos/angular-phonecat
> protractor e2e-tests/protractor.conf.js

[12:39:19] I/local - Starting selenium standalone server...
[12:39:19] I/launcher - Running 1 instances of WebDriver
[12:39:21] I/local - Selenium standalone server started at http://192.168.10.118:37069/wd/hub
[12:39:42] E/launcher - null
[12:39:42] E/launcher - WebDriverError: null
    at WebDriverError (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/error.js:27:5)
    at Object.checkLegacyResponse (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/error.js:639:15)
    at parseHttpResponse (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/http/index.js:538:13)
    at client_.send.then.response (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/http/index.js:472:11)
    at ManagedPromise.invokeCallback_ (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:1379:14)
    at TaskQueue.execute_ (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2913:14)
    at TaskQueue.executeNext_ (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2896:21)
    at asyncRun (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:2820:25)
    at /home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (internal/process/next_tick.js:103:7)
From: Task: WebDriver.createSession()
    at Function.createSession (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/lib/webdriver.js:329:24)
    at Builder.build (/home/aslevy/repos/angular-phonecat/node_modules/selenium-webdriver/builder.js:458:24)
    at Local.DriverProvider.getNewDriver (/home/aslevy/repos/angular-phonecat/node_modules/protractor/built/driverProviders/driverProvider.js:37:33)
    at Runner.createBrowser (/home/aslevy/repos/angular-phonecat/node_modules/protractor/built/runner.js:198:43)
    at /home/aslevy/repos/angular-phonecat/node_modules/protractor/built/runner.js:277:30
    at _fulfilled (/home/aslevy/repos/angular-phonecat/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/home/aslevy/repos/angular-phonecat/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/home/aslevy/repos/angular-phonecat/node_modules/q/q.js:796:13)
    at /home/aslevy/repos/angular-phonecat/node_modules/q/q.js:604:44
    at runSingle (/home/aslevy/repos/angular-phonecat/node_modules/q/q.js:137:13)
[12:39:42] E/launcher - Process exited with error code 199

npm ERR! Linux 4.8.4-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "protractor"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 199
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/aslevy/repos/angular-phonecat/npm-debug.log
```

Here is the output from npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'protractor' ]
2 info using npm@3.10.9
3 info using node@v6.9.1
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/aslevy/repos/angular-phonecat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /home/aslevy/repos/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/aslevy/repos/angular-phonecat/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /home/aslevy/repos/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 199  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 199
18 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /home/aslevy/repos/angular-phonecat
21 error Linux 4.8.4-1-ARCH
22 error argv "/usr/bin/node" "/usr/bin/npm" "run" "protractor"
23 error node v6.9.1
24 error npm  v3.10.9
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 199
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
```

I am running in Chromium on Arch Linux. Everything is up to date.
Thank you

**Comment by gkalpak** [comment]
What version of protractor have you install? I.e. what does `npm list protractor` (from inside the project directory) print?

**Comment by AdamSLevy** [comment]
Protractor version 4.0.10

```
$ npm list protractor
angular-phonecat@0.0.0 /home/aslevy/repos/angular-phonecat
`-- protractor@4.0.10
```

**Comment by gkalpak** [comment]
It seems that Selenium can't find the chrome/chromium binary. Can you verify that `/usr/bin/google-chrome` is a symlink to the actual Chromium binary (as discribed [here][1])?

[1]: https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver#requirements

**Comment by emprit1988** [comment]
Running into the same issue, with above-mentioned logs. Launched chrome and chromium browser using  symlink '/usr/bin/google-chrome' and '/usr/bin/chromium-browser' successfully, but still no luck with protractor. I'm running them in ubuntu 14.04.

Here is my npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.14.12
3 info using node@v4.2.4
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
10 verbose stack Exit status 199
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:818:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd /home/emprit/nodework/phonecatfull/angular-phonecat
13 error Linux 3.19.0-30-generic
14 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
15 error node v4.2.4
16 error npm  v2.14.12
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 error Exit status 199
19 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     protractor e2e-tests/protractor.conf.js
19 error You can get their info via:
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by gkalpak** [comment]
I can't reproduce the error using the same versions of node/npm/protractor (on Ubuntu 16.04) 😞
I don't know how to help further. In any case, this is more likely a Protractor issue, rather than phoencat-specific. You should probably open an issue over there.

**Comment by crashspringfield** [comment]
I'm getting the same issue Mint 17.4

**Comment by OStefani** [comment]
I have the same error 199
Here is my debug-log
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Olga/angular-phonecat/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /Users/Olga/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Olga/angular-phonecat/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /Users/Olga/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 199  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 199
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /Users/Olga/angular-phonecat
21 error Darwin 15.6.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
23 error node v6.9.1
24 error npm  v3.10.8
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 199
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]
`

**Comment by rohit-glassbeam** [comment]
Having same problem in jenkins. Its irritating.

**Comment by gclayburg** [comment]
I ran into the same issue.  It seems to be something related to protractor being able to start chrome.  In my case, I am using CentOS 6.8. and chrome 54.0.  chrome isn't officially supported by google on this platform, but I made it work anyway using the tools here  [https://chrome.richardlloyd.org.uk/](url)

Even though Chrome is working fine on my system, it fails when running through protractor.  For the time being, I am working around this problem by switching out to firefox with this `e2e-tests/protractor.conf.js` file:

```
exports.config = {

  allScriptsTimeout: 11000,

  specs: [
    '*.js'
  ],

  capabilities: {
    'browserName': 'firefox'
  },

  baseUrl: 'http://localhost:8000/',

  framework: 'jasmine',

  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }

};

```

**Comment by OStefani** [comment]
It didn't help me, I still see the error 199

**Comment by gkalpak** [comment]
I am afraid there is not much we can do without a reproduction. In any case, this doesn't sound like an issue specific to phonecat. I would try asking for help on the protractor support channels.

**Comment by gclayburg** [comment]
Ok, I went through a bunch of hoops to figure out why it was failing for me when using chrome.  What ended up helping me the most was to change the protractor config to use a selenium server running separately instead of the default config that is part of angular-phonecat.  So in one window I ran this:

`$ webdriver-manager start`

And in another window run protractor directly against a modified config file:

`$ protractor e2e-tests/protractor.conf-standalone-selenium.js`

The config file is:
```
$ cat e2e-tests/protractor.conf-standalone-selenium.js
//jshint strict: false
exports.config = {

  allScriptsTimeout: 11000,

  specs: [
    '*.js'
  ],

  capabilities: {
    'browserName': 'chrome'
  },

  baseUrl: 'http://localhost:8000/',
  seleniumAddress: 'http://localhost:4444/wd/hub',

  framework: 'jasmine',

  jasmineNodeOpts: {
    defaultTimeoutInterval: 30000
  }

};
```

The window where you run webdriver-manager should show more meaningful errors

**Comment by rohit-glassbeam** [comment]
@gclayburg are you satrting chrome in a headless environment(Xvfb) ? Also are you using jenkins to run this e2e ?

**Comment by gclayburg** [comment]
@rohit-glassbeam  No, I haven't tried that yet.  My issue was related to running newer chrome browsers on CentOS 6.  In my case I saw several errors in the webdriver-manager window like this:

```
/home/gclaybur/tools/node-v4.4.4-linux-x64/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by /home/gclaybur/tools/node-v4.4.4-linux-x64/lib/node_modules/protractor/node_modules/webdriver-manager/selenium/chromedriver_2.25)
```

With this information, I was able to make webdriver-manager work with this LD_LIBRARY_PATH:

```
export LD_LIBRARY_PATH=/opt/google/chrome/lib:/usr/lib
```

Running webdriver-manager this way was the only way to see the real reason behind the 199 error that I have found.  If you use the protractor defaults for this tutorial, it will try to directly start webdriver-manager, but any error messages are hidden.

**Comment by gauravk-optimus** [comment]
This issue will be fixed after updating the webdriver manager using 'webdriver-manager update' command

**Comment by Procelius** [comment]
@gauravk-optimus 
Your advice fixed my problem with protractor error code 199.
Thank you!

**Comment by joaogomes44033** [comment]
I had the same problem on windows.
Fixed with:

`npm install webdriver-manager`

**Comment by en2455926** [comment]
Hi,
Fixed with: 
>npm audit 
given information 
== npm audit security report ===
and followed npm installs:
>npm install --save-dev karma@2.0.4
>npm install --save-dev protractor@5.3.2
>npm install --save-dev http-server@0.11.1
resolved (10+2+1)  vulnerability
