### ISSUE TITLE
http://localhost:8000/index.html 404 error

### ISSUE THREAD

**Issue by DocGreenRob** [angular/angular-phonecat#382]
I have an Angular 1.5 app that is similar to the angular-phone-cat app and it works fine.  Now, when I implement my unit test, I load the appropriate files needed in the karma.conf file and then start the node server with `npm start`, then I go to my browser and access **http://localhost:8000** and I can see the directory structure of the specified directories in the karma.conf but I cannot browse to the index.html file, when I try I get a 404 error.

Conversely, when I do the same thing with the angular-phonecat app I am able to view the index.html file when I browse to  **http://localhost:8000**.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
