### ISSUE TITLE
Failed at the angular-phonecat protractor script 'protractor e2e-tests/protractor.conf.js'.

### ISSUE THREAD

**Issue by RijkJ** [angular/angular-phonecat#386]
"Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\jojo_\Documents\angular-phonecat\npm-debug.log"

I do have the latest versions of node and npm. Additionally, this npm-debug log is nowhere to be found.

**Comment by gkalpak** [comment]
We can't really help without more info (e.g. the complete error message, node/npm/protractor versions etc).

**Comment by PMas551** [comment]
RijkJ, I had to do a few things to get the Protractor tests working. I'm running Windows 7.

You could try some / all of these:

Run your command line windows with administrator rights.

Install the Java SDK: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Download the latest Chrome webdriver: https://sites.google.com/a/chromium.org/chromedriver/downloads

Unzip and drop the exe into angular-phonecat\node_modules\protractor\selenium

Download the latest Selenium Standalone Server: http://www.seleniumhq.org/download/

Drop the jar file into angular-phonecat\node_modules\protractor\selenium

Update the "webdriverVersions" section of the package.json file in angular-phonecat\node_modules\protractor - update the "selenium" value with your new version number.

Set the browsername: chrome value to directConnect: true, (don't forget the comma) in the file protractor-conf.js in angular-phonecat\test

hth

**Comment by gkalpak** [comment]
I just wanted to point out that some of these steps are unrelated:

- Protractor will automatically download recent versions of ChromeDrier and Selenium.
- When using `directConnect: true`, you shouldn't use Selenium, since protractor is connecting directly to the browser.

**Comment by jrubarthlay** [comment]
I received the same error.
$ node --version
v6.9.5
$ npm --version
3.10.10

[npm-debug-20170207T1020.zip](https://github.com/angular/angular-phonecat/files/758467/npm-debug-20170207T1020.zip)

I'll try some of PMas551's recommendations and report back.

**Comment by Jedeu** [comment]
Just a note that for all Mac users that an easier solution than @PMas551 is to:

`brew cask install java`

A good explanation of why this happens is found in this StackOverflow [link](http://stackoverflow.com/questions/34201990/unsupported-major-minor-version-on-mac-os-x-el-capitan)

**Comment by Sergey1983** [comment]
I have the same mistake as above:
![460f900195](https://cloud.githubusercontent.com/assets/17278829/25101781/463e3d1e-23be-11e7-93c5-e6ee682884d7.jpg)
and, by the way, I don't have "/Users/sergeyfomin/code/angular-phonecat/npm-debug.log" file on my computer:
![27a8378290](https://cloud.githubusercontent.com/assets/17278829/25101871/a0e0d8a8-23be-11e7-927e-4e05d0c8c149.jpg)

**Comment by gkalpak** [comment]
Are you serving the file (e.g. running `npm start` on a different terminal) before running protractor?

**Comment by kaibrabo** [comment]
I'm having the same errors that have been addressed on these threads. 

Im current on: 

Kainoas-MacBook-Pro:angular-phonecat Kainoa$ npm --version
3.10.10
Kainoas-MacBook-Pro:angular-phonecat Kainoa$ node --version
v6.10.2

This error popped up after input:

`npm run protractor`

<img width="719" alt="screen shot 2017-04-27 at 18 38 32" src="https://cloud.githubusercontent.com/assets/24517714/25510971/c6b46c36-2b78-11e7-9d6f-80916db97f40.png">

**Comment by kinospro** [comment]
I have pretty the same problem.
windows 7,
npm --version: 5.0.4,
node --version: 6.11.0.
Terminal text:
`npm run protractor

> angular-phonecat@0.0.0 preprotractor C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
> npm run update-webdriver

npm WARN invalid config loglevel="notice"

> angular-phonecat@0.0.0 preupdate-webdriver C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
> npm install

npm WARN invalid config loglevel="notice"

> angular-phonecat@0.0.0 postinstall C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
> bower install

up to date in 3.927s

> angular-phonecat@0.0.0 update-webdriver C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
> webdriver-manager update

[13:05:46] I/update - chromedriver: file exists C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.26win32.zi
p
[13:05:46] I/update - chromedriver: unzipping chromedriver_2.26win32.zip
[13:05:47] I/update - chromedriver: v2.26 up to date
[13:05:47] I/update - selenium standalone: file exists C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-st
andalone-2.53.1.jar
[13:05:47] I/update - selenium standalone: v2.53.1 up to date
[13:05:48] I/update - geckodriver: file exists C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.11.1-win64.
zip
[13:05:48] I/update - geckodriver: unzipping geckodriver-v0.11.1-win64.zip
[13:05:48] I/update - geckodriver: vv0.11.1 up to date

> angular-phonecat@0.0.0 protractor C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
> protractor e2e-tests/protractor.conf.js

[13:05:48] I/local - Starting selenium standalone server...
[13:05:49] I/launcher - Running 1 instances of WebDriver
[13:05:49] E/launcher - spawn java ENOENT
[13:05:49] E/launcher - Error: spawn java ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[13:05:49] E/launcher - Process exited with error code 199
npm ERR! code ELIFECYCLE
npm ERR! errno 199
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 199
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\alexey\AppData\Roaming\npm-cache\_logs\2017-07-19T10_05_49_230Z-debug.log`

and content of log file:
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\alexey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@5.0.4
3 info using node@v6.11.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: C:\Users\alexey\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Git\bin\;C:\Program Files\doxygen\bin;C:\Users\alexey\AppData\Roaming\npm;C:\Program Files\Git\bin\git.exe;C:\xampp\php\php.exe;C:\xamp\htdocs\yii-framework\;C:\Program Files (x86)\Graphviz2.38\bin\dot.exe
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '/d /s /c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: C:\Users\alexey\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\;C:\Program Files (x86)\MySQL\MySQL Fabric 1.5 & MySQL Utilities 1.5\Doctrine extensions for PHP\;C:\Windows\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files\Git\bin\;C:\Program Files\doxygen\bin;C:\Users\alexey\AppData\Roaming\npm;C:\Program Files\Git\bin\git.exe;C:\xampp\php\php.exe;C:\xamp\htdocs\yii-framework\;C:\Program Files (x86)\Graphviz2.38\bin\dot.exe
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '/d /s /c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 199  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 199
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\alexey\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\alexey\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:891:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd C:\Users\alexey\WebstormProjects\personal_initiatives\angular\angular-phonecat
21 verbose Windows_NT 6.1.7601
22 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alexey\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
23 verbose node v6.11.0
24 verbose npm  v5.0.4
25 error code ELIFECYCLE
26 error errno 199
27 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
27 error Exit status 199
28 error Failed at the angular-phonecat@0.0.0 protractor script.
28 error This is probably not a problem with npm. There is likely additional logging output above.
29 verbose exit [ 199, true ]
`

**Comment by gkalpak** [comment]
It seems like java is either not installed or not on your path. Please make sure you have set up your environment as instructed [here][1]

[1]: https://docs.angularjs.org/tutorial#environment-setup
