### ISSUE TITLE
Installing bower

### ISSUE THREAD

**Issue by graynwhite** [angular/angular-phonecat#389]
abending at bower install 

Your environment has been set up for using Node.js 6.9.2 (x64) and npm.

C:\Users\peggyjoThree>cd angularjs/angular-phonecat

C:\Users\peggyjoThree\angularjs\angular-phonecat>node --version
v6.9.2

C:\Users\peggyjoThree\angularjs\angular-phonecat>apt-get install nodejs-legacy npm
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\peggyjoThree\angularjs\angular-phonecat>nodejs --version
'nodejs' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\peggyjoThree\angularjs\angular-phonecat>npm --version
3.10.9

C:\Users\peggyjoThree\angularjs\angular-phonecat>apt-get install nodejs-legacy npm
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\peggyjoThree\angularjs\angular-phonecat>npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[                ..] / build:angular-phonecat: sill install runPostinstallTopLevelLifecyclesfor postinstall, continuingll, continuingngntinuingimatchexpand-rangere-js-353050d5\node_modules
> angular-phonecat@0.0.0 postinstall C:\Users\peggyjoThree\angularjs\angular-phonecat
> bower install

bower angular-mocks#1.5.x       ENOGIT git is not installed or not in the PATH

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\peggyjoThree\angularjs\angular-phonecat\npm-debug.log

C:\Users\peggyjoThree\angularjs\angular-phonecat>npm bugs angular-phonecat

C:\Users\peggyjoThree\angularjs\angular-phonecat>

**Comment by graynwhite** [comment]
Updated to minimatch 3.0.2
and then ran:
Your environment has been set up for using Node.js 6.9.2 (x64) and npm.

C:\Users\peggyjoThree>cd angularjs/angular-phonecat

C:\Users\peggyjoThree\angularjs\angular-phonecat>node --version
v6.9.2

C:\Users\peggyjoThree\angularjs\angular-phonecat>apt-get install nodejs-legacy npm
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\peggyjoThree\angularjs\angular-phonecat>nodejs --version
'nodejs' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\peggyjoThree\angularjs\angular-phonecat>npm --version
3.10.9

C:\Users\peggyjoThree\angularjs\angular-phonecat>apt-get install nodejs-legacy npm
'apt-get' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\peggyjoThree\angularjs\angular-phonecat>npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[                ..] / build:angular-phonecat: sill install runPostinstallTopLevelLifecyclesfor postinstall, continuingll, continuingngntinuingimatchexpand-rangere-js-353050d5\node_modules
> angular-phonecat@0.0.0 postinstall C:\Users\peggyjoThree\angularjs\angular-phonecat
> bower install

bower angular-mocks#1.5.x       ENOGIT git is not installed or not in the PATH

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\peggyjoThree\angularjs\angular-phonecat\npm-debug.log

C:\Users\peggyjoThree\angularjs\angular-phonecat>npm bugs angular-phonecat

C:\Users\peggyjoThree\angularjs\angular-phonecat>npm install

> angular-phonecat@0.0.0 postinstall C:\Users\peggyjoThree\angularjs\angular-phonecat
> bower install

bower angular-mocks#1.5.x       ENOGIT git is not installed or not in the PATH

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\peggyjoThree\angularjs\angular-phonecat\npm-debug.log

C:\Users\peggyjoThree\angularjs\angular-phonecat>

**Comment by gkalpak** [comment]
You are trying to use some commands that (a) unnecessary (e.g. trying to install the already installed node and npm) and (b) for Linux, not Windows (e.g. `apt-get`).

##
Based on the logs above, the real problem seems to be that:

> git is not installed or not in the PATH

So, make sure you have `git` installed and that it is available in the PATH.

##
Closing, since the issues are not related to `angular-phonecat`.
