### ISSUE TITLE
Can't get pass the tests

### ISSUE THREAD

**Issue by nagano564** [angular/angular-phonecat#393]
I don't understand what is going on

after running 

npm run protractor

![screen shot 2017-01-26 at 5 04 24 pm](https://cloud.githubusercontent.com/assets/21698552/22352431/20890a7c-e3ea-11e6-9043-6ae69951e46a.png)

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.10
3 info using node@v6.9.4
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Julie713/bloc/angular-phonecat/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: /Users/Julie713/bloc/angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '-c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/Julie713/bloc/angular-phonecat/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: /Users/Julie713/bloc/angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '-c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 1  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 1
18 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd /Users/Julie713/bloc/angular-phonecat
21 error Darwin 15.6.0
22 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
23 error node v6.9.4
24 error npm  v3.10.10
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 1
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

**Comment by gkalpak** [comment]
Do you get another error message before that?
Have you started the webserver before running `npm run protractor`?

**Comment by nagano564** [comment]
this message repeats over and over

**Comment by gkalpak** [comment]
What do you mean? What message?
This doesn't seem to answer my previous comment 😕

**Comment by nagano564** [comment]
you asked if I had any error messages before
the two messages in the picture.

window.angular is undefined.
and

  Failed: Error while running testForAngular: asynchronous script timeout:
result was not received in 11 seconds

the webserver mean? am I going to the localhost website before I run  npm
run protractor?

**Comment by gkalpak** [comment]
As explained in the tutorial, you need to start the webserver before running protractor:

> **Note:** In order for protractor to access and run tests against your application, it must be served via a web server. In a different terminal/command line window, run npm start to fire up the web server.

```
# In terminal window 1
npm start

# In terminal window 2
npm run protractor
```

**Comment by nagano564** [comment]
thanks

**Comment by gkalpak** [comment]
N
