### ISSUE TITLE
one fdescribe fails causes rest of the tests to skip in Protractor Jasmine in Windows 10

### ISSUE THREAD

**Issue by premkumarvarathan** [angular/angular-phonecat#394]
We are trying to run the Protactor jasmine Testcase in Windows 10 machine.
 
In our suite i have 6 Testcase. If 3rd test case got failed rest of testcases are skipped automatically and executions stops.

We have Tried modifying the configuration file. But still rest of the cases are getting skipped.

1. In Config file we have added the below list of configuration keywords
stopSpecOnExpectationFailure: false

onPrepare: function() {
  		var failFast = require('jasmine-fail-fast');
  		jasmine.getEnv().addReporter(failFast.init());
		}

afterLaunch: function() {
		failFast.clean(); // Cleans up the "fail file" 
		} 

jasmineNodeOpts: {
		...
		realtimeFailure: true
		},

2. And also we have installed the following npm modules and included the below sentences. Still we are getting the same skip error.
	1. Jasmine-bail-fast
	2. Protractor-fail-fast

require('jasmine-bail-fast');
jasmine.getEnv().bailFast();

Please help us to resolve this issue. 

-Prem

**Comment by gkalpak** [comment]
This sounds like a general support question, not directly related to the tutorial. Please, use one of the [appropriate support channels](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question) for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!
