### ISSUE TITLE
Uncaught Error: [$injector:modulerr] Failed to instantiate module siteApplication due to: Error: [$injector:nomod] Module 'siteApplication' is not available! You either misspelled the module name or forgot to load it. 

### ISSUE THREAD

**Issue by sudhirojha10** [angular/angular-phonecat#396]
How i solve the above problem.Please help guys.

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
