### ISSUE TITLE
use angular material, material design lite or materialize.css for styles

### ISSUE THREAD

**Issue by NilsHolger** [angular/angular-phonecat#397]
i suggest replacing the css framework with either:
1. https://material.angularjs.org/latest/
2. https://getmdl.io/
3. http://materializecss.com/
they are all based on material design and we are 2017, we progress. we want to provide the new and old angular developers with a delightful experience and the newest technologies, right? apart from that these are all google technologies and synergies are created which is beneficial to mutual growth. all things aside the quality of the material design css stands out.

**Comment by gkalpak** [comment]
This is not a good idea imho for the following reason:

This is not a generic "web-development with AngularJS" tutorial. It is specifically focused on AngularJS. Thus, it should contain the minimum non-AngularJS concepts/tools necessary to teach people how to start using AngularJS. 

##
There are probably two kinds of people that the tutorial targets: 

1. People that are beginners in web-dev in general.
2. People that might be experienced in web-dev and trying to learn AngularJS.

The second group of people would be familiar with CSS frameworks and would be able to apply them on top of AngularJS. So, while using a CSS framework would not make the tutorial more difficult for them to follow, omitting wouldn't hurt them either.
The first group of people, having to learn a CSS framework along with AngularJS (and web-dev in general) and having to read through more bloated templates etc, would have a much harder time imo.

Just m2c.

##
What would be interesting, is maybe having an AngularJS Material tutorial (if there is not one already) that assumes you know the basics of AngularJS and starts from there.
