### ISSUE TITLE
Failed at the angular-phonecat@0.0.0 start script 'http-server ./app -a localhost -p 8000 -c-1

### ISSUE THREAD

**Issue by ekim1394** [angular/angular-phonecat#399]
Trying to run the tutorial on AngularJS.

I have the latest version of node.js and npm installed.

**Comment by gkalpak** [comment]
We can't help much without more info. For example, what is the exact error message?

**Comment by adrBoy** [comment]
The web server is configured to use port 8000. If the port is already in use (for example by another instance of a running web server) you will get an EADDRINUSE error. Make sure the port is available, before running npm start.

**Comment by lazyManLearn** [comment]
change port
