### ISSUE TITLE
Step 2 PhoneListController is not defined error

### ISSUE THREAD

**Issue by leolandotan** [angular/angular-phonecat#405]
Im getting this error when I run `npm test`:
```
PhoneListController should create a `phones` model with 3 phones FAILED
        ReferenceError: $scope is not defined
        @/Users/leotan/Documents/Tutorials/angular-phonecat/app/app.spec.js:9:52
        invoke@/Users/leotan/Documents/Tutorials/angular-phonecat/app/bower_components/angular/angular.js:4771:16
        WorkFn@/Users/leotan/Documents/Tutorials/angular-phonecat/app/bower_components/angular-mocks/angular-mocks.js:3130:11
        angular.mock.inject@/Users/leotan/Documents/Tutorials/angular-phonecat/app/bower_components/angular-mocks/angular-mocks.js:3093:25
        @/Users/leotan/Documents/Tutorials/angular-phonecat/app/app.spec.js:7:54
        @/Users/leotan/Documents/Tutorials/angular-phonecat/app/app.spec.js:3:1
```

To fix this, I based my fix mostly on [this article](http://www.bradoncode.com/blog/2015/05/19/karma-angularjs-testing) and come up with my final code:
```
'use strict';

describe('PhoneListController', function () {
  beforeEach(module('phonecatApp'));

  var $controller;

  beforeEach(inject(function(_$controller_) {
    $controller = _$controller_;
  }));

  it('should create a `phones` model with 3 phones', function() {
    var $scope = {};
    var controller = $controller('PhoneListController', { $scope: $scope });
    
    expect($scope.phones.length).toBe(3);
  });
});
```

Any ideas on why the AngularJS step 2 Karma test code doesn't work or is this really the "supposed to be" code?

Thanks!

**Comment by gkalpak** [comment]
I don't see how your code is any different than what we have on [step 2][1]. Also, the automated tests run on every step pass, so this works as expected afaict. Closing since this is not actionable, but feel free to continue the discussion below.

[1]: https://github.com/angular/angular-phonecat/blob/step-2/app/app.spec.js

**Comment by cfdude** [comment]
I too am getting the same error when trying to run the test

Firefox 65.0.0 (Mac OS X 10.14.0) PhoneListController should create a 'phones' model with 3 phones FAILED
	Error: [$controller:ctrlreg] The controller with the name 'PhoneListController' is not registered.
	https://errors.angularjs.org/1.7.5/$controller/ctrlreg?p0=PhoneListController
	minErr/<@lib/angular/angular.js:138:12
	$controller@lib/angular/angular.js:11646:17
	createControllerDecorator/angular.mock.$ControllerDecorator</<@/Users/robsherman/Servers/angular-phonecat/node_modules/angular-mocks/angular-mocks.js:2555:14
	@app.spec.js:6:20
	invoke@lib/angular/angular.js:5122:16
	WorkFn@/Users/robsherman/Servers/angular-phonecat/node_modules/angular-mocks/angular-mocks.js:3459:11
	<Jasmine>
	angular.mock.inject@/Users/robsherman/Servers/angular-phonecat/node_modules/angular-mocks/angular-mocks.js:3422:25
	@app.spec.js:4:56
	<Jasmine>
	@app.spec.js:1:1
