### ISSUE TITLE
No versions found in https://github.com/angular/bower-angular.git

### ISSUE THREAD

**Issue by koolkeshav** [angular/angular-phonecat#408]
When I am trying to run the command "bower install", it is giving below error

Additional error details:
No versions found in https://github.com/twbs/bootstrap.git
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\keshavrastogi\AppData\Roaming\npm-cache\_logs\2017-04-13T07_32_25_433Z-debug.log

**Comment by gkalpak** [comment]
This sounds like a temporary network issue. Or maybe a proxy configuration issue.
I am going to close this, but feel free to continue the discussion below if the problem persists.
