### ISSUE TITLE
git checkout step-? doesn't work, please help

### ISSUE THREAD

**Issue by chinesescorpions** [angular/angular-phonecat#410]
In Node command line, I type "git checkout step?", but a error message is returned that "fatal: Not a git repository...". What's wrong? pls help, thanks

**Comment by gkalpak** [comment]
This sounds like a general support question. Please, use one of the [appropriate support channels][1] for these types of questions.
<sub>GitHub issues are reserved for bug reports and feature requests.</sub>

Thx!

##
That said, it sounds like you are not executing the command from inside the directory that you have cloned the repo (or you haven't cloned it at all). Make sure you follow the instructions [here][2].

[1]: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
[2]: https://docs.angularjs.org/tutorial
