### ISSUE TITLE
This fails my system: http-server ./app -a localhost -p 8000 -c-1

### ISSUE THREAD

**Issue by sunthar** [angular/angular-phonecat#411]
> angular-phonecat@0.0.0 prestart /Users/suntharpremakamur/Documents/angular/angular-phonecat
> npm install

npm WARN lifecycle angular-phonecat@0.0.0~postinstall: cannot run in wd %s %s (wd=%s) angular-phonecat@0.0.0 bower install /Users/suntharpremakamur/Documents/angular/angular-phonecat

> angular-phonecat@0.0.0 start /Users/suntharpremakamur/Documents/angular/angular-phonecat
> http-server ./app -a localhost -p 8000 -c-1

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at Server._listen2 (net.js:1258:14)
    at listen (net.js:1294:10)
    at net.js:1404:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

**Comment by then815** [comment]
I was having the same issue and couldn't get any answers on how to actually fix the issue, but I opened up the package.json file and changed the port number from 8000 to 8888.  It was on line 22 for me.  Hope that helps for you too.

**Comment by Yogeshwar235** [comment]
I found the node processes were not ending after the server was terminated.
