### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by ethereal-sandeep** [angular/angular-phonecat#412]
Please add code for generating snapshot files for SEO as well.

**Comment by gkalpak** [comment]
Thx for the suggestion, but this is outside the scope of this basic tutorial.

**Comment by ethereal-sandeep** [comment]
It looks like this tutorial is incomplete without showing a scope for seo. Isn't it.

**Comment by gkalpak** [comment]
Not really. SEO in SPAs is not a topic for beginners. This is supposed to be an introduction to AngularJS, showing the basic concepts to absolute beginners. It can't cover everything. SEO is a topic for a more specialized tutorial imo.
