### ISSUE TITLE
npm install fails on 'bower install'

### ISSUE THREAD

**Issue by eboninger** [angular/angular-phonecat#413]
I have the latest versions of both npm and node installed on my computer.  Still getting the follow output after running npm install:

npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> angular-phonecat@0.0.0 postinstall C:\Users\eli.boninger\Documents\angular-practice\angular-phonecat
> bower install

bower angular-mocks#1.5.x       ENOGIT git is not installed or not in the PATH

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\eli.boninger\Documents\angular-practice\angular-phonecat\npm-debug.log

Thanks for any help!

**Comment by eboninger** [comment]
after looking at previous posts I'm finding that this seems to be a git issue - I get the message "git is not installed or not in the PATH"

will do more digging tomorrow but seems very fixable

**Comment by gkalpak** [comment]
You are right. That is exactly the problem. You need `git` to be installed and on your PATH.
Closing, because this is not an issue with the tutorial itself. Make sure you have set up your environment as instructed [here][1].

[1]: https://docs.angularjs.org/tutorial#environment-setup
