### ISSUE TITLE
is ngSrc directive useless?

### ISSUE THREAD

**Issue by kinospro** [angular/angular-phonecat#415]
I have followed the instruction at https://docs.angularjs.org/tutorial/step_08. And I've found out that there is no difference between 'ng-src' and 'src'. They both do the same - just show the phone image. I also tried to restart app with simple src and ctrl+f5 - no difference at all.

My config: 
windows 7,
npm --version: 5.0.4,
node --version: 6.11.0.

**Comment by gkalpak** [comment]
The difference is explained [here][1]. The end result will be the same, but meanwhile `src` will result in unnecessary requests.

[1]: https://docs.angularjs.org/api/ng/directive/ngSrc
