### ISSUE TITLE
Problem with $ npm install

### ISSUE THREAD

**Issue by cherganov** [angular/angular-phonecat#424]
Hi guys this is my problem : 

USER@USER-PC MINGW64 ~/angular-phonecat (master)
$ npm install

> angular-phonecat@0.0.0 postinstall C:\Users\USER\angular-phonecat
> bower install

bower angular#1.5.x          ENOTFOUND Request to https://registry.bower.io/pack                                                                                                                ages/angular failed: getaddrinfo ENOTFOUND registry.bower.io registry.bower.io:4                                                                                                                43

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch                                                                                                                okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@                                                                                                                1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}                                                                                                                )
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\                                                                                                                node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'                                                                                                                .
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat pack                                                                                                                age,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\USER\angular-phonecat\npm-debug.log

I hope you know what that is :) Thank you :)

**Comment by gkalpak** [comment]
It says that it couldn't find https://registry.bower.io/packages/angular, but it clearly exists. It could be a temporary issue or configurtion issues on your local environment (e.g. some DNS or proxy issue).

Unfortunately, there is not much we can do, I'm afraid 😞
