### ISSUE TITLE
An Issue on components' templateUrl

### ISSUE THREAD

**Issue by front2psy** [angular/angular-phonecat#427]
<img width="409" alt="res" src="https://user-images.githubusercontent.com/26113624/34914374-9177d97a-f94c-11e7-93b0-531f65240ce9.png">

<img width="914" alt="code" src="https://user-images.githubusercontent.com/26113624/34914353-123c0564-f94c-11e7-97d8-d82f52e2767e.png">

As you can see, the templateUrl setting in my component did not work. Not even report any errors. Did I miss something ?

**Comment by gkalpak** [comment]
> As you can see

I can't see anything :confused:
Make sure you follow the instructions correctly.
