### ISSUE TITLE
constantly Bower install is failing with ssl issue

### ISSUE THREAD

**Issue by karunakant** [angular/angular-phonecat#428]
Bower install is constantly failing for One or the package from github.

bower install --config.storage.packages=.bower-cache --config.tmp=.bower-tmp --verbose

bower ismobilejs#~0.4.0                        ECMDERR Failed to execute "git clone https://github.com/kaimallea/isMobile.git -b 0.4.1 --progress . --depth 1", exit code of #128 Cloning into '.'... fatal: unable to access 'https://github.com/kaimallea/isMobile.git/': Unknown SSL protocol error in connection to github.com:443

We already done the following things
 gitconfig file has the following entry there

[http]
	sslCAinfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
	sslBackend = openssl
	sslverify = false

[url "https://"]
	insteadOf = git://
Also version for all are latest

**Comment by karunakant** [comment]
The issue got resolved with new version of NPM

**Comment by thanhtran2910** [comment]
Hi @karunakant ,
Could you please tell me which version you had used and which is new version? I has the same issue.
Thanks
