### ISSUE TITLE
Tutorial steps/chapters not corresponding to tutorial description/Live Demo/branches

### ISSUE THREAD

**Issue by pmyszkier** [angular/angular-phonecat#432]
**See for example: https://code.angularjs.org/1.3.15/docs/tutorial** 
**Tutorial: 3** - Filtering Repeaters ( https://code.angularjs.org/1.3.15/docs/tutorial/step_03 ) says: "The app now has a search box" . But in Live Demo ( http://angular.github.io/angular-phonecat/step-3/app/ ) there is no search box . Branch step-3 (`git checkout -f step-3`) is wrong for this chapter 3.
**Tutorial: 4** - Two-way Data Binding ( https://code.angularjs.org/1.3.15/docs/tutorial/step_04 ) says: "In addition to the search box, the app displays a drop down menu..." . But in Live Demo ( http://angular.github.io/angular-phonecat/step-4/app/ ) there is no dropdown menu and no search box . Branch step-4 (`git checkout -f step-4`) is wrong for this chapter 4.
**Tutorial: 5** - XHRs & Dependency Injection ( https://code.angularjs.org/1.3.15/docs/tutorial/step_05 ) says: "There is now a list of 20 phones..." . But in Live Demo ( http://angular.github.io/angular-phonecat/step-5/app/ ) there is a list of 3 phones, not 20 phones . Branch step-5 (git checkout -f step-5) is wrong for this chapter 5.
**Tutorial: 6** - Templating Links & Images( https://code.angularjs.org/1.3.15/docs/tutorial/step_06 ) says: "There are now links and images of the phones in the list." . But in Live Demo ( http://angular.github.io/angular-phonecat/step-6/app/ ) there is no links and images of phones . Branch step-6 (git checkout -f step-6) is wrong for this chapter 6.
**etc...**
Can You fix it?

**Comment by gkalpak** [comment]
Version 1.3.x is very old and not maintained any more. You should follow the latest version if you are learning AngularJS. The latest code in `angular-phonecat` corresponds to the latest version of the tutorial (which happens to be the same for 1.5.x and 1.6.x), but there is also an older version maintained for 1.4.x (so you could follow the 1.4.x tutorial too, but strongly recommend to use the latest).
