### ISSUE TITLE
Error when running npm install at bower install

### ISSUE THREAD

**Issue by Luke791** [angular/angular-phonecat#434]
I'm following AngularJS tutorial (https://docs.angularjs.org/tutorial) and running npm install I get the following error:

bower install

bower ENOTFOUND     Request to https://registry.bower.io/packages/angular failed
: getaddrinfo ENOTFOUND registry.bower.io registry.bower.io:443

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 postinstall script 'bower install'
.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat pack
age,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wsvi386\angularProjects\angular-phonecat\npm-debug.log

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 prestart: `npm install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 prestart script 'npm install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat pack
age,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\wsvi386\angularProjects\angular-phonecat\npm-debug.log

What is it caused by and how to solve it?

**Comment by Luke791** [comment]
Found the reason: proxy is blocking git application.

bower ECMDERR       Failed to execute "git ls-remote --tags --heads https://git
ub.com/angular/bower-angular-animate.git", exit code of #128 fatal: unable to a
cess 'https://github.com/angular/bower-angular-animate.git/': Received HTTP cod
 407 from proxy after CONNECT

Absurd how you can't follow the tutorial if you can't run git, uh? This is an Angular tutorial not a git tutorial right?

**Comment by gkalpak** [comment]
Yes, this is an AngularJS tutorial, but (as most web dev tutorials) has prerequisites. This one is specifically using git. We have a [Common Issues][1] section on the tutorial that might help you get your environment set up.

[1]: https://docs.angularjs.org/tutorial#common-issues

**Comment by Luke791** [comment]
If you have no control over which applications are blocked by the proxy there is no way the environment can be set up.

**Comment by gkalpak** [comment]
Sorry to hear that. Fortunately, even if you don't have access to a computer with the ability to clone github repositories, you can at least still follow the tutorial. You just won't be able to automatically check out the code for each step (but this is not necessary to follow the tutorial).
