### ISSUE TITLE
Unable to push the files into github

### ISSUE THREAD

**Issue by Nik118** [angular/angular-phonecat#435]
unable to access 'https://github.com/Nik118/Blog.git/': OpenSSL SSL_conne                                                                                                                                  ct: SSL_ERROR_SYSCALL in connection to github.com:443

I am getting this error while I am trying to push a file into github repository...Please help me in solving this issue.

**Comment by gkalpak** [comment]
This issue doesn't sound related to this tutorial or AngularJS in general.
