### ISSUE TITLE
Failed to npm run protractor 

### ISSUE THREAD

**Issue by Clickys** [angular/angular-phonecat#441]
Greetings, 

I have downgraded the node version to v.7.0.0 because i read that protractor had some issues with node v8+ . 

$ npm version
{ 'angular-phonecat': '0.0.0',
  npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '51',
  node: '7.0.0',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.4.500.36',
  zlib: '1.2.8' }

I failed to ' npm run protractor ' . My log is :

`$ npm run protractor

> angular-phonecat@0.0.0 preprotractor C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
> npm run copy-libs

> angular-phonecat@0.0.0 copy-libs C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
> cpx "node_modules/{angular,angular-*,bootstrap/dist,jquery/dist}/**/*" app/lib -C

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\cpx\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

> angular-phonecat@0.0.0 update-webdriver C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
> webdriver-manager update

[21:07:11] I/update - chromedriver: file exists C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_2.46.zip
[21:07:11] I/update - chromedriver: unzipping chromedriver_2.46.zip
[21:07:11] I/update - chromedriver: chromedriver_2.46.exe up to date
[21:07:11] I/update - selenium standalone: file exists C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\selenium-server-standalone-4.0.0-alpha-1.zip.jar
[21:07:11] I/update - selenium standalone: selenium-server-standalone-4.0.0-alpha-1.zip.jar up to date
[21:07:12] I/update - geckodriver: file exists C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat\node_modules\protractor\node_modules\webdriver-manager\selenium\geckodriver-v0.24.0.zip
[21:07:12] I/update - geckodriver: unzipping geckodriver-v0.24.0.zip
[21:07:13] I/update - geckodriver: geckodriver-v0.24.0.exe up to date

> angular-phonecat@0.0.0 protractor C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
> protractor e2e-tests/protractor.conf.js

[21:07:14] I/launcher - Running 1 instances of WebDriver
[21:07:15] I/local - Starting selenium standalone server...
[21:07:15] E/launcher - Error: Error: Server terminated early with status 1
    at earlyTermination.catch.e (C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat\node_modules\selenium-webdriver\remote\index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)
[21:07:15] E/launcher - Process exited with error code 100

npm ERR! Windows_NT 10.0.17134
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
npm ERR! Exit status 100
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor e2e-tests/protractor.conf.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request: ` 

And the debug log is : 
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@3.10.8
3 info using node@v7.0.0
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info lifecycle angular-phonecat@0.0.0~preprotractor: angular-phonecat@0.0.0
6 verbose lifecycle angular-phonecat@0.0.0~preprotractor: unsafe-perm in lifecycle true
7 verbose lifecycle angular-phonecat@0.0.0~preprotractor: PATH: C:\Users\clickys\AppData\Roaming\nvm\v7.0.0\node_modules\npm\bin\node-gyp-bin;C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\clickys\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\clickys\AppData\Local\Microsoft\WindowsApps;C:\Users\clickys\AppData\Roaming\Composer\vendor\bin;C:\Users\clickys\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\clickys\AppData\Roaming\nvm;C:\Program Files\nodejs
8 verbose lifecycle angular-phonecat@0.0.0~preprotractor: CWD: C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
9 silly lifecycle angular-phonecat@0.0.0~preprotractor: Args: [ '/d /s /c', 'npm run update-webdriver' ]
10 silly lifecycle angular-phonecat@0.0.0~preprotractor: Returned: code: 0  signal: null
11 info lifecycle angular-phonecat@0.0.0~protractor: angular-phonecat@0.0.0
12 verbose lifecycle angular-phonecat@0.0.0~protractor: unsafe-perm in lifecycle true
13 verbose lifecycle angular-phonecat@0.0.0~protractor: PATH: C:\Users\clickys\AppData\Roaming\nvm\v7.0.0\node_modules\npm\bin\node-gyp-bin;C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\clickys\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\clickys\AppData\Local\Microsoft\WindowsApps;C:\Users\clickys\AppData\Roaming\Composer\vendor\bin;C:\Users\clickys\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\clickys\AppData\Roaming\nvm;C:\Program Files\nodejs
14 verbose lifecycle angular-phonecat@0.0.0~protractor: CWD: C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
15 silly lifecycle angular-phonecat@0.0.0~protractor: Args: [ '/d /s /c', 'protractor e2e-tests/protractor.conf.js' ]
16 silly lifecycle angular-phonecat@0.0.0~protractor: Returned: code: 100  signal: null
17 info lifecycle angular-phonecat@0.0.0~protractor: Failed to exec protractor script
18 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
18 verbose stack Exit status 100
18 verbose stack     at EventEmitter.<anonymous> (C:\Users\clickys\AppData\Roaming\nvm\v7.0.0\node_modules\npm\lib\utils\lifecycle.js:255:16)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at EventEmitter.emit (events.js:191:7)
18 verbose stack     at ChildProcess.<anonymous> (C:\Users\clickys\AppData\Roaming\nvm\v7.0.0\node_modules\npm\lib\utils\spawn.js:40:14)
18 verbose stack     at emitTwo (events.js:106:13)
18 verbose stack     at ChildProcess.emit (events.js:191:7)
18 verbose stack     at maybeClose (internal/child_process.js:877:16)
18 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
19 verbose pkgid angular-phonecat@0.0.0
20 verbose cwd C:\Users\clickys\Desktop\Projects\WatchnCode\angular tutorial\angular-phonecat
21 error Windows_NT 10.0.17134
22 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
23 error node v7.0.0
24 error npm  v3.10.8
25 error code ELIFECYCLE
26 error angular-phonecat@0.0.0 protractor: `protractor e2e-tests/protractor.conf.js`
26 error Exit status 100
27 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor e2e-tests/protractor.conf.js'.
27 error Make sure you have the latest version of node.js and npm installed.
27 error If you do, this is most likely a problem with the angular-phonecat package,
27 error not with npm itself.
27 error Tell the author that this fails on your system:
27 error     protractor e2e-tests/protractor.conf.js
27 error You can get information on how to open an issue for this project with:
27 error     npm bugs angular-phonecat
27 error Or if that isn't available, you can get their info via:
27 error     npm owner ls angular-phonecat
27 error There is likely additional logging output above.
28 verbose exit [ 1, true ]

I have tried to install protractor globally and run it direct on the protractor e2e-tests/protractor.conf.js . But it its still doesnt work

**Comment by Clickys** [comment]
Updating dependencies
In order to avoid surprises, all dependencies listed in package.json are pinned to specific versions (this is what the package-lock.json file is about). This ensures that the same version of a dependency is installed every time.

Since all dependencies are acquired via npm, you can use the same tool to easily update them as well (although you probably don't need to for the purpose of this tutorial). Simply run the preconfigured script:

`npm run update-dep`

This solve it !

**Comment by noorball** [comment]
> Updating dependencies
> In order to avoid surprises, all dependencies listed in package.json are pinned to specific versions (this is what the package-lock.json file is about). This ensures that the same version of a dependency is installed every time.
> 
> Since all dependencies are acquired via npm, you can use the same tool to easily update them as well (although you probably don't need to for the purpose of this tutorial). Simply run the preconfigured script:
> 
> `npm run update-dep`
> 
> This solve it !

I believe the @Clickys means 
`npm run update-deps` 
This solved the problem perfectly.
