### ISSUE TITLE
Use of AngularJS markup in URL-valued attribute

### ISSUE THREAD

**Issue by dmellstrom** [angular/angular-phonecat#446]
The `phone-list` component contains some Angular double-bracket syntax inside of normal `href` attributes on links.

    <a href="#!/phones/{{phone.id}}" class="thumb">
                <img ng-src="{{phone.imageUrl}}" alt="{{phone.name}}" />
              </a>
              <a href="#!/phones/{{phone.id}}">{{phone.name}}</a>
    
This can cause link to appear with an invalid URL until the page has finished loading. The appropriate approach is to use the `ng-href` directive instead.

Reference: AngularJS Docs
https://docs.angularjs.org/api/ng/directive/ngHref

**Comment by gkalpak** [comment]
Thx for taking the time to open this issue (and a pull request), @dmellstrom. However, the issue you mention is only present for templates that could be shown before being compiled by AngularJS (e.g. stuff in `index.html`). In this case, the HTML code is inside an `ngRepeat` directive, which means that it will be compiled by AngularJS before showing on the page and therefore `href="{{ ... }}"` is fine.

##
BTW, AngularJS (1.x) is in LTS mode and we are no longer accepting changes that are not critical bug fixes into this project. See https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c for more details.
