### ISSUE TITLE
How to Deploy this project on Server.

### ISSUE THREAD

**Issue by SHUBHAMDAVE001** [angular/angular-phonecat#459]
I have a project in Angular Version 1 or AngularJS. I want to serve that project on Cpanel. Is there any way how to deploy this project or any angularJs project stand alone on the server?

**Comment by gkalpak** [comment]
You just need to host the files that. It depends of how you have set up your project, but for the Phonecat tutorial, you need to host the contents of the `app` directory.

You could use any static server (or service) for hosting the files (including Apache, Nginx, a CDN, etc.).

**Comment by SHUBHAMDAVE001** [comment]
Thank You @gkalpak .
I have set project and called index.html file.

Would like to learn how to use Nginx to serve the project on Cpanel.

**Comment by gkalpak** [comment]
That is not related to AngularJS, so I can't answer that. You can check with your hosting provider on how to run Nginx on cPanel. [This blogpost][1] might also help.

[1]: https://blog.cpanel.com/how-to-install-and-manage-nginx-on-cpanel/
