### ISSUE TITLE
Step 7 is broken (no output)

### ISSUE THREAD

**Issue by ghurley** [angular/angular-phonecat#69]
If you update to step-7 (git checkout -f step-7) and load the index page, nothing renders. There is no redirect from index.html to index.html# and there are no errors in the browser console or in the node server console. The "live demo" behaves the same way:

http://angular.github.io/angular-phonecat/step-7/app/

This is as of 2013-10-09 11:40 PDT.

All 5 e2e tests fail as well.

**Comment by RajeswarReddy** [comment]
How and where to add these dependencies? Kindly notify me.


{
  "name": "angular-phonecat",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-phonecat",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "1.4.x",
    "angular-mocks": "1.4.x",
    "jquery": "~2.1.1",
    "bootstrap": "~3.1.1",
    "angular-route": "1.4.x"
  }
}

**Comment by RajeswarReddy** [comment]
How and where to add these dependencies in 7th step in angular phonecatapp? Kindly notify me.
{
  "name": "angular-phonecat",
  "description": "A starter project for AngularJS",
  "version": "0.0.0",
  "homepage": "https://github.com/angular/angular-phonecat",
  "license": "MIT",
  "private": true,
  "dependencies": {
    "angular": "1.4.x",
    "angular-mocks": "1.4.x",
    "jquery": "~2.1.1",
    "bootstrap": "~3.1.1",
    "angular-route": "1.4.x"
  }
}

**Comment by petebacondarwin** [comment]
@RajeswarReddy - You put them in a file called `bower.json` in the root folder of your project.

**Comment by RajeswarReddy** [comment]
There are many bower.json files. 1: In angular, 2 , in Angular.animate 3)Angular.mocks which one i have to chosse?

**Comment by petebacondarwin** [comment]
The one in the root of your project

**Comment by RajeswarReddy** [comment]
In the bower components file?

**Comment by RajeswarReddy** [comment]
Kindly provide me the snapshot.This task is very important for me. @petebacondarwin

**Comment by petebacondarwin** [comment]
https://github.com/angular/angular-phonecat/blob/master/bower.json

**Comment by RajeswarReddy** [comment]
I have to create bower.json sub folder in angularphonecat ?

**Comment by petebacondarwin** [comment]
`bower.json` is a file. Yes, create it in the root of your project.

**Comment by RajeswarReddy** [comment]
OK thanku. In net i found the below links. to to include. Are they right? 

<script src="http://angular.github.io/angular-phonecat/step-7/app/lib/angular/angular.js"></script>
<script src="http://angular.github.io/angular-phonecat/step-7/app/lib/angular/angular-route.js"></script>

**Comment by RajeswarReddy** [comment]
OK thanku. In net i found the below links. to to include. Are they right?

<script src="http://angular.github.io/angular-phonecat/step-7/app/lib/angular/angular.js"></script>
<script src="http://angular.github.io/angular-phonecat/step-7/app/lib/angular/angular-route.js"></script>

**Comment by RajeswarReddy** [comment]
After updating in file, how to include the library in scripts?

**Comment by RajeswarReddy** [comment]
Can anyone kindly send me the exact folder file architecture for step 7 in phonecatapp.. step by step.

This task is much needed for me kindly reply @ghurley  @petebacondarwin  @annismckenzie @jeffkile

**Comment by RajeswarReddy** [comment]
What is the difference between bower globally installed and locally installed?
